import fs from 'node:fs/promises';
import path from 'node:path';

import { FONT_SIZES, SEVERITY_COLORS, THEME_PALETTES, TOUCH_TARGETS, type ThemeId } from '../../apps/web/src/shared/theme/palettes';

type Mode = 'write' | 'check';
type TargetApp = 'mobile' | 'patient';

const ROOT_DIR = path.resolve(__dirname, '../..');

const TARGETS: ReadonlyArray<{ app: TargetApp; relPath: string }> = [
  { app: 'mobile', relPath: 'apps/mobile/lib/core/generated/design_tokens.g.dart' },
  { app: 'patient', relPath: 'apps/patient-app/lib/core/generated/design_tokens.g.dart' },
];

function parseRemToPx(remValue: string): number {
  if (!remValue.endsWith('rem')) {
    throw new Error(`Expected rem value, got: ${remValue}`);
  }
  const rem = Number.parseFloat(remValue.replace('rem', '').trim());
  if (!Number.isFinite(rem)) {
    throw new Error(`Invalid rem value: ${remValue}`);
  }
  return rem * 16;
}

function formatNumber(value: number): string {
  if (Number.isInteger(value)) return `${value}`;
  return `${value.toFixed(3).replace(/0+$/, '').replace(/\.$/, '')}`;
}

function asDartColor(hex: string): string {
  const normalized = hex.trim().replace(/^#/, '').toUpperCase();
  if (!/^[0-9A-F]{6}$/.test(normalized)) {
    throw new Error(`Expected 6-digit hex color, got: ${hex}`);
  }
  return `Color(0xFF${normalized})`;
}

function renderPaletteEntries(): string {
  return (Object.entries(THEME_PALETTES) as Array<[ThemeId, (typeof THEME_PALETTES)[ThemeId]]>)
    .map(([themeId, palette]) => `    '${themeId}': SignacareThemePaletteToken(
      primary: ${asDartColor(palette.primary)},
      onPrimary: ${asDartColor(palette.onPrimary)},
      secondary: ${asDartColor(palette.secondary)},
      sidebar: ${asDartColor(palette.sidebar)},
      sidebarText: ${asDartColor(palette.sidebarText)},
      background: ${asDartColor(palette.background)},
      paper: ${asDartColor(palette.paper)},
      text: ${asDartColor(palette.text)},
      accent: ${asDartColor(palette.accent)},
    ),`)
    .join('\n');
}

function renderDartDesignTokens(app: TargetApp): string {
  const appBodyPx = app === 'patient' ? parseRemToPx(FONT_SIZES.patientApp) : parseRemToPx(FONT_SIZES.body);
  return `// GENERATED CODE - DO NOT EDIT BY HAND.
// Source: apps/web/src/shared/theme/palettes.ts
// Generated by: scripts/design-tokens/generate-dart-design-tokens.ts

import 'package:flutter/material.dart';

class SignacareThemePaletteToken {
  final Color primary;
  final Color onPrimary;
  final Color secondary;
  final Color sidebar;
  final Color sidebarText;
  final Color background;
  final Color paper;
  final Color text;
  final Color accent;

  const SignacareThemePaletteToken({
    required this.primary,
    required this.onPrimary,
    required this.secondary,
    required this.sidebar,
    required this.sidebarText,
    required this.background,
    required this.paper,
    required this.text,
    required this.accent,
  });
}

class SignacareDesignTokens {
  static const Color severityCritical = ${asDartColor(SEVERITY_COLORS.critical)};
  static const Color severityWarning = ${asDartColor(SEVERITY_COLORS.warning)};
  static const Color severitySuccess = ${asDartColor(SEVERITY_COLORS.success)};
  static const Color severityInfo = ${asDartColor(SEVERITY_COLORS.info)};
  static const Color severityNeutral = ${asDartColor(SEVERITY_COLORS.neutral)};

  static const double touchTargetStandardPx = ${formatNumber(TOUCH_TARGETS.standard)};
  static const double touchTargetSafetyActionPx = ${formatNumber(TOUCH_TARGETS.safetyAction)};

  static const double fontSizeTitlePx = ${formatNumber(parseRemToPx(FONT_SIZES.title))};
  static const double fontSizeHeadingPx = ${formatNumber(parseRemToPx(FONT_SIZES.heading))};
  static const double fontSizeSubheadingPx = ${formatNumber(parseRemToPx(FONT_SIZES.subheading))};
  static const double fontSizeBodyPx = ${formatNumber(parseRemToPx(FONT_SIZES.body))};
  static const double fontSizeBodySmallPx = ${formatNumber(parseRemToPx(FONT_SIZES.bodySmall))};
  static const double fontSizeCaptionPx = ${formatNumber(parseRemToPx(FONT_SIZES.caption))};
  static const double fontSizePatientAppPx = ${formatNumber(parseRemToPx(FONT_SIZES.patientApp))};
  static const double appBodySizePx = ${formatNumber(appBodyPx)};

  static const Map<String, SignacareThemePaletteToken> themePalettes = {
${renderPaletteEntries()}
  };
}
`;
}

async function writeFileIfChanged(absPath: string, content: string): Promise<boolean> {
  await fs.mkdir(path.dirname(absPath), { recursive: true });
  const existing = await fs.readFile(absPath, 'utf8').catch(() => null);
  if (existing === content) return false;
  await fs.writeFile(absPath, content, 'utf8');
  return true;
}

async function run(mode: Mode): Promise<void> {
  const dirty: string[] = [];
  for (const target of TARGETS) {
    const absPath = path.join(ROOT_DIR, target.relPath);
    const generated = renderDartDesignTokens(target.app);
    if (mode === 'write') {
      const changed = await writeFileIfChanged(absPath, generated);
      if (changed) {
        console.log(`updated ${target.relPath}`);
      } else {
        console.log(`no change ${target.relPath}`);
      }
      continue;
    }

    const existing = await fs.readFile(absPath, 'utf8').catch(() => null);
    if (existing !== generated) dirty.push(target.relPath);
  }

  if (mode === 'check') {
    if (dirty.length === 0) {
      console.log('OK: Dart design tokens are in sync with web SSoT.');
      return;
    }
    console.error('FAIL: Dart design token files are out of sync with web SSoT.');
    for (const rel of dirty) console.error(` - ${rel}`);
    console.error('Run: npm run tokens:generate:dart');
    process.exitCode = 1;
  }
}

function parseMode(argv: string[]): Mode {
  return argv.includes('--check') ? 'check' : 'write';
}

const mode = parseMode(process.argv.slice(2));
run(mode).catch((err) => {
  console.error(err);
  process.exitCode = 1;
});

export { renderDartDesignTokens, parseRemToPx, asDartColor };
