import * as billingRepo from './billingRepository';
import { feeScheduleService } from './feeScheduleService';
import { referralValidityService } from './referralValidityService';
import { todayLocal } from '../../utils/dateUtils';
import { createTaskInternal } from '../tasks/taskService';
import logger from '../../utils/logger';
import { jobBus } from '../../shared/jobBus';
import { generateInvoiceNumber } from '../../shared/utils/numberGenerator';
import type {
  BillingAccountCreateDTO,
  BillingAccountResponse,
  InvoiceCreateDTO,
  InvoiceResponse,
  InvoiceApproveDTO,
  PaymentCreateDTO,
  PaymentResponse,
  ClaimUpdateDTO,
} from '@signacare/shared';

const GST_RATE = 0.1;

function notFound(msg: string, code: string): Error & { status: number; code: string } {
  const err = new Error(msg) as Error & { status: number; code: string };
  err.status = 404;
  err.code = code;
  return err;
}

function badRequest(msg: string, code: string): Error & { status: number; code: string } {
  const err = new Error(msg) as Error & { status: number; code: string };
  err.status = 400;
  err.code = code;
  return err;
}

function mapAccount(row: Record<string, unknown>): BillingAccountResponse {
  return {
    id: row['id'] as string,
    clinicId: row['clinic_id'] as string,
    patientId: row['patient_id'] as string,
    billingType: row['billing_type'] as BillingAccountResponse['billingType'],
    healthFundName: (row['health_fund_name'] as string | undefined) ?? undefined,
    healthFundMemberNumber:
      (row['health_fund_member_number'] as string | undefined) ?? undefined,
    ndisNumber: (row['ndis_number'] as string | undefined) ?? undefined,
    ndisPackageManager:
      (row['ndis_package_manager'] as string | undefined) ?? undefined,
    dvaNumber: (row['dva_number'] as string | undefined) ?? undefined,
    dvaCardType:
      (row['dva_card_type'] as BillingAccountResponse['dvaCardType']) ?? undefined,
    notes: (row['notes'] as string | undefined) ?? undefined,
    createdAt: row['created_at'] as string,
    updatedAt: row['updated_at'] as string,
  };
}

function mapInvoice(
  row: Record<string, unknown> & { lineItems: Record<string, unknown>[] },
): InvoiceResponse {
  return {
    id: row['id'] as string,
    clinicId: row['clinic_id'] as string,
    patientId: row['patient_id'] as string,
    clinicianId: (row['clinician_id'] as string | null) ?? null,
    appointmentId: (row['appointment_id'] as string | null) ?? null,
    invoiceNumber: row['invoice_number'] as string,
    billingType: (row['billing_type'] as string) ?? 'private',
    subtotalCents: Number(row['subtotal_cents'] ?? row['subtotal'] ?? 0),
    gstCents: Number(row['gst_cents'] ?? row['gst_amount'] ?? 0),
    totalCents: Number(row['total_cents'] ?? row['total_amount'] ?? 0),
    paidCents: Number(row['paid_cents'] ?? row['paid_amount'] ?? 0),
    gapCents: Number(row['gap_cents'] ?? 0),
    scheduleFeeCents: Number(row['schedule_fee_cents'] ?? 0),
    rebateCents: Number(row['rebate_cents'] ?? 0),
    providerFeeCents: Number(row['provider_fee_cents'] ?? 0),
    status: (row['status'] as string) ?? 'draft',
    dueDate: (row['due_date'] as string | null) ?? null,
    notes: (row['notes'] as string | null) ?? null,
    autoGenerated: Boolean(row['auto_generated']),
    overrideNotes: (row['override_notes'] as string | null) ?? null,
    referralValid: row['referral_valid'] !== false,
    approvedAt: (row['approved_at'] as string | null) ?? null,
    approvedByStaffId: (row['approved_by_staff_id'] as string | null) ?? null,
    sentAt: (row['sent_at'] as string | null) ?? null,
    lineItems: (row.lineItems ?? []).map((li) => ({
      id: li['id'] as string,
      invoiceId: li['invoice_id'] as string,
      mbsItemNumber: (li['mbs_item_number'] as string | undefined) ?? (li['mbs_item_code'] as string | undefined),
      description: li['description'] as string,
      quantity: Number(li['quantity']),
      unitPriceCents: Number(li['unit_price_cents'] ?? li['unit_price'] ?? li['fee_cents'] ?? 0),
      discountCents: Number(li['discount_cents'] ?? li['discount_amount'] ?? 0),
      lineTotalCents: Number(li['line_total_cents'] ?? li['line_total'] ?? 0),
      scheduleFeeCents: Number(li['schedule_fee_cents'] ?? 0),
    })),
    createdAt: row['created_at'] as string,
    updatedAt: row['updated_at'] as string,
  };
}

function mapPayment(row: Record<string, unknown>): PaymentResponse {
  return {
    id: row['id'] as string,
    clinicId: row['clinic_id'] as string,
    invoiceId: row['invoice_id'] as string,
    receivedById: row['received_by_id'] as string,
    amount: Number(row['amount']),
    paymentMethod: row['payment_method'] as PaymentResponse['paymentMethod'],
    paymentDate: row['payment_date'] as string,
    referenceNumber: (row['reference_number'] as string | undefined) ?? undefined,
    claimStatus: (row['claim_status'] as PaymentResponse['claimStatus']) ?? null,
    claimReference: (row['claim_reference'] as string | null) ?? null,
    notes: (row['notes'] as string | undefined) ?? undefined,
    createdAt: row['created_at'] as string,
    updatedAt: row['updated_at'] as string,
  };
}

// ── Billing Accounts ──────────────────────────────────────────────────────────

export async function upsertBillingAccount(
  clinicId: string,
  dto: BillingAccountCreateDTO,
): Promise<BillingAccountResponse> {
  const row = await billingRepo.upsertBillingAccount(clinicId, dto);
  return mapAccount(row);
}

export async function getBillingAccount(
  clinicId: string,
  patientId: string,
): Promise<BillingAccountResponse | null> {
  const row = await billingRepo.getBillingAccount(clinicId, patientId);
  return row ? mapAccount(row) : null;
}

// ── Invoices ──────────────────────────────────────────────────────────────────

export async function createInvoice(
  clinicId: string,
  dto: InvoiceCreateDTO,
): Promise<InvoiceResponse> {
  const subtotal = dto.lineItems.reduce(
    (sum, li) => sum + li.unitPriceCents * li.quantity - (li.discountCents ?? 0),
    0,
  );
  // GST applies to private billing only; bulk-bill, DVA and NDIS are GST-free
  const gstAmount =
    dto.billingType === 'private'
      ? Math.round(subtotal * GST_RATE * 100) / 100
      : 0;
  const totalAmount = Math.round((subtotal + gstAmount) * 100) / 100;
  const invoiceNumber = await generateInvoiceNumber(clinicId);

  const row = await billingRepo.createInvoice(
    clinicId,
    dto,
    invoiceNumber,
    subtotal,
    gstAmount,
    totalAmount,
  );
  return mapInvoice(row);
}

export async function listInvoicesByPatient(
  clinicId: string,
  patientId: string,
): Promise<InvoiceResponse[]> {
  const rows = await billingRepo.findInvoicesByPatient(clinicId, patientId);
  return Promise.all(
    rows.map(async (r) => {
      const full = await billingRepo.getInvoiceWithItems(clinicId, r['id'] as string);
      return mapInvoice(full!);
    }),
  );
}

export async function getInvoice(
  clinicId: string,
  invoiceId: string,
): Promise<InvoiceResponse> {
  const row = await billingRepo.getInvoiceWithItems(clinicId, invoiceId);
  if (!row) throw notFound('Invoice not found', 'INVOICE_NOT_FOUND');
  return mapInvoice(row);
}

export async function voidInvoice(
  clinicId: string,
  invoiceId: string,
): Promise<void> {
  const row = await billingRepo.getInvoiceWithItems(clinicId, invoiceId);
  if (!row) throw notFound('Invoice not found', 'INVOICE_NOT_FOUND');
  if (row['paid_amount'] && Number(row['paid_amount']) > 0) {
    throw badRequest(
      'Cannot void an invoice with payments recorded',
      'INVOICE_HAS_PAYMENTS',
    );
  }
  await billingRepo.voidInvoice(clinicId, invoiceId);
}

// ── Payments ──────────────────────────────────────────────────────────────────

export async function recordPayment(
  clinicId: string,
  receivedById: string,
  dto: PaymentCreateDTO,
): Promise<PaymentResponse> {
  const invoice = await billingRepo.getInvoiceWithItems(clinicId, dto.invoiceId);
  if (!invoice) throw notFound('Invoice not found', 'INVOICE_NOT_FOUND');

  const status = invoice['status'] as string;
  if (status === 'void' || status === 'refunded') {
    throw badRequest(
      'Cannot record payment on a void or refunded invoice',
      'INVOICE_CLOSED',
    );
  }

  const remaining =
    Number(invoice['total_amount']) - Number(invoice['paid_amount']);
  if (dto.amount > remaining + 0.001) {
    throw badRequest(
      `Payment amount ${dto.amount} exceeds outstanding balance ${remaining.toFixed(2)}`,
      'PAYMENT_EXCEEDS_BALANCE',
    );
  }

  const row = await billingRepo.createPayment(clinicId, receivedById, dto);
  const payment = mapPayment(row);

  try {
    const patientId = (invoice['patient_id'] as string | null) ?? null;
    const invoiceNumber = (invoice['invoice_number'] as string | null) ?? null;
    if (patientId) {
      const amountCents = Math.max(0, Math.round(payment.amount));
      await jobBus.enqueue('email', {
        type: 'billing_notice',
        clinicId,
        patientId,
        invoiceId: dto.invoiceId,
        paymentId: payment.id,
        amountCents,
        currency: 'AUD',
        title: invoiceNumber ? `Payment receipt — ${invoiceNumber}` : 'Payment receipt',
        body: `We have received your payment of AUD ${(amountCents / 100).toFixed(2)}.`,
      });
    }
  } catch (err) {
    logger.warn({ err, clinicId, invoiceId: dto.invoiceId }, 'Failed to enqueue payment receipt email');
  }

  return payment;
}

export async function listPaymentsByInvoice(
  clinicId: string,
  invoiceId: string,
): Promise<PaymentResponse[]> {
  const rows = await billingRepo.findPaymentsByInvoice(clinicId, invoiceId);
  return rows.map(mapPayment);
}

export async function updateClaimStatus(
  clinicId: string,
  paymentId: string,
  dto: ClaimUpdateDTO,
): Promise<void> {
  await billingRepo.updatePaymentClaimStatus(clinicId, paymentId, dto);
}

// ── Auto-Invoice on Appointment Completion ────────────────────────────────────

/**
 * Auto-generate a draft invoice when an appointment is completed.
 * The clinician must review and approve before it's sent.
 */
export async function autoGenerateInvoice(
  clinicId: string,
  staffId: string,
  appointment: {
    id: string;
    patientId: string;
    clinicianId: string;
    type: string;
    startTime: string;
    endTime: string;
  },
): Promise<InvoiceResponse | null> {
  // 1. Suggest MBS item based on appointment
  const suggestion = await feeScheduleService.suggestMbsItem(
    clinicId, appointment.clinicianId, appointment,
  );
  if (!suggestion) {
    logger.info({ clinicId, appointmentId: appointment.id }, 'No MBS item suggestion — skipping auto-invoice');
    return null;
  }

  // 2. Check referral validity
  const { valid: referralValid } = await referralValidityService.checkValidity(
    clinicId, appointment.patientId,
  );

  // 3. Determine billing type from patient's billing account
  const account = await billingRepo.getBillingAccount(clinicId, appointment.patientId);
  const billingType = (account?.billing_type as string) ?? 'private';

  // 4. Calculate GST (private only)
  const gstCents = billingType === 'private'
    ? Math.round(suggestion.providerFeeCents * GST_RATE)
    : 0;
  const totalCents = suggestion.providerFeeCents + gstCents;

  // 5. Create draft invoice
  const invoiceNumber = await generateInvoiceNumber(clinicId);
  const today = todayLocal();
  const dueDate = new Date(today);
  dueDate.setDate(dueDate.getDate() + 30);
  const dueDateStr = dueDate.toISOString().split('T')[0];

  const row = await billingRepo.createAutoInvoice(clinicId, {
    patient_id: appointment.patientId,
    clinician_id: appointment.clinicianId,
    appointment_id: appointment.id,
    invoice_number: invoiceNumber,
    service_date: today,
    mbs_item_code: suggestion.itemNumber,
    mbs_item_description: suggestion.description,
    billing_type: billingType,
    subtotal_cents: suggestion.providerFeeCents,
    gst_cents: gstCents,
    total_cents: totalCents,
    paid_cents: 0,
    gap_cents: suggestion.gapCents,
    schedule_fee_cents: suggestion.scheduleFeeCents,
    rebate_cents: suggestion.rebateCents,
    provider_fee_cents: suggestion.providerFeeCents,
    status: 'draft',
    due_date: dueDateStr,
    auto_generated: true,
    referral_valid: referralValid,
    notes: suggestion.reason,
  }, [{
    mbs_item_code: suggestion.itemNumber,
    description: suggestion.description,
    quantity: 1,
    unit_price_cents: suggestion.providerFeeCents,
    discount_cents: 0,
    line_total_cents: suggestion.providerFeeCents,
    schedule_fee_cents: suggestion.scheduleFeeCents,
  }]);

  // 6. Create task for clinician to review
  try {
    await createTaskInternal(clinicId, staffId, {
      assignedToId: appointment.clinicianId,
      patientId: appointment.patientId,
      title: `Review draft invoice ${invoiceNumber}`,
      description: `Auto-generated invoice for ${suggestion.description}. Provider fee: $${(suggestion.providerFeeCents / 100).toFixed(2)}, Gap: $${(suggestion.gapCents / 100).toFixed(2)}${!referralValid ? ' — WARNING: No valid referral on file' : ''}`,
      priority: 'medium',
    });
  } catch (err) {
    logger.warn({ err, clinicId }, 'Failed to create invoice review task');
  }

  const full = await billingRepo.getInvoiceWithItems(clinicId, row.id as string);
  return full ? mapInvoice(full) : null;
}

// ── Invoice Approval ──────────────────────────────────────────────────────────

/**
 * Approve a draft invoice. Clinician can override MBS item and fee before approving.
 */
export async function approveInvoice(
  clinicId: string,
  staffId: string,
  invoiceId: string,
  dto: InvoiceApproveDTO,
): Promise<InvoiceResponse> {
  const invoice = await billingRepo.getInvoiceWithItems(clinicId, invoiceId);
  if (!invoice) throw notFound('Invoice not found', 'INVOICE_NOT_FOUND');

  const status = invoice['status'] as string;
  if (status !== 'draft' && status !== 'pending_approval') {
    throw badRequest('Only draft invoices can be approved', 'INVALID_STATUS');
  }

  // Apply overrides if provided
  const updates: Record<string, unknown> = {
    status: 'approved',
    approved_at: new Date(),
    approved_by_staff_id: staffId,
    updated_at: new Date(),
  };

  if (dto.overrideNotes) {
    updates.override_notes = dto.overrideNotes;
  }

  if (dto.overrideItemNumber || dto.overrideFeeCents !== undefined) {
    // Require override notes when changing the suggested item/fee
    if (!dto.overrideNotes) {
      throw badRequest('Override notes are required when changing the auto-suggested item or fee', 'OVERRIDE_NOTES_REQUIRED');
    }

    if (dto.overrideItemNumber) {
      const feeItem = await feeScheduleService.getByItemNumber(clinicId, dto.overrideItemNumber);
      if (feeItem) {
        updates.mbs_item_code = dto.overrideItemNumber;
        updates.mbs_item_description = feeItem.description;
        updates.schedule_fee_cents = feeItem.scheduleFeeCents;
        updates.rebate_cents = Math.round(feeItem.scheduleFeeCents * 0.85);
      }
    }

    if (dto.overrideFeeCents !== undefined) {
      const scheduleFee = (updates.schedule_fee_cents as number) ?? Number(invoice['schedule_fee_cents'] ?? 0);
      updates.provider_fee_cents = dto.overrideFeeCents;
      updates.gap_cents = dto.overrideFeeCents - scheduleFee;
      updates.subtotal_cents = dto.overrideFeeCents;
      const billingType = invoice['billing_type'] as string;
      const gstCents = billingType === 'private' ? Math.round(dto.overrideFeeCents * GST_RATE) : 0;
      updates.gst_cents = gstCents;
      updates.total_cents = dto.overrideFeeCents + gstCents;

      // Update line item too
      if (invoice.lineItems?.length) {
        const { db: dbConn } = await import('../../db/db');
        const firstItemId = invoice.lineItems[0]['id'] as string;
        await dbConn('invoice_line_items')
          .where({ invoice_id: invoiceId, id: firstItemId })
          .update({
            unit_price_cents: dto.overrideFeeCents,
            line_total_cents: dto.overrideFeeCents,
          });
      }
    }
  }

  await billingRepo.updateInvoice(clinicId, invoiceId, updates);

  const updated = await billingRepo.getInvoiceWithItems(clinicId, invoiceId);
  return mapInvoice(updated!);
}

/**
 * Mark an approved invoice as sent to the patient.
 * Also shares the invoice to the patient's Viva app.
 */
export async function markInvoiceSent(
  clinicId: string,
  invoiceId: string,
): Promise<void> {
  const invoice = await billingRepo.getInvoiceWithItems(clinicId, invoiceId);
  if (!invoice) return;

  await billingRepo.updateInvoice(clinicId, invoiceId, {
    status: 'sent',
    sent_at: new Date(),
    updated_at: new Date(),
  });

  try {
    const patientId = (invoice['patient_id'] as string | null) ?? null;
    const invoiceNumber = (invoice['invoice_number'] as string | null) ?? invoiceId;
    const totalCents = Number(invoice['total_cents'] ?? invoice['total_amount'] ?? 0);
    if (patientId) {
      await jobBus.enqueue('email', {
        type: 'billing_notice',
        clinicId,
        patientId,
        invoiceId,
        amountCents: Number.isFinite(totalCents) ? Math.max(0, Math.round(totalCents)) : undefined,
        currency: 'AUD',
        title: `Invoice issued — ${invoiceNumber}`,
        body: `Your invoice ${invoiceNumber} has been issued and is now available.`,
      });
    }
  } catch (err) {
    logger.warn({ err, clinicId, invoiceId }, 'Failed to enqueue invoice-issued email');
  }

  // Share invoice to patient's Viva app as a shared document
  const patientId = invoice['patient_id'] as string;
  if (patientId) {
    try {
      const { db: dbConn } = await import('../../db/db');
      const invoiceNum = invoice['invoice_number'] as string;
      const totalCents = Number(invoice['total_cents'] ?? invoice['total_amount'] ?? 0);
      const gapCents = Number(invoice['gap_cents'] ?? 0);

      await dbConn('patient_shared_documents').insert({
        clinic_id: clinicId,
        patient_id: patientId,
        title: `Invoice ${invoiceNum} — $${(totalCents / 100).toFixed(2)}${gapCents > 0 ? ` (Gap: $${(gapCents / 100).toFixed(2)})` : ''}`,
        doc_type: 'invoice',
        url: `billing/invoices/${invoiceId}`,
        file_path: null,
        shared_by: invoice['clinician_id'] ?? invoice['approved_by_staff_id'] ?? null,
      });

      logger.info({ clinicId, invoiceId, patientId }, 'Invoice shared to patient Viva app');
    } catch (err) {
      logger.warn({ err, clinicId, invoiceId }, 'Failed to share invoice to Viva — invoice still marked as sent');
    }
  }
}
