// apps/api/src/features/llm/letterRoutes.ts
//
// Tier 15 — letter authoring routes.
//
// State machine:
//   draft → in_review → approved → sent
//          ↳ revised (rejected) → in_review → ...
//          ↳ withdrawn (terminal)
//
// Every state-changing endpoint delegates to letterService so the
// letters row + letter_sections rows + letter_audit_log row are
// written inside the same transaction.

import { Router, type Request, type Response, type NextFunction } from 'express';
import { z } from 'zod';
import { authMiddleware } from '../../middleware/authMiddleware';
import { requireRoles } from '../../middleware/rbacMiddleware';
import { requireFeatureEnabled } from '../../middleware/featureFlagMiddleware';
import { db } from '../../db/db';
import { buildAuthContext } from '../../shared/buildAuthContext';
import { requirePatientRelationship } from '../../shared/authGuards';
import {
  createDraftLetter, regenerateSection, editSection,
  submitForReview, approveLetter, rejectLetter,
} from './letterService';
import {
  deliverLetter, exportLetter, openRevision,
} from './letterDeliveryService';

const router = Router();
router.use(authMiddleware);
// Letter authoring is gated by the same scribe kill-switch because
// the sections are generated by the same model surface. If AI is
// paused, manual letter authoring still works (via editSection) but
// regeneration is blocked.
router.use(requireFeatureEnabled('ai-scribe'));

// ── Templates ──────────────────────────────────────────────────────────────

router.get('/templates',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const category = typeof req.query.category === 'string' ? req.query.category : undefined;
      let q = db('letter_templates')
        .where(function () {
          this.whereNull('clinic_id').orWhere({ clinic_id: req.clinicId });
        })
        .andWhere({ is_active: true })
        .select(
          'id', 'clinic_id as clinicId', 'code', 'name', 'category',
          'description', 'sections', 'is_active as isActive',
          'requires_second_review as requiresSecondReview',
        )
        .orderBy([{ column: 'category', order: 'asc' }, { column: 'name', order: 'asc' }]);
      if (category) q = q.andWhere({ category });
      const rows = await q;
      res.json({ templates: rows });
    } catch (err) { next(err); }
  },
);

// ── Letters ────────────────────────────────────────────────────────────────

const CreateLetterSchema = z.object({
  templateId: z.string().uuid(),
  patientId: z.string().uuid(),
  episodeId: z.string().uuid().optional(),
  sessionId: z.string().uuid().optional(),
  subject: z.string().min(1).max(300),
  recipients: z.array(z.object({
    name: z.string().min(1).max(200),
    address: z.string().max(500).optional(),
    email: z.string().email().max(200).optional(),
    role: z.string().max(60).optional(),
  })).optional(),
});

router.post('/',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const dto = CreateLetterSchema.parse(req.body);
      const auth = buildAuthContext(req, dto.patientId);
      await requirePatientRelationship(auth, dto.patientId);
      const result = await createDraftLetter(auth, dto);
      res.status(201).json(result);
    } catch (err) { next(err); }
  },
);

router.get('/',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const status = typeof req.query.status === 'string' ? req.query.status : undefined;
      const patientId = typeof req.query.patientId === 'string' ? req.query.patientId : undefined;
      let q = db('letters')
        .where({ clinic_id: req.clinicId })
        .select(
          'id', 'template_id as templateId', 'patient_id as patientId',
          'episode_id as episodeId', 'author_id as authorId',
          'status', 'subject', 'revision',
          'approved_by as approvedBy', 'approved_at as approvedAt',
          'sent_by as sentBy', 'sent_at as sentAt',
          'created_at as createdAt', 'updated_at as updatedAt',
        )
        .orderBy('updated_at', 'desc')
        .limit(200);
      if (status) q = q.andWhere({ status });
      if (patientId) q = q.andWhere({ patient_id: patientId });
      const rows = await q;
      res.json({ letters: rows });
    } catch (err) { next(err); }
  },
);

router.get('/:id',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const letter = await db('letters')
        .where({ id: req.params.id, clinic_id: req.clinicId })
        .first();
      if (!letter) { res.status(404).json({ error: 'Not found' }); return; }
      const sections = await db('letter_sections')
        .where({ letter_id: letter.id, clinic_id: req.clinicId })
        .select(
          'id', 'section_key as sectionKey', 'label', 'content',
          'section_order as sectionOrder', 'regen_count as regenCount',
          'last_regen_at as lastRegenAt', 'last_regen_by as lastRegenBy',
        )
        .orderBy('section_order', 'asc');
      res.json({
        letter: {
          id: letter.id,
          clinicId: letter.clinic_id,
          templateId: letter.template_id,
          patientId: letter.patient_id,
          episodeId: letter.episode_id,
          authorId: letter.author_id,
          sessionId: letter.session_id,
          status: letter.status,
          subject: letter.subject,
          recipients: letter.recipients,
          renderedText: letter.rendered_text,
          approvedBy: letter.approved_by,
          approvedAt: letter.approved_at,
          sentBy: letter.sent_by,
          sentAt: letter.sent_at,
          revision: letter.revision,
          createdAt: letter.created_at,
          updatedAt: letter.updated_at,
        },
        sections,
      });
    } catch (err) { next(err); }
  },
);

// ── Section regeneration / edit ────────────────────────────────────────────

const SectionPatchSchema = z.object({
  content: z.string().max(20_000),
  source: z.enum(['regenerated', 'edited']).default('edited'),
});

router.patch('/:id/sections/:sectionKey',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { content, source } = SectionPatchSchema.parse(req.body);
      const auth = buildAuthContext(req);
      const fn = source === 'regenerated' ? regenerateSection : editSection;
      const result = await fn(auth, req.params.id, req.params.sectionKey, content);
      res.json(result);
    } catch (err) { next(err); }
  },
);

// ── Lifecycle transitions ─────────────────────────────────────────────────

router.post('/:id/submit',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const auth = buildAuthContext(req);
      await submitForReview(auth, req.params.id);
      res.status(204).end();
    } catch (err) { next(err); }
  },
);

router.post('/:id/approve',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const auth = buildAuthContext(req);
      await approveLetter(auth, req.params.id);
      res.status(204).end();
    } catch (err) { next(err); }
  },
);

const RejectSchema = z.object({ reason: z.string().min(3).max(1000) });

router.post('/:id/reject',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { reason } = RejectSchema.parse(req.body);
      const auth = buildAuthContext(req);
      await rejectLetter(auth, req.params.id, reason);
      res.status(204).end();
    } catch (err) { next(err); }
  },
);

// ── Review queue + audit log ──────────────────────────────────────────────

router.get('/review-queue/list',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const rows = await db('letters')
        .where({ clinic_id: req.clinicId, status: 'in_review' })
        .select(
          'id', 'template_id as templateId', 'patient_id as patientId',
          'author_id as authorId', 'subject', 'revision',
          'created_at as createdAt', 'updated_at as updatedAt',
        )
        .orderBy('updated_at', 'asc')
        .limit(200);
      res.json({ letters: rows });
    } catch (err) { next(err); }
  },
);

router.get('/:id/audit-log',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const rows = await db('letter_audit_log')
        .where({ letter_id: req.params.id, clinic_id: req.clinicId })
        .select(
          'id', 'event', 'actor_id as actorId', 'actor_role as actorRole',
          'section_key as sectionKey', 'diff_summary as diffSummary',
          'created_at as createdAt',
        )
        .orderBy('created_at', 'asc');
      res.json({ events: rows });
    } catch (err) { next(err); }
  },
);

// ── Tier 16.1 — Delivery ────────────────────────────────────────────────────

const DeliverSchema = z.object({
  channel: z.enum(['healthlink', 'mhr_docref', 'email', 'fax', 'print', 'secure_link']),
  recipientName: z.string().min(1).max(300),
  recipientAddress: z.string().max(500).optional(),
  recipientEmail: z.string().email().max(200).optional(),
  recipientFax: z.string().max(30).optional(),
  recipientMhrIhi: z.string().max(20).optional(),
});

router.post('/:id/deliver',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const dto = DeliverSchema.parse(req.body);
      const auth = buildAuthContext(req);
      const result = await deliverLetter(auth, req.params.id, dto);
      // 202 Accepted on queued, 200 on delivered, 502 on failed (letter
      // is persisted as 'failed' so admin can see the retry path).
      const code = result.status === 'delivered' ? 200
        : result.status === 'queued' || result.status === 'in_flight' ? 202
        : 502;
      res.status(code).json(result);
    } catch (err) { next(err); }
  },
);

router.get('/:id/deliveries',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const rows = await db('letter_deliveries')
        .where({ letter_id: req.params.id, clinic_id: req.clinicId })
        .select(
          'id', 'channel', 'recipient_name as recipientName',
          'recipient_address as recipientAddress',
          'recipient_email as recipientEmail',
          'recipient_fax as recipientFax',
          'recipient_mhr_ihi as recipientMhrIhi',
          'status', 'receipt_id as receiptId',
          'sent_by as sentBy', 'attempted_at as attemptedAt',
          'delivered_at as deliveredAt', 'error',
          'attempt_count as attemptCount',
          'created_at as createdAt', 'updated_at as updatedAt',
        )
        .orderBy('created_at', 'desc');
      res.json({ deliveries: rows });
    } catch (err) { next(err); }
  },
);

// ── Tier 16.2 — Exports ─────────────────────────────────────────────────────

const ExportSchema = z.object({
  format: z.enum(['pdf', 'cda_document', 'fhir_composition', 'plain_text']),
});

router.post('/:id/export',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { format } = ExportSchema.parse(req.body);
      const auth = buildAuthContext(req);
      const result = await exportLetter(auth, req.params.id, format);
      const contentType =
        format === 'pdf' ? 'application/pdf'
        : format === 'cda_document' ? 'application/xml'
        : format === 'fhir_composition' ? 'application/fhir+json'
        : 'text/plain';
      res.setHeader('Content-Type', contentType);
      res.setHeader('X-Export-Id', result.exportId);
      res.setHeader('X-Export-Ref', result.contentRef);
      res.status(201).send(result.content);
    } catch (err) { next(err); }
  },
);

router.get('/:id/exports',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const rows = await db('letter_exports')
        .where({ letter_id: req.params.id, clinic_id: req.clinicId })
        .select(
          'id', 'format', 'content_ref as contentRef',
          'content_size_bytes as contentSizeBytes',
          'generated_by as generatedBy',
          'generated_at as generatedAt',
        )
        .orderBy('generated_at', 'desc');
      res.json({ exports: rows });
    } catch (err) { next(err); }
  },
);

// ── Tier 16.3 — Translations ────────────────────────────────────────────────
//
// POST /:id/translations accepts a pre-computed translation from
// upstream (client calls the model, then persists). Centralising the
// translation model choice belongs in the model-version-locked scribe
// pipeline (Tier 19), not in this route — a client-supplied
// translation keeps the API stable across model swaps.

const TranslationUpsertSchema = z.object({
  languageCode: z.string().min(2).max(5),
  translatedText: z.string().min(1).max(50_000),
  translatorModel: z.string().min(1).max(100),
});

router.post('/:id/translations',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const dto = TranslationUpsertSchema.parse(req.body);

      // BUG-276 L4 absorb — translations create a second PHI artefact
      // (translated content). An unrelated clinician must not be able
      // to author a translation for another patient's letter. Resolve
      // the letter first to get patient_id, then gate.
      const letter = await db('letters')
        .where({ id: req.params.id, clinic_id: req.clinicId })
        .first();
      if (!letter) { res.status(404).json({ error: 'Letter not found' }); return; }
      const auth = buildAuthContext(req, letter.patient_id);
      await requirePatientRelationship(auth, letter.patient_id);

      // Upsert on (letter_id, language_code). If there's an existing
      // translation for that language, replace it and bump
      // translated_at so the caller's stale cache is invalidated.
      const existing = await db('letter_translations')
        .where({ letter_id: req.params.id, language_code: dto.languageCode, clinic_id: req.clinicId })
        .first();

      let rowId: string;
      if (existing) {
        await db('letter_translations')
          .where({ id: existing.id, clinic_id: req.clinicId })
          .update({
            translated_text: dto.translatedText,
            translator_model: dto.translatorModel,
            translated_by: req.user!.id,
            translated_at: new Date(),
          });
        rowId = existing.id;
      } else {
        const [r] = await db('letter_translations')
          .insert({
            clinic_id: req.clinicId,
            letter_id: req.params.id,
            language_code: dto.languageCode,
            translated_text: dto.translatedText,
            translator_model: dto.translatorModel,
            translated_by: req.user!.id,
          })
          .returning(['id']);
        rowId = r.id;
      }

      res.status(existing ? 200 : 201).json({ id: rowId, languageCode: dto.languageCode });
    } catch (err) { next(err); }
  },
);

router.get('/:id/translations',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const rows = await db('letter_translations')
        .where({ letter_id: req.params.id, clinic_id: req.clinicId })
        .select(
          'id', 'language_code as languageCode', 'translator_model as translatorModel',
          'translated_text as translatedText',
          'translated_by as translatedBy',
          'translated_at as translatedAt',
        )
        .orderBy('language_code', 'asc');
      res.json({ translations: rows });
    } catch (err) { next(err); }
  },
);

// ── Tier 16.4 — Post-approval revisions ─────────────────────────────────────

const RevisionSchema = z.object({
  reasonCategory: z.enum([
    'factual_correction', 'typo', 'recipient_change',
    'patient_request', 'clinical_update', 'legal_correction', 'other',
  ]),
  reasonDetail: z.string().min(5).max(2000),
});

router.post('/:id/revise',
  requireRoles(['clinician', 'admin', 'superadmin']),
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const { reasonCategory, reasonDetail } = RevisionSchema.parse(req.body);
      const auth = buildAuthContext(req);
      const result = await openRevision(auth, req.params.id, reasonCategory, reasonDetail);
      res.status(201).json(result);
    } catch (err) { next(err); }
  },
);

router.get('/:id/revisions',
  async (req: Request, res: Response, next: NextFunction) => {
    try {
      const rows = await db('letter_revisions')
        .where({ letter_id: req.params.id, clinic_id: req.clinicId })
        .select(
          'id', 'revision_number as revisionNumber',
          'previous_rendered_text as previousRenderedText',
          'reason_category as reasonCategory', 'reason_detail as reasonDetail',
          'requested_by as requestedBy', 'created_at as createdAt',
        )
        .orderBy('revision_number', 'desc');
      res.json({ revisions: rows });
    } catch (err) { next(err); }
  },
);

export default router;
