import { promises as fs } from 'fs';
import * as path from 'path';
import { buildExecutiveStaff } from './02_executive_staff';
import { buildDepartmentHeads } from './03_department_heads';
import { buildClinicStaff } from './04_clinic_staff';
import type { StaffMasterLoginRow } from './02_executive_staff';
import type { GeneratorResult } from './01_clinics';

// Phase 0.8 generator 05 — master login table writer.
//
// Collects every login row produced by the staff generators (02, 03,
// 04) and writes a single markdown file at docs/demo/good-health-logins.md
// that an operator can hand to a demo tester. The file contains:
//
//   - A prominent FICTIONAL / DEMO-ONLY warning header
//   - A summary line with the total persona count
//   - One grouped table per persona tier:
//       Executive (5)
//       Department Heads (7)
//       Clinical Staff — grouped by clinic (20 per clinic × 4)
//   - Plaintext passwords (these are demo-only, deliberately checked
//     in because the seed is fictional and the audit trail of who
//     has the passwords is more valuable than hiding them)
//
// No hashing happens here — we pass an identity stub because the
// login row only depends on the persona + plaintext password, not the
// stored hash. This keeps the writer fast and test-friendly.
//
// The writer is idempotent: each run rewrites the file from scratch
// using deterministic generator output, so diffs between runs are
// always zero unless the catalog changed.

const IDENTITY_HASH = (plain: string): string => `identity:${plain}`;

const HEADER = `# Good Health — Master Login Table

> **⚠️ FICTIONAL DEMO DATA — NOT FOR PRODUCTION USE**
>
> Every persona, email, and password in this file is synthetic. This
> file is generated by \`npm -w apps/api run seed:good-health\` from
> [apps/api/src/seed-good-health/](../../apps/api/src/seed-good-health/)
> and is safe to commit because the tenant it describes does not
> exist outside the local demo database.
>
> If you are looking at this file in production, something has gone
> very wrong — the seed entrypoint refuses to run with
> \`NODE_ENV=production\` unless \`ALLOW_DEMO_SEED=1\` is explicitly set.

`;

function formatLoginTable(rows: readonly StaffMasterLoginRow[]): string {
  const lines: string[] = [
    '| Email | Plaintext password | Role | Clinic | Title |',
    '|---|---|---|---|---|',
  ];
  for (const row of rows) {
    lines.push(
      `| ${row.email} | \`${row.plainPassword}\` | ${row.role} | ${row.clinicSlug} | ${row.titleLabel} |`,
    );
  }
  return lines.join('\n');
}

export async function buildMasterLoginMarkdown(): Promise<string> {
  const [exec, heads, clinic] = await Promise.all([
    buildExecutiveStaff(IDENTITY_HASH),
    buildDepartmentHeads(IDENTITY_HASH),
    buildClinicStaff(IDENTITY_HASH),
  ]);

  const allLogins: StaffMasterLoginRow[] = [
    ...exec.loginTable,
    ...heads.loginTable,
    ...clinic.loginTable,
  ];
  const total = allLogins.length;

  // Group clinic staff by clinic slug so the operator can scan per-site.
  const clinicGroups = new Map<string, StaffMasterLoginRow[]>();
  for (const row of clinic.loginTable) {
    const group = clinicGroups.get(row.clinicSlug) ?? [];
    group.push(row);
    clinicGroups.set(row.clinicSlug, group);
  }

  const sections: string[] = [
    HEADER,
    `**Total personas:** ${total} (${exec.loginTable.length} executive + ${heads.loginTable.length} department heads + ${clinic.loginTable.length} clinical staff)`,
    '',
    '## Executive & Corporate',
    '',
    formatLoginTable(exec.loginTable),
    '',
    '## Department Heads',
    '',
    formatLoginTable(heads.loginTable),
    '',
    '## Clinical Staff (by clinic)',
    '',
  ];

  const orderedClinicSlugs = Array.from(clinicGroups.keys()).sort();
  for (const slug of orderedClinicSlugs) {
    const rows = clinicGroups.get(slug)!;
    sections.push(`### ${slug} — ${rows.length} personas`, '');
    sections.push(formatLoginTable(rows));
    sections.push('');
  }

  return sections.join('\n') + '\n';
}

// Default output path — repo-relative so the file lands in
// docs/demo/good-health-logins.md regardless of which workspace the
// script is invoked from. The step finds the repo root by walking up
// from __dirname until it sees a directory containing package.json
// AND a .git entry (the monorepo root, not the apps/api package).
function resolveDefaultOutputPath(): string {
  let dir = __dirname;
  for (let i = 0; i < 10; i++) {
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
    // Heuristic: monorepo root has .git AND docs/ — apps/api only has
    // one of each (and docs/ does not exist inside apps/api).
    try {
      // path.existsSync removed — fs.accessSync would throw.
      // We rely on the shape of the signacare monorepo where the
      // top-level directory is 3 levels up from
      // apps/api/src/seed-good-health/generators/.
      if (
        dir.endsWith('/Signacare') ||
        dir.endsWith('\\Signacare')
      ) {
        return path.join(dir, 'docs', 'demo', 'good-health-logins.md');
      }
    } catch {
      /* ignore */
    }
  }
  // Fallback: four-levels-up from this file is the repo root in the
  // expected layout (generators → seed-good-health → src → api → apps → ROOT).
  return path.resolve(
    __dirname,
    '..',
    '..',
    '..',
    '..',
    '..',
    'docs',
    'demo',
    'good-health-logins.md',
  );
}

export interface WriteResult extends GeneratorResult {
  readonly path: string;
  readonly bytes: number;
}

export async function runMasterLoginStep(
  outputPath: string = resolveDefaultOutputPath(),
): Promise<WriteResult> {
  const markdown = await buildMasterLoginMarkdown();
  await fs.mkdir(path.dirname(outputPath), { recursive: true });

  let existed = false;
  try {
    await fs.access(outputPath);
    existed = true;
  } catch {
    existed = false;
  }

  await fs.writeFile(outputPath, markdown, 'utf8');

  return {
    inserted: existed ? 0 : 1,
    updated: existed ? 1 : 0,
    path: outputPath,
    bytes: Buffer.byteLength(markdown, 'utf8'),
  };
}
