/**
 * BUG-336 + BUG-339 regression — /hi-service/verify-hpii + verify-hpio
 *
 * Admin-facing endpoints that wrap the hiServiceClient.verifyHpii /
 * verifyHpio helpers. Under the default CI env the NASH mTLS cert is
 * absent, so the endpoints run in "stub" mode: format + Luhn pass
 * returns { found: true, hpii|hpio, error: '…unverified' }; format
 * failure returns { found: false, error: 'Invalid HPI-… format' }.
 *
 * Also covers BUG-339 clinic update: PUT /clinics/:id with hpio +
 * npdsConformanceId + erxEtp1SiteId writes through to the row.
 *
 * Coverage (9 tests):
 *   T1 — /verify-hpii with bad format → 400
 *   T2 — /verify-hpii with valid format (Luhn) → found:true + unverified
 *   T3 — /verify-hpii without auth → 401
 *   T4 — /verify-hpio with bad format → 400
 *   T5 — /verify-hpio with valid format (Luhn) → found:true + unverified
 *   T6 — /verify-hpio without auth → 401
 *   T7 — PUT /clinics/:id persists hpio + npdsConformanceId + erxEtp1SiteId
 *   T8 — PUT /clinics/:id with malformed hpio → 422 (zod regex)
 *   T9 — GET /clinics/:id returns hpio + npdsConformanceId + erxEtp1SiteId
 */

import { describe, it, expect, beforeAll } from 'vitest';
import { isIntegrationReady, loginAsAdmin, authedAgent } from './_helpers';

const READY = await isIntegrationReady();

// Pre-computed valid HPI-I / HPI-O numbers (prefix + 10-digit suffix + Luhn-correct).
// Production codes are real; these are test-space values that happen to pass Luhn.
// Generated by iterating the last digit of a candidate prefix until the Luhn
// checksum lands. Format validators in hiNumbers.ts confirm correctness.
const VALID_HPII = '8003611234567893';
const VALID_HPIO = '8003621234567892';

describe.skipIf(!READY)('BUG-336/339 HI Service verify + clinic eRx fields', () => {
  let token: string;
  let clinicId: string;

  beforeAll(async () => {
    const session = await loginAsAdmin();
    token = session.token;
    clinicId = session.clinicId;
  });

  describe('HPI-I verify (/hi-service/verify-hpii)', () => {
    it('T1 — malformed HPI-I rejected at schema layer (422 VALIDATION_ERROR)', async () => {
      const agent = authedAgent(token);
      const res = await agent.post('/api/v1/hi-service/verify-hpii').send({ hpii: 'not-a-number' });
      expect(res.status).toBe(422);
    });

    it('T2 — valid HPI-I returns found:true in stub mode', async () => {
      const agent = authedAgent(token);
      const res = await agent.post('/api/v1/hi-service/verify-hpii').send({ hpii: VALID_HPII });
      expect(res.status).toBe(200);
      expect(res.body.found).toBe(true);
      expect(res.body.hpii).toBe(VALID_HPII);
      // Stub-mode marker — frontend surfaces the warning banner from this field
      expect(res.body.error).toMatch(/unverified/i);
    });

    it('T3 — /verify-hpii without auth returns 401/403', async () => {
      const request = (await import('supertest')).default;
      const app = (await import('../../src/server')).default;
      const res = await request(app)
        .post('/api/v1/hi-service/verify-hpii')
        .set('X-CSRF-Token', 'test')
        .send({ hpii: VALID_HPII });
      expect([401, 403]).toContain(res.status);
    });
  });

  describe('HPI-O verify (/hi-service/verify-hpio)', () => {
    it('T4 — malformed HPI-O rejected at schema layer (422 VALIDATION_ERROR)', async () => {
      const agent = authedAgent(token);
      const res = await agent.post('/api/v1/hi-service/verify-hpio').send({ hpio: '800362xxx' });
      expect(res.status).toBe(422);
    });

    it('T5 — valid HPI-O returns found:true in stub mode', async () => {
      const agent = authedAgent(token);
      const res = await agent.post('/api/v1/hi-service/verify-hpio').send({ hpio: VALID_HPIO });
      expect(res.status).toBe(200);
      expect(res.body.found).toBe(true);
      expect(res.body.hpio).toBe(VALID_HPIO);
      expect(res.body.error).toMatch(/unverified/i);
    });

    it('T6 — /verify-hpio without auth returns 401/403', async () => {
      const request = (await import('supertest')).default;
      const app = (await import('../../src/server')).default;
      const res = await request(app)
        .post('/api/v1/hi-service/verify-hpio')
        .set('X-CSRF-Token', 'test')
        .send({ hpio: VALID_HPIO });
      expect([401, 403]).toContain(res.status);
    });
  });

  describe('Clinic eRx fields (BUG-339 update path)', () => {
    it('T7 — PUT /clinics/:id persists hpio + npdsConformanceId + erxEtp1SiteId', async () => {
      const agent = authedAgent(token);
      const res = await agent
        .put(`/api/v1/clinics/${clinicId}`)
        .send({
          hpio: VALID_HPIO,
          npdsConformanceId: 'NPDS-TEST-2026',
          erxEtp1SiteId: 'ETP1-TEST-0001',
        });
      expect(res.status).toBe(200);
      expect(res.body.hpio).toBe(VALID_HPIO);
      expect(res.body.npdsConformanceId).toBe('NPDS-TEST-2026');
      expect(res.body.erxEtp1SiteId).toBe('ETP1-TEST-0001');

      // Cleanup: clear the fields so a rerun doesn't collide with the
      // T8 regex-rejection path (which doesn't know the pre-state).
      await agent.put(`/api/v1/clinics/${clinicId}`).send({
        hpio: null,
        npdsConformanceId: null,
        erxEtp1SiteId: null,
      });
    });

    it('T8 — PUT /clinics/:id with malformed hpio rejected by validateBody middleware (422)', async () => {
      const agent = authedAgent(token);
      const res = await agent.put(`/api/v1/clinics/${clinicId}`).send({ hpio: '800362-bad' });
      expect(res.status).toBe(422);
    });

    it('T9 — GET /clinics/:id returns the three eRx fields', async () => {
      const agent = authedAgent(token);
      const res = await agent.get(`/api/v1/clinics/${clinicId}`);
      expect(res.status).toBe(200);
      // Fields present on the response shape (null when unset).
      expect(res.body).toHaveProperty('hpio');
      expect(res.body).toHaveProperty('npdsConformanceId');
      expect(res.body).toHaveProperty('erxEtp1SiteId');
    });
  });
});
