/**
 * scripts/generate-types/emitter.ts
 *
 * Phase 0b.1b-i — extracted from `scripts/generate-types-from-migrations.ts`
 * per L5 0b.1a advisory #2 (god-file split). Pure function (no I/O); type-map
 * lookups + string assembly only. Re-export contract verified via the
 * umbrella test suite — see fix-registry rows + commit body.
 *
 * Phase 0b.1b-i absorbs L5 0b.1a advisory #3 (decimal precision): when a
 * `decimal` column carries `decimalPrecision` + `decimalScale` from the
 * parser, emit `z.string().regex(/^-?\d{1,M}(\.\d{0,S})?$/)` instead of
 * bare `z.string()`. Captures the precision contract that Knex's bare
 * `z.string()` discarded. L3 absorb-2 (cycle-1 REJECT): integer-digit
 * count clamped to >=1 (Math.max(1, P-S)) so NUMERIC(4,5) etc. produce
 * valid regex (Knex emits "0.12345" with leading zero — integer part is
 * always >=1 digit).
 *
 * RESPONSIBILITY: emit per-table TS Row interface (snake_case) + Zod DTO
 * scaffold (camelCase) + Zod Response scaffold (camelCase). Type maps
 * are the canonical Knex → TS / Knex → Zod translation table.
 */

import { type KnexColumnType, type ColumnDef } from './parser';
import { type TableState } from './replayer';

export const TS_TYPE_MAP: Record<KnexColumnType, string> = {
  uuid: 'string',
  string: 'string',
  text: 'string',
  integer: 'number',
  bigInteger: 'number',
  boolean: 'boolean',
  date: 'string',
  timestamp: 'string',
  time: 'string',
  jsonb: 'unknown',
  json: 'unknown',
  decimal: 'string',
  specificType: 'unknown',
  unknown: 'unknown',
};

export const ZOD_TYPE_MAP: Record<KnexColumnType, string> = {
  uuid: 'z.string().uuid()',
  string: 'z.string()',
  text: 'z.string()',
  integer: 'z.number().int()',
  bigInteger: 'z.number().int()',
  boolean: 'z.boolean()',
  date: 'z.string()', // ISO YYYY-MM-DD
  // CLAUDE.md §5.1 + §15 (Phase R1 PR-R1-11): *At fields backed by Postgres
  // timestamp must use `.datetime()` validator. Knex `timestamp` column
  // produces ISO datetime strings; emit the stricter Zod chain.
  timestamp: 'z.string().datetime()',
  time: 'z.string()',
  jsonb: 'z.unknown()',
  json: 'z.unknown()',
  decimal: 'z.string()',
  specificType: 'z.unknown()',
  unknown: 'z.unknown()',
};

/**
 * Phase 0b.1b-i absorb of L5 0b.1a advisory #3: per-column Zod expression
 * factoring in decimal precision + scale + string max length.
 */
export function zodExpressionForColumn(col: ColumnDef): string {
  let expr = ZOD_TYPE_MAP[col.knexType];
  if (col.knexType === 'string' && col.stringMaxLength) {
    expr = `z.string().max(${col.stringMaxLength})`;
  }
  if (col.knexType === 'decimal' && col.decimalPrecision !== undefined) {
    // Postgres NUMERIC(precision, scale): precision = total digits, scale = digits after decimal point.
    // Knex returns string for precision preservation. Emit a Zod regex matching that constraint.
    // L3 absorb-2 (cycle-1 REJECT): use Math.max(1, ...) — NUMERIC(4,5) is valid Postgres
    // (fractional-only domains: correlation coefficients, normalized scores). Knex returns
    // such values as "0.12345" with a leading zero, so the integer part is always ≥1 digit.
    // Math.max(0, ...) would emit `\d{1,0}` — an invalid regex quantifier that crashes at
    // RegExp() construction time when the consumer imports the scaffold.
    const integerDigits = col.decimalScale !== undefined
      ? Math.max(1, col.decimalPrecision - col.decimalScale)
      : col.decimalPrecision;
    if (col.decimalScale !== undefined && col.decimalScale > 0) {
      expr = `z.string().regex(/^-?\\d{1,${integerDigits}}(\\.\\d{0,${col.decimalScale}})?$/)`;
    } else {
      expr = `z.string().regex(/^-?\\d{1,${integerDigits}}$/)`;
    }
  }
  return expr;
}

function snakeToCamel(s: string): string {
  return s.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

function snakeToPascal(s: string): string {
  return s.charAt(0).toUpperCase() + snakeToCamel(s.slice(1));
}

function tableToTypePrefix(table: string): string {
  return snakeToPascal(table);
}

const HEADER_ROW = `// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run \`npm run generate:types-from-migrations\` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).
`;

const HEADER_DTO = `// AUTO-GENERATED scaffold by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Hand-written DTO must \`extends\` this scaffold's
// Zod schema OR carry a \`// @scaffold-divergence: <reason>\` annotation.
// The scaffold-extension guard (Phase 0b.1b) enforces this at merge gate.
`;

const HEADER_RESPONSE = `// AUTO-GENERATED scaffold by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Hand-written Response must \`extends\` this
// scaffold's Zod schema OR carry a \`// @scaffold-divergence: <reason>\`
// annotation. The scaffold-extension guard (Phase 0b.1b) enforces this.
`;

export function emitRowInterface(table: TableState): string {
  const ifaceName = `${tableToTypePrefix(table.name)}Row`;
  const fields: string[] = [];
  for (const col of table.columns.values()) {
    const tsType = TS_TYPE_MAP[col.knexType];
    const optional = col.nullable ? '?' : '';
    const nullableSuffix = col.nullable ? ' | null' : '';
    fields.push(`  ${col.name}${optional}: ${tsType}${nullableSuffix};`);
  }
  // Phase 0b.2a (operator-authorized 2026-05-04): emit a runtime column
  // constant + a Column union type alongside the Row interface so consumers
  // can import a single source of truth for the table's column set instead
  // of hand-writing `*_COLUMNS` constants that drift silently when migrations
  // add columns. Naming convention: SCREAMING_SNAKE_CASE for the runtime
  // constant + PascalCase + `Column` suffix for the union type. See Phase
  // 0b.2 plan + CLAUDE.md §15 for the SD-class drift this prevents.
  const columnsConstName = `${table.name.toUpperCase()}_COLUMNS`;
  const columnUnionName = `${tableToTypePrefix(table.name)}Column`;
  const columnLiterals = Array.from(table.columns.values()).map((c) => `  '${c.name}',`);
  return `${HEADER_ROW}
export interface ${ifaceName} {
${fields.join('\n')}
}

export const ${columnsConstName} = [
${columnLiterals.join('\n')}
] as const;

export type ${columnUnionName} = typeof ${columnsConstName}[number];
`;
}

export function emitDtoScaffold(table: TableState): string {
  const schemaName = `${tableToTypePrefix(table.name)}DtoScaffoldSchema`;
  const typeName = `${tableToTypePrefix(table.name)}DtoScaffold`;
  const fields: string[] = [];
  for (const col of table.columns.values()) {
    const camelName = snakeToCamel(col.name);
    let zodExpr = zodExpressionForColumn(col);
    if (col.nullable) zodExpr = `${zodExpr}.nullable().optional()`;
    fields.push(`  ${camelName}: ${zodExpr},`);
  }
  return `${HEADER_DTO}
import { z } from 'zod';

export const ${schemaName} = z.object({
${fields.join('\n')}
});

export type ${typeName} = z.infer<typeof ${schemaName}>;
`;
}

export function emitResponseScaffold(table: TableState): string {
  const schemaName = `${tableToTypePrefix(table.name)}ResponseScaffoldSchema`;
  const typeName = `${tableToTypePrefix(table.name)}ResponseScaffold`;
  const fields: string[] = [];
  for (const col of table.columns.values()) {
    const camelName = snakeToCamel(col.name);
    let zodExpr = zodExpressionForColumn(col);
    if (col.nullable) zodExpr = `${zodExpr}.nullable().optional()`;
    fields.push(`  ${camelName}: ${zodExpr},`);
  }
  return `${HEADER_RESPONSE}
import { z } from 'zod';

export const ${schemaName} = z.object({
${fields.join('\n')}
});

export type ${typeName} = z.infer<typeof ${schemaName}>;
`;
}
