/**
 * CI guard: every `export interface X(Row|Db)` bound to a table via
 * `db<X>('<table>')` must declare a field set that EXACTLY matches the
 * columns of that table — both directions.
 *
 * BUG-529 — bidirectional §15 invariant.
 *
 * Forward direction (original, SD12–SD21 class):
 *   every interface field MUST exist as a DB column. A field on the
 *   interface that doesn't exist in the DB means `.insert({ ...row })`
 *   crashes at runtime — but TS compiles cleanly because the field IS
 *   declared. This guard closes that blind spot.
 *
 * Reverse direction (NEW, BUG-458 / BUG-489 class):
 *   every DB column MUST be declared in the interface (or explicitly
 *   exempt). When a real DB column is omitted from the interface,
 *   downstream mappers fabricate a literal (`null`, `false`, `''`) for
 *   that column and silently drop the source-of-truth value on every
 *   write. Compiles cleanly; fails clinically.
 *
 * Data source: apps/api/src/db/schema-snapshot.json — regenerated by
 * `npm run db:snapshot --workspace=apps/api` after every migration. The
 * integration-test job runs a live check against Postgres as a second
 * line of defence (tests/integration/schemaDrift.test.ts).
 *
 * Whole-interface exemptions (annotate the JSDoc with exactly one):
 *   @schema-drift-exempt select-aliased  — columns come from SELECT col AS alias
 *   @schema-drift-exempt aggregation     — derived shape (GROUP BY, JSON agg, view)
 *   @schema-drift-exempt response-shape  — API response after service-layer mapping
 *   @schema-drift-exempt partial-shape   — IS a row, deliberate sub-projection
 *
 * The first three skip BOTH directions (the interface isn't a row at
 * all). `partial-shape` is asymmetric: skips REVERSE direction only;
 * forward direction is still enforced (a sub-projection still must not
 * declare phantom columns).
 *
 * Per-column allowlist: scripts/guards/check-row-interface-matches-db.allowlist
 *   <table>.<column>  # BUG-NNN — reason
 * Exempts the named column from the reverse-direction check only. For
 * surgical cases where most columns should be declared but specific
 * ones are deliberately excluded.
 *
 * Exit code:
 *   0  — every interface matches the DB (forward + reverse)
 *   1  — drift detected
 *   2  — allowlist file is malformed or stale (self-cleaning gate)
 */

import { readFileSync, readdirSync, statSync } from 'fs';
import { resolve } from 'path';

interface SchemaSnapshot {
  generatedAt: string;
  database: string;
  tables: Record<string, string[]>;
}

interface InterfaceCheck {
  file: string;
  lineNo: number;
  interfaceName: string;
  fields: string[];
  boundTable: string | null;
  exemptReason: string | null;
}

export interface RunCheckResult {
  exitCode: 0 | 1 | 2;
  violations: string[];
  scanned: number;
  verified: number;
  exempt: number;
  unbound: number;
}

const ALLOWLIST_PATH = resolve(__dirname, 'check-row-interface-matches-db.allowlist');

function walkTs(dir: string, out: string[] = []): string[] {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    const full = resolve(dir, entry);
    const s = statSync(full);
    if (s.isDirectory()) {
      if (entry === 'node_modules' || entry === 'dist' || entry === '__tests__') continue;
      walkTs(full, out);
    } else if (entry.endsWith('.ts') && !entry.endsWith('.d.ts') && !entry.endsWith('.test.ts')) {
      out.push(full);
    }
  }
  return out;
}

function parseFile(file: string): InterfaceCheck[] {
  const src = readFileSync(file, 'utf-8');
  const lines = src.split('\n');
  const checks: InterfaceCheck[] = [];

  const ifaceRe = /^export interface (\w+(?:Row|Db))\s*\{/;

  for (let i = 0; i < lines.length; i++) {
    const m = ifaceRe.exec(lines[i]);
    if (!m) continue;
    const interfaceName = m[1];

    // Walk backward through the contiguous JSDoc block (if any) above the
    // interface looking for `@schema-drift-exempt <reason>`. The block is
    // delimited by the first line that is neither blank nor a JSDoc line
    // (`/**`, `*/`, `* …`, `//`). No fixed line cap — rely on the
    // semantic boundary so multi-paragraph JSDoc annotations are reachable.
    let exemptReason: string | null = null;
    for (let j = i - 1; j >= 0; j--) {
      const line = lines[j];
      const em = /@schema-drift-exempt\s+(select-aliased|aggregation|response-shape|partial-shape)/.exec(line);
      if (em) { exemptReason = em[1]; break; }
      const trimmed = line.trim();
      const isJsdoc = trimmed.startsWith('*') || trimmed.startsWith('/*') || trimmed.startsWith('//');
      if (!isJsdoc && trimmed !== '') break;
    }

    // Field extraction: handles BOTH multi-line ("  field: type;\n") AND
    // inline-semicolon ("  id: string; clinic_id: string;") interface
    // styles. We walk character-by-character at depth 1 only, splitting
    // on ';' to recover top-level field declarations. Nested type
    // literals ({ x: number }) at depth >= 2 are ignored.
    const fields: string[] = [];
    let depth = 1;
    let bodyDone = false;
    for (let j = i + 1; j < lines.length && !bodyDone; j++) {
      const line = lines[j];
      const segments: string[] = [''];
      for (const ch of line) {
        if (ch === '{') { depth++; continue; }
        if (ch === '}') {
          depth--;
          if (depth <= 0) { bodyDone = true; break; }
          continue;
        }
        if (depth === 1) {
          if (ch === ';') segments.push('');
          else segments[segments.length - 1] += ch;
        }
      }
      for (const seg of segments) {
        const fm = /^\s*(\w+)\??\s*:/.exec(seg);
        if (fm && !fm[1].startsWith('_')) fields.push(fm[1]);
      }
    }

    let boundTable: string | null = null;
    const genericRe = new RegExp(
      `(?:db|trx|dbAdmin|dbRead|dbConn|dbWrite|conn)\\s*<\\s*${interfaceName}\\s*>\\s*\\(\\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]`,
    );
    const gm = genericRe.exec(src);
    if (gm) boundTable = gm[1];

    if (!boundTable) {
      const castRe = new RegExp(
        `as\\s+${interfaceName}(?:\\s*\\[\\s*\\]|\\s*\\||\\s*;|\\s*\\))`,
      );
      const cm = castRe.exec(src);
      if (cm) {
        const window = src.substring(Math.max(0, cm.index - 2000), cm.index);
        const tableMatches = [
          ...window.matchAll(/(?:db|trx|dbAdmin|dbRead|dbConn|dbWrite|conn)(?:<[^>]+>)?\s*\(\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]/g),
          ...window.matchAll(/\(\s*(?:trx|db|dbAdmin|dbRead|dbConn|dbWrite)\s*(?:\?\?|\|\|)\s*(?:trx|db|dbAdmin|dbRead|dbConn|dbWrite)\s*\)\s*\(\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]/g),
        ];
        if (tableMatches.length > 0) {
          tableMatches.sort((a, b) => (b.index ?? 0) - (a.index ?? 0));
          boundTable = tableMatches[0][1];
        }
      }
    }

    if (!boundTable) {
      const classRe = new RegExp(`extends\\s+\\w*Repository\\s*<\\s*${interfaceName}\\s*>`);
      if (classRe.test(src)) {
        const tblConst = /(?:TABLE_NAME|TABLE)\s*=\s*['"]([A-Za-z_][A-Za-z0-9_]*)['"]/.exec(src);
        if (tblConst) boundTable = tblConst[1];
      }
    }

    checks.push({ file, lineNo: i + 1, interfaceName, fields, boundTable, exemptReason });
  }
  return checks;
}

function parseAllowlist(
  allowlistPath: string,
  snapshot: SchemaSnapshot,
): { entries: Set<string>; errors: string[] } {
  const entries = new Set<string>();
  const errors: string[] = [];

  let content: string;
  try {
    content = readFileSync(allowlistPath, 'utf-8');
  } catch {
    return { entries, errors };
  }

  const lines = content.split('\n');
  for (let i = 0; i < lines.length; i++) {
    const raw = lines[i];
    const commentIdx = raw.indexOf('#');
    const beforeComment = commentIdx >= 0 ? raw.substring(0, commentIdx) : raw;
    const trimmed = beforeComment.trim();
    if (trimmed === '') continue;

    const m = /^([A-Za-z_][A-Za-z0-9_]*)\.([A-Za-z_][A-Za-z0-9_]*)$/.exec(trimmed);
    if (!m) {
      errors.push(`allowlist line ${i + 1}: malformed entry "${trimmed}" — expected "<table>.<column> # BUG-NNN — reason"`);
      continue;
    }
    const [, table, column] = m;
    if (!snapshot.tables[table]) {
      errors.push(`allowlist line ${i + 1}: stale entry "${trimmed}" — table "${table}" does not exist in schema snapshot`);
      continue;
    }
    if (!snapshot.tables[table].includes(column)) {
      errors.push(`allowlist line ${i + 1}: stale entry "${trimmed}" — column "${column}" does not exist on table "${table}"`);
      continue;
    }
    entries.add(`${table}.${column}`);
  }

  return { entries, errors };
}

function relpath(p: string, root: string): string {
  return p.startsWith(root) ? p.substring(root.length + 1) : p;
}

export function runCheck(
  rootDir: string,
  snapshotPath: string,
  allowlistPath: string,
): RunCheckResult {
  const snapshot = JSON.parse(readFileSync(snapshotPath, 'utf-8')) as SchemaSnapshot;
  const scanRoot = resolve(rootDir, 'apps', 'api', 'src');

  const { entries: allowlist, errors: allowlistErrors } = parseAllowlist(allowlistPath, snapshot);
  if (allowlistErrors.length > 0) {
    return {
      exitCode: 2,
      violations: allowlistErrors,
      scanned: 0,
      verified: 0,
      exempt: 0,
      unbound: 0,
    };
  }

  const tsFiles = walkTs(scanRoot);
  const violations: string[] = [];
  let scanned = 0;
  let verified = 0;
  let exempt = 0;
  let unbound = 0;

  for (const f of tsFiles) {
    const checks = parseFile(f);
    for (const c of checks) {
      scanned++;

      // Whole-interface exemption (skip BOTH directions): select-aliased,
      // aggregation, response-shape. partial-shape is asymmetric — handled
      // below per-direction.
      if (c.exemptReason && c.exemptReason !== 'partial-shape') {
        exempt++;
        continue;
      }
      if (!c.boundTable) {
        unbound++;
        continue;
      }
      const dbCols = snapshot.tables[c.boundTable];
      if (!dbCols) {
        violations.push(
          `${relpath(c.file, rootDir)}:${c.lineNo}  ${c.interfaceName} → table "${c.boundTable}" does not exist in schema snapshot.\n` +
          `     Possible causes: typo in db<${c.interfaceName}>('${c.boundTable}'), missing migration, or snapshot is stale.\n` +
          `     Fix: verify the table name + run \`npm run db:snapshot --workspace=apps/api\` after migrations.`,
        );
        continue;
      }

      const phantomFields = c.fields.filter((field) => !dbCols.includes(field));

      // Reverse direction: every DB column must be declared in the
      // interface (or allowlisted). Skipped for partial-shape interfaces.
      const realButUndeclared = c.exemptReason === 'partial-shape'
        ? []
        : dbCols.filter((col) => !c.fields.includes(col) && !allowlist.has(`${c.boundTable}.${col}`));

      const hasForward = phantomFields.length > 0;
      const hasReverse = realButUndeclared.length > 0;

      if (!hasForward && !hasReverse) {
        verified++;
        continue;
      }

      let msg = `${relpath(c.file, rootDir)}:${c.lineNo}  ${c.interfaceName} → table "${c.boundTable}"\n`;
      if (hasForward) {
        msg += `  Interface declares fields that don't exist in the DB:\n`;
        for (const field of phantomFields) {
          const low = field.toLowerCase();
          const near = dbCols.filter((col) => col.toLowerCase().includes(low.replace(/[^a-z0-9]/g, '')));
          msg += near.length > 0
            ? `      ${field}  →  ${near.join(', ')}\n`
            : `      ${field}  →  (no near match — column may need a migration)\n`;
        }
        msg += `  Fix one of:\n`;
        msg += `    1. Rename the interface field to match the DB column.\n`;
        msg += `    2. Add a migration that adds the missing column.\n`;
        msg += `    3. Annotate the JSDoc with @schema-drift-exempt {select-aliased|aggregation|response-shape}\n`;
        msg += `       if this interface is a SELECT-result, aggregation, or API-response shape.\n`;
      }
      if (hasReverse) {
        msg += `  DB has columns NOT declared in the interface (BUG-529 reverse direction):\n`;
        for (const col of realButUndeclared) msg += `      ${col}\n`;
        msg += `  Either:\n`;
        msg += `    a) declare these columns in the interface (preferred — closes silent-drop class), OR\n`;
        msg += `    b) annotate the interface JSDoc with "@schema-drift-exempt partial-shape"\n`;
        msg += `       if this interface is a deliberate sub-projection, OR\n`;
        msg += `    c) add specific entries to scripts/guards/check-row-interface-matches-db.allowlist\n` +
               `       in the form: <table>.<column>  # BUG-NNN — reason\n`;
      }
      violations.push(msg);
    }
  }

  return {
    exitCode: violations.length > 0 ? 1 : 0,
    violations,
    scanned,
    verified,
    exempt,
    unbound,
  };
}

function main(): void {
  const repoRoot = resolve(__dirname, '..', '..');
  const snapshotPath = resolve(repoRoot, 'apps', 'api', 'src', 'db', 'schema-snapshot.json');

  let result: RunCheckResult;
  try {
    result = runCheck(repoRoot, snapshotPath, ALLOWLIST_PATH);
  } catch (err) {
    console.error(`FAIL: cannot read schema snapshot at ${snapshotPath}`);
    console.error(`  Run: npm run db:snapshot --workspace=apps/api`);
    console.error(`  Error: ${err instanceof Error ? err.message : String(err)}`);
    process.exit(1);
  }

  console.error(`\n→ check-row-interface-matches-db (BUG-529 bidirectional)`);
  console.error(`  snapshot:    ${snapshotPath}`);
  console.error(`  allowlist:   ${ALLOWLIST_PATH}`);
  console.error(`  scanned:     ${result.scanned} interface(s)`);
  console.error(`  verified:    ${result.verified}`);
  console.error(`  exempt:      ${result.exempt}`);
  console.error(`  unbound:     ${result.unbound}  (no db<Iface>('table') binding — skipped)`);

  if (result.exitCode === 2) {
    console.error(`\n✗ FAIL: allowlist file is malformed or stale (exit 2):\n`);
    for (const v of result.violations) console.error(`  ${v}`);
    console.error(`\n  Fix: edit ${ALLOWLIST_PATH} to match the snapshot or remove stale entries.`);
    process.exit(2);
  }

  if (result.exitCode === 1) {
    console.error(`\n✗ FAIL: ${result.violations.length} interface(s) drift from DB:\n`);
    for (const v of result.violations) console.error(v + '\n');
    console.error(`Rule: CLAUDE.md §15 — TS row interfaces must match the DB schema (bidirectional, BUG-529).`);
    console.error(`Fix-registry: ROW-IFACE-DRIFT, BUG-529 anchors.`);
    process.exit(1);
  }

  console.error(`\n✓ All interfaces match their DB tables (forward + reverse).`);
}

if (require.main === module) {
  main();
}
