// AUTO-GENERATED scaffold by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Hand-written Response must `extends` this
// scaffold's Zod schema OR carry a `// @scaffold-divergence: <reason>`
// annotation. The scaffold-extension guard (Phase 0b.1b) enforces this.

import { z } from 'zod';

export const InvoicesResponseScaffoldSchema = z.object({
  id: z.string().uuid(),
  clinicId: z.string().uuid(),
  patientId: z.string().uuid().nullable().optional(),
  clinicianId: z.string().uuid().nullable().optional(),
  invoiceNumber: z.string().max(50).nullable().optional(),
  serviceDate: z.string().nullable().optional(),
  mbsItemCode: z.string().max(20).nullable().optional(),
  mbsItemDescription: z.string().max(300).nullable().optional(),
  feeCents: z.number().int().nullable().optional(),
  status: z.string().max(30).nullable().optional(),
  paymentMethod: z.string().max(50).nullable().optional(),
  notes: z.string().nullable().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  appointmentId: z.string().uuid().nullable().optional(),
  billingType: z.string().max(30).nullable().optional(),
  subtotalCents: z.number().int().nullable().optional(),
  gstCents: z.number().int().nullable().optional(),
  totalCents: z.number().int().nullable().optional(),
  paidCents: z.number().int().nullable().optional(),
  gapCents: z.number().int().nullable().optional(),
  scheduleFeeCents: z.number().int().nullable().optional(),
  rebateCents: z.number().int().nullable().optional(),
  providerFeeCents: z.number().int().nullable().optional(),
  dueDate: z.string().nullable().optional(),
  approvedAt: z.string().datetime().nullable().optional(),
  approvedByStaffId: z.string().uuid().nullable().optional(),
  sentAt: z.string().datetime().nullable().optional(),
  autoGenerated: z.boolean(),
  overrideNotes: z.string().nullable().optional(),
  referralValid: z.boolean().nullable().optional(),
});

export type InvoicesResponseScaffold = z.infer<typeof InvoicesResponseScaffoldSchema>;
