// AUTO-GENERATED scaffold by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Hand-written Response must `extends` this
// scaffold's Zod schema OR carry a `// @scaffold-divergence: <reason>`
// annotation. The scaffold-extension guard (Phase 0b.1b) enforces this.

import { z } from 'zod';

export const PatientsResponseScaffoldSchema = z.object({
  id: z.string().uuid(),
  clinicId: z.string().uuid(),
  emrNumber: z.string().max(50).nullable().optional(),
  givenName: z.string().max(100),
  familyName: z.string().max(100),
  preferredName: z.string().max(100).nullable().optional(),
  dateOfBirth: z.string(),
  gender: z.string().max(100).nullable().optional(),
  pronouns: z.string().max(50).nullable().optional(),
  email: z.string().max(255).nullable().optional(),
  emailPrimary: z.string().max(512).nullable().optional(),
  phoneMobile: z.string().max(512).nullable().optional(),
  phoneHome: z.string().max(512).nullable().optional(),
  addressLine1: z.string().max(512).nullable().optional(),
  addressLine2: z.string().max(255).nullable().optional(),
  suburb: z.string().max(512).nullable().optional(),
  state: z.string().max(30).nullable().optional(),
  postcode: z.string().max(10).nullable().optional(),
  country: z.string().max(60).nullable().optional(),
  status: z.string().max(30),
  medicareNumber: z.string().max(512).nullable().optional(),
  medicareReference: z.string().max(512).nullable().optional(),
  medicareExpiry: z.string().nullable().optional(),
  ihiNumber: z.string().max(512).nullable().optional(),
  dvaNumber: z.string().max(512).nullable().optional(),
  dvaCardType: z.string().max(20).nullable().optional(),
  indigenousStatus: z.string().max(50).nullable().optional(),
  atsiStatus: z.string().max(50).nullable().optional(),
  interpreterRequired: z.boolean(),
  interpreterLanguage: z.string().max(100).nullable().optional(),
  emergencyContactName: z.string().max(200).nullable().optional(),
  emergencyContactPhone: z.string().max(30).nullable().optional(),
  emergencyContactRelationship: z.string().max(100).nullable().optional(),
  gpName: z.string().max(200).nullable().optional(),
  gpPractice: z.string().max(200).nullable().optional(),
  gpPhone: z.string().max(30).nullable().optional(),
  gpFax: z.string().max(30).nullable().optional(),
  gpEmail: z.string().max(255).nullable().optional(),
  gpProviderNumber: z.string().max(30).nullable().optional(),
  gpAddressStreet: z.string().max(255).nullable().optional(),
  gpAddressSuburb: z.string().max(100).nullable().optional(),
  gpAddressState: z.string().max(20).nullable().optional(),
  gpAddressPostcode: z.string().max(10).nullable().optional(),
  nokName: z.string().max(200).nullable().optional(),
  nokRelationship: z.string().max(100).nullable().optional(),
  nokPhone: z.string().max(512).nullable().optional(),
  consentToTreatment: z.boolean().nullable().optional(),
  consentForResearch: z.boolean().nullable().optional(),
  consentToShareWithGp: z.boolean().nullable().optional(),
  consentToShareWithCarer: z.boolean().nullable().optional(),
  createdAt: z.string().datetime(),
  updatedAt: z.string().datetime(),
  deletedAt: z.string().datetime().nullable().optional(),
  vivaTriageNumber: z.string().max(30).nullable().optional(),
  healthFundName: z.string().max(100).nullable().optional(),
  healthFundNumber: z.string().max(50).nullable().optional(),
  medicareNumberLookup: z.string().nullable().optional(),
  ihiNumberLookup: z.string().nullable().optional(),
  dvaNumberLookup: z.string().nullable().optional(),
  smsConsent: z.boolean(),
  smsConsentUpdatedAt: z.string().datetime().nullable().optional(),
  smsConsentUpdatedBy: z.string().uuid().nullable().optional(),
  photoUrl: z.string().nullable().optional(),
  deceasedDate: z.string().nullable().optional(),
  purgedAt: z.string().datetime().nullable().optional(),
  lastContactAt: z.string().datetime().nullable().optional(),
  ihiRecordStatus: z.string().nullable().optional(),
  ihiNumberStatus: z.string().nullable().optional(),
  ihiVerifiedAt: z.string().datetime().nullable().optional(),
  searchTsv: z.unknown().nullable().optional(),
});

export type PatientsResponseScaffold = z.infer<typeof PatientsResponseScaffoldSchema>;
