// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ActiveSessionsRow {
  id: string;
  staff_id: string;
  clinic_id: string;
  refresh_token_jti: string;
  ip_address?: string | null;
  user_agent?: string | null;
  created_at: string;
  expires_at: string;
  revoked_at?: string | null;
}

export const ACTIVE_SESSIONS_COLUMNS = [
  'id',
  'staff_id',
  'clinic_id',
  'refresh_token_jti',
  'ip_address',
  'user_agent',
  'created_at',
  'expires_at',
  'revoked_at',
] as const;

export type ActiveSessionsColumn = typeof ACTIVE_SESSIONS_COLUMNS[number];
