// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AdmissionWaitlistRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  hotspot_id?: string | null;
  source: string;
  priority: string;
  status: string;
  reason?: string | null;
  clinical_notes?: string | null;
  preferred_ward?: string | null;
  target_admission_date?: string | null;
  flagged_by_staff_id?: string | null;
  removed_by_staff_id?: string | null;
  removed_at?: string | null;
  removal_reason?: string | null;
  created_at: string;
  updated_at: string;
}

export const ADMISSION_WAITLIST_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'hotspot_id',
  'source',
  'priority',
  'status',
  'reason',
  'clinical_notes',
  'preferred_ward',
  'target_admission_date',
  'flagged_by_staff_id',
  'removed_by_staff_id',
  'removed_at',
  'removal_reason',
  'created_at',
  'updated_at',
] as const;

export type AdmissionWaitlistColumn = typeof ADMISSION_WAITLIST_COLUMNS[number];
