// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AdminImpersonationSessionsRow {
  id: string;
  clinic_id: string;
  admin_id: string;
  impersonated_staff_id: string;
  reason: string;
  started_at: string;
  expires_at: string;
  ended_at?: string | null;
  created_at: string;
}

export const ADMIN_IMPERSONATION_SESSIONS_COLUMNS = [
  'id',
  'clinic_id',
  'admin_id',
  'impersonated_staff_id',
  'reason',
  'started_at',
  'expires_at',
  'ended_at',
  'created_at',
] as const;

export type AdminImpersonationSessionsColumn = typeof ADMIN_IMPERSONATION_SESSIONS_COLUMNS[number];
