// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AdvanceDirectivesRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  type: string;
  content?: unknown | null;
  status: string;
  valid_from?: string | null;
  valid_until?: string | null;
  created_at: string;
  updated_at?: string | null;
  lock_version: number;
}

export const ADVANCE_DIRECTIVES_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'type',
  'content',
  'status',
  'valid_from',
  'valid_until',
  'created_at',
  'updated_at',
  'lock_version',
] as const;

export type AdvanceDirectivesColumn = typeof ADVANCE_DIRECTIVES_COLUMNS[number];
