// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AiContextFilesRow {
  id: string;
  clinic_id: string;
  title: string;
  description?: string | null;
  category: string;
  content: string;
  content_format: string;
  is_active: boolean;
  include_in_rag: boolean;
  priority: number;
  token_estimate?: number | null;
  uploaded_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const AI_CONTEXT_FILES_COLUMNS = [
  'id',
  'clinic_id',
  'title',
  'description',
  'category',
  'content',
  'content_format',
  'is_active',
  'include_in_rag',
  'priority',
  'token_estimate',
  'uploaded_by_staff_id',
  'created_at',
  'updated_at',
] as const;

export type AiContextFilesColumn = typeof AI_CONTEXT_FILES_COLUMNS[number];
