// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AiJobRunsRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  patient_id?: string | null;
  consent_id?: string | null;
  action: string;
  status: string;
  progress_percent: number;
  stage?: string | null;
  status_message?: string | null;
  model?: string | null;
  input_summary?: string | null;
  queue_payload: unknown;
  result_text?: string | null;
  result_json: unknown;
  output_hash?: string | null;
  validation_valid?: boolean | null;
  error_code?: string | null;
  error_message?: string | null;
  validation_warnings: unknown;
  audio_storage_key?: string | null;
  audio_storage_backend?: string | null;
  audio_storage_bucket?: string | null;
  audio_mime_type?: string | null;
  audio_retention_policy?: string | null;
  audio_deleted_at?: string | null;
  duration_ms?: number | null;
  queued_at: string;
  started_at?: string | null;
  completed_at?: string | null;
  failed_at?: string | null;
  lock_version: number;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const AI_JOB_RUNS_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'patient_id',
  'consent_id',
  'action',
  'status',
  'progress_percent',
  'stage',
  'status_message',
  'model',
  'input_summary',
  'queue_payload',
  'result_text',
  'result_json',
  'output_hash',
  'validation_valid',
  'error_code',
  'error_message',
  'validation_warnings',
  'audio_storage_key',
  'audio_storage_backend',
  'audio_storage_bucket',
  'audio_mime_type',
  'audio_retention_policy',
  'audio_deleted_at',
  'duration_ms',
  'queued_at',
  'started_at',
  'completed_at',
  'failed_at',
  'lock_version',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type AiJobRunsColumn = typeof AI_JOB_RUNS_COLUMNS[number];
