// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AiModelApprovalsRow {
  id: string;
  clinic_id?: string | null;
  model_name: string;
  model_digest: string;
  approved_by_staff_id?: string | null;
  approved_at: string;
  notes?: string | null;
  created_at: string;
}

export const AI_MODEL_APPROVALS_COLUMNS = [
  'id',
  'clinic_id',
  'model_name',
  'model_digest',
  'approved_by_staff_id',
  'approved_at',
  'notes',
  'created_at',
] as const;

export type AiModelApprovalsColumn = typeof AI_MODEL_APPROVALS_COLUMNS[number];
