// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AiModelfilesRow {
  id: string;
  clinic_id: string;
  action_type: string;
  model_name: string;
  modelfile_content?: string | null;
  system_prompt?: string | null;
  temperature: string;
  max_tokens: number;
  few_shot_examples?: string | null;
  rag_instructions?: string | null;
  is_active: boolean;
  updated_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const AI_MODELFILES_COLUMNS = [
  'id',
  'clinic_id',
  'action_type',
  'model_name',
  'modelfile_content',
  'system_prompt',
  'temperature',
  'max_tokens',
  'few_shot_examples',
  'rag_instructions',
  'is_active',
  'updated_by_staff_id',
  'created_at',
  'updated_at',
] as const;

export type AiModelfilesColumn = typeof AI_MODELFILES_COLUMNS[number];
