// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AiProvenanceRow {
  id: string;
  clinic_id: string;
  job_id?: string | null;
  patient_id?: string | null;
  action: string;
  output_hash: string;
  output_length: number;
  model_name: string;
  model_version: string;
  prompt_template_version: string;
  source_data_summary?: string | null;
  validated: boolean;
  validation_warnings: unknown;
  created_by_staff_id?: string | null;
  reviewed_by_staff_id?: string | null;
  reviewed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const AI_PROVENANCE_COLUMNS = [
  'id',
  'clinic_id',
  'job_id',
  'patient_id',
  'action',
  'output_hash',
  'output_length',
  'model_name',
  'model_version',
  'prompt_template_version',
  'source_data_summary',
  'validated',
  'validation_warnings',
  'created_by_staff_id',
  'reviewed_by_staff_id',
  'reviewed_at',
  'created_at',
  'updated_at',
] as const;

export type AiProvenanceColumn = typeof AI_PROVENANCE_COLUMNS[number];
