// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AiTrainingFeedbackRow {
  id: string;
  clinic_id: string;
  staff_id?: string | null;
  interaction_id?: string | null;
  feedback_type?: string | null;
  rating?: number | null;
  comments?: string | null;
  original_output?: string | null;
  corrected_output?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const AI_TRAINING_FEEDBACK_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'interaction_id',
  'feedback_type',
  'rating',
  'comments',
  'original_output',
  'corrected_output',
  'created_at',
  'updated_at',
] as const;

export type AiTrainingFeedbackColumn = typeof AI_TRAINING_FEEDBACK_COLUMNS[number];
