// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AimsAssessmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  lai_schedule_id?: string | null;
  assessed_by_staff_id: string;
  assessment_date: string;
  item_scores: unknown;
  total_score?: number | null;
  interpretation?: string | null;
  global_severity?: number | null;
  incapacitation?: number | null;
  patient_awareness?: number | null;
  current_dental_problems: boolean;
  dentures: boolean;
  clinical_notes?: string | null;
  is_baseline: boolean;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const AIMS_ASSESSMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'lai_schedule_id',
  'assessed_by_staff_id',
  'assessment_date',
  'item_scores',
  'total_score',
  'interpretation',
  'global_severity',
  'incapacitation',
  'patient_awareness',
  'current_dental_problems',
  'dentures',
  'clinical_notes',
  'is_baseline',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type AimsAssessmentsColumn = typeof AIMS_ASSESSMENTS_COLUMNS[number];
