// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AntenatalVisitsRow {
  id: string;
  clinic_id: string;
  pregnancy_id: string;
  patient_id: string;
  visit_number: number;
  visit_date: string;
  ga_weeks: number;
  ga_days: number;
  fundal_height_cm?: string | null;
  fetal_heart_rate_bpm?: number | null;
  bp_systolic?: number | null;
  bp_diastolic?: number | null;
  urine_protein?: string | null;
  urine_glucose?: string | null;
  oedema?: boolean | null;
  note?: string | null;
  seen_by?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const ANTENATAL_VISITS_COLUMNS = [
  'id',
  'clinic_id',
  'pregnancy_id',
  'patient_id',
  'visit_number',
  'visit_date',
  'ga_weeks',
  'ga_days',
  'fundal_height_cm',
  'fetal_heart_rate_bpm',
  'bp_systolic',
  'bp_diastolic',
  'urine_protein',
  'urine_glucose',
  'oedema',
  'note',
  'seen_by',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type AntenatalVisitsColumn = typeof ANTENATAL_VISITS_COLUMNS[number];
