// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AppointmentAttendeesRow {
  id: string;
  clinic_id: string;
  appointment_id: string;
  staff_id: string;
  role: string;
  attendance_status: string;
  invited_at: string;
  responded_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const APPOINTMENT_ATTENDEES_COLUMNS = [
  'id',
  'clinic_id',
  'appointment_id',
  'staff_id',
  'role',
  'attendance_status',
  'invited_at',
  'responded_at',
  'created_at',
  'updated_at',
] as const;

export type AppointmentAttendeesColumn = typeof APPOINTMENT_ATTENDEES_COLUMNS[number];
