// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AppointmentChecklistsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  appointment_id?: string | null;
  item: string;
  is_completed: boolean;
  sort_order: number;
  created_by?: string | null;
  created_at: string;
}

export const APPOINTMENT_CHECKLISTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'appointment_id',
  'item',
  'is_completed',
  'sort_order',
  'created_by',
  'created_at',
] as const;

export type AppointmentChecklistsColumn = typeof APPOINTMENT_CHECKLISTS_COLUMNS[number];
