// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AppointmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  clinician_id: string;
  staff_id?: string | null;
  episode_id?: string | null;
  start_time: string;
  end_time: string;
  appointment_start?: string | null;
  appointment_end?: string | null;
  duration_minutes?: number | null;
  status: string;
  type: string;
  appointment_type?: string | null;
  mode?: string | null;
  mbs_item?: string | null;
  patient_response?: string | null;
  location?: string | null;
  notes?: string | null;
  telehealth?: boolean | null;
  telehealth_url?: string | null;
  telehealth_link?: string | null;
  telehealth_provider?: string | null;
  telehealth_passcode?: string | null;
  cancellation_reason?: string | null;
  cancelled_by_id?: string | null;
  rescheduled_from_id?: string | null;
  reminder_scheduled: boolean;
  reminder_sent: boolean;
  reminder_sent_at?: string | null;
  outlook_event_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  recurrence_rule?: string | null;
  recurrence_end_date?: string | null;
  recurrence_parent_id?: string | null;
  specialty_code: string;
  check_in_at?: string | null;
  checked_in_by_id?: string | null;
  lock_version: number;
}

export const APPOINTMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'clinician_id',
  'staff_id',
  'episode_id',
  'start_time',
  'end_time',
  'appointment_start',
  'appointment_end',
  'duration_minutes',
  'status',
  'type',
  'appointment_type',
  'mode',
  'mbs_item',
  'patient_response',
  'location',
  'notes',
  'telehealth',
  'telehealth_url',
  'telehealth_link',
  'telehealth_provider',
  'telehealth_passcode',
  'cancellation_reason',
  'cancelled_by_id',
  'rescheduled_from_id',
  'reminder_scheduled',
  'reminder_sent',
  'reminder_sent_at',
  'outlook_event_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'recurrence_rule',
  'recurrence_end_date',
  'recurrence_parent_id',
  'specialty_code',
  'check_in_at',
  'checked_in_by_id',
  'lock_version',
] as const;

export type AppointmentsColumn = typeof APPOINTMENTS_COLUMNS[number];
