// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AssessmentResponsesRow {
  id: string;
  patient_id?: string | null;
  clinic_id: string;
  episode_id?: string | null;
  staff_id?: string | null;
  template_id?: string | null;
  assessment_type?: string | null;
  responses?: unknown | null;
  total_score?: string | null;
  severity?: string | null;
  collection_occasion?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const ASSESSMENT_RESPONSES_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'episode_id',
  'staff_id',
  'template_id',
  'assessment_type',
  'responses',
  'total_score',
  'severity',
  'collection_occasion',
  'created_at',
  'updated_at',
] as const;

export type AssessmentResponsesColumn = typeof ASSESSMENT_RESPONSES_COLUMNS[number];
