// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AuditLogRow {
  id: string;
  clinic_id?: string | null;
  staff_id?: string | null;
  user_id?: string | null;
  username?: string | null;
  action?: string | null;
  operation?: string | null;
  module?: string | null;
  entity_type?: string | null;
  entity_id?: string | null;
  table_name?: string | null;
  record_id?: string | null;
  details?: unknown | null;
  old_data?: unknown | null;
  new_data?: unknown | null;
  ip_address?: string | null;
  user_agent?: string | null;
  created_at: string;
  dedupe_key?: string | null;
  prev_hash: string;
  row_hash: string;
  chain_ordinal: number;
}

export const AUDIT_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'user_id',
  'username',
  'action',
  'operation',
  'module',
  'entity_type',
  'entity_id',
  'table_name',
  'record_id',
  'details',
  'old_data',
  'new_data',
  'ip_address',
  'user_agent',
  'created_at',
  'dedupe_key',
  'prev_hash',
  'row_hash',
  'chain_ordinal',
] as const;

export type AuditLogColumn = typeof AUDIT_LOG_COLUMNS[number];
