// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AuditRunsRow {
  id: string;
  clinic_id: string;
  template_id: string;
  team_id?: string | null;
  clinician_id?: string | null;
  sample_size: number;
  status: string;
  selected_note_ids: unknown;
  results?: unknown | null;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const AUDIT_RUNS_COLUMNS = [
  'id',
  'clinic_id',
  'template_id',
  'team_id',
  'clinician_id',
  'sample_size',
  'status',
  'selected_note_ids',
  'results',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type AuditRunsColumn = typeof AUDIT_RUNS_COLUMNS[number];
