// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AuditTemplatesRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  questions: unknown;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const AUDIT_TEMPLATES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'questions',
  'created_by_id',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type AuditTemplatesColumn = typeof AUDIT_TEMPLATES_COLUMNS[number];
