// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface AuditLogChainBaselinesRow {
  scope_key: string;
  baseline_marker: string;
  marker_signature: string;
  source_row_count: number;
  min_created_at?: string | null;
  max_created_at?: string | null;
  computed_at: string;
}

export const AUDIT_LOG_CHAIN_BASELINES_COLUMNS = [
  'scope_key',
  'baseline_marker',
  'marker_signature',
  'source_row_count',
  'min_created_at',
  'max_created_at',
  'computed_at',
] as const;

export type AuditLogChainBaselinesColumn = typeof AUDIT_LOG_CHAIN_BASELINES_COLUMNS[number];
