// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BackupHistoryRow {
  id: string;
  started_at: string;
  finished_at?: string | null;
  status: string;
  size_bytes?: number | null;
  location?: string | null;
  error_text?: string | null;
  trigger_kind: string;
  triggered_by_staff_id?: string | null;
}

export const BACKUP_HISTORY_COLUMNS = [
  'id',
  'started_at',
  'finished_at',
  'status',
  'size_bytes',
  'location',
  'error_text',
  'trigger_kind',
  'triggered_by_staff_id',
] as const;

export type BackupHistoryColumn = typeof BACKUP_HISTORY_COLUMNS[number];
