// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BackupConfigRow {
  id: string;
  schedule_enabled: boolean;
  frequency: string;
  time_of_day: string;
  retention_days: number;
  local_dir?: string | null;
  offsite_target?: string | null;
  last_run_at?: string | null;
  last_run_status?: string | null;
  created_at: string;
  updated_at: string;
}

export const BACKUP_CONFIG_COLUMNS = [
  'id',
  'schedule_enabled',
  'frequency',
  'time_of_day',
  'retention_days',
  'local_dir',
  'offsite_target',
  'last_run_at',
  'last_run_status',
  'created_at',
  'updated_at',
] as const;

export type BackupConfigColumn = typeof BACKUP_CONFIG_COLUMNS[number];
