// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BedMovementsRow {
  id: string;
  bed_id: string;
  patient_id: string;
  episode_id?: string | null;
  clinic_id: string;
  movement_type: string;
  movement_at: string;
  authorised_by_id?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const BED_MOVEMENTS_COLUMNS = [
  'id',
  'bed_id',
  'patient_id',
  'episode_id',
  'clinic_id',
  'movement_type',
  'movement_at',
  'authorised_by_id',
  'notes',
  'created_at',
  'updated_at',
] as const;

export type BedMovementsColumn = typeof BED_MOVEMENTS_COLUMNS[number];
