// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BedsRow {
  id: string;
  clinic_id: string;
  org_unit_id?: string | null;
  ward?: string | null;
  room?: string | null;
  bed_label: string;
  bed_type?: string | null;
  status: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const BEDS_COLUMNS = [
  'id',
  'clinic_id',
  'org_unit_id',
  'ward',
  'room',
  'bed_label',
  'bed_type',
  'status',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type BedsColumn = typeof BEDS_COLUMNS[number];
