// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BillingQueueRow {
  id: string;
  clinic_id: string;
  invoice_id: string;
  claim_type: string;
  status: string;
  submitted_at?: string | null;
  response_code?: string | null;
  response_message?: string | null;
  created_at: string;
}

export const BILLING_QUEUE_COLUMNS = [
  'id',
  'clinic_id',
  'invoice_id',
  'claim_type',
  'status',
  'submitted_at',
  'response_code',
  'response_message',
  'created_at',
] as const;

export type BillingQueueColumn = typeof BILLING_QUEUE_COLUMNS[number];
