// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BillingAccountsRow {
  id: string;
  clinic_id: string;
  patient_id?: string | null;
  account_type?: string | null;
  medicare_number?: string | null;
  dva_number?: string | null;
  private_health_fund?: string | null;
  member_number?: string | null;
  is_active?: boolean | null;
  created_at: string;
  billing_type?: string | null;
  health_fund_name?: string | null;
  health_fund_member_number?: string | null;
  ndis_number?: string | null;
  ndis_package_manager?: string | null;
  dva_card_type?: string | null;
  notes?: string | null;
  updated_at?: string | null;
}

export const BILLING_ACCOUNTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'account_type',
  'medicare_number',
  'dva_number',
  'private_health_fund',
  'member_number',
  'is_active',
  'created_at',
  'billing_type',
  'health_fund_name',
  'health_fund_member_number',
  'ndis_number',
  'ndis_package_manager',
  'dva_card_type',
  'notes',
  'updated_at',
] as const;

export type BillingAccountsColumn = typeof BILLING_ACCOUNTS_COLUMNS[number];
