// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface BreakGlassSessionsRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  reason: string;
  status: string;
  approver_id?: string | null;
  approved_at?: string | null;
  denied_reason?: string | null;
  token_hash?: string | null;
  issued_at?: string | null;
  expires_at?: string | null;
  revoked_at?: string | null;
  revoked_by?: string | null;
  ip_address?: unknown | null;
  user_agent?: string | null;
  actions_performed?: unknown | null;
  alerted_at?: string | null;
  created_at: string;
}

export const BREAK_GLASS_SESSIONS_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'reason',
  'status',
  'approver_id',
  'approved_at',
  'denied_reason',
  'token_hash',
  'issued_at',
  'expires_at',
  'revoked_at',
  'revoked_by',
  'ip_address',
  'user_agent',
  'actions_performed',
  'alerted_at',
  'created_at',
] as const;

export type BreakGlassSessionsColumn = typeof BREAK_GLASS_SESSIONS_COLUMNS[number];
