// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CancerTreatmentPlansRow {
  id: string;
  clinic_id: string;
  condition_id: string;
  regimen_name: string;
  intent: string;
  protocol_ref?: string | null;
  start_date: string;
  end_date?: string | null;
  status: string;
  notes?: string | null;
  created_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const CANCER_TREATMENT_PLANS_COLUMNS = [
  'id',
  'clinic_id',
  'condition_id',
  'regimen_name',
  'intent',
  'protocol_ref',
  'start_date',
  'end_date',
  'status',
  'notes',
  'created_by_staff_id',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type CancerTreatmentPlansColumn = typeof CANCER_TREATMENT_PLANS_COLUMNS[number];
