// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CapacityAssessmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  assessor_id: string;
  letter_id?: string | null;
  decision_context: string;
  understand_notes: string;
  retain_notes: string;
  weigh_notes: string;
  communicate_notes: string;
  conclusion: string;
  conclusion_reasoning: string;
  assessed_at: string;
  created_at: string;
  updated_at: string;
}

export const CAPACITY_ASSESSMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'assessor_id',
  'letter_id',
  'decision_context',
  'understand_notes',
  'retain_notes',
  'weigh_notes',
  'communicate_notes',
  'conclusion',
  'conclusion_reasoning',
  'assessed_at',
  'created_at',
  'updated_at',
] as const;

export type CapacityAssessmentsColumn = typeof CAPACITY_ASSESSMENTS_COLUMNS[number];
