// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CarePlansRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  title?: string | null;
  description?: string | null;
  status: string;
  transition_checklist?: unknown | null;
  transition_status?: string | null;
  transition_target_date?: string | null;
  recovery_star_scores?: unknown | null;
  recovery_star_updated_at?: string | null;
  recovery_star_updated_by?: string | null;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const CARE_PLANS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'title',
  'description',
  'status',
  'transition_checklist',
  'transition_status',
  'transition_target_date',
  'recovery_star_scores',
  'recovery_star_updated_at',
  'recovery_star_updated_by',
  'created_by_id',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type CarePlansColumn = typeof CARE_PLANS_COLUMNS[number];
