// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CarePlanGoalsRow {
  id: string;
  clinic_id: string;
  treatment_plan_id: string;
  goal_text: string;
  description?: string | null;
  goal_type: string;
  target_date?: string | null;
  status: string;
  sort_order: number;
  measurable?: string | null;
  patient_self_rated?: string | null;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const CARE_PLAN_GOALS_COLUMNS = [
  'id',
  'clinic_id',
  'treatment_plan_id',
  'goal_text',
  'description',
  'goal_type',
  'target_date',
  'status',
  'sort_order',
  'measurable',
  'patient_self_rated',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type CarePlanGoalsColumn = typeof CARE_PLAN_GOALS_COLUMNS[number];
