// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CarersRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  given_name: string;
  family_name?: string | null;
  relationship?: string | null;
  phone?: string | null;
  email?: string | null;
  is_primary: boolean;
  created_at: string;
  updated_at?: string | null;
}

export const CARERS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'given_name',
  'family_name',
  'relationship',
  'phone',
  'email',
  'is_primary',
  'created_at',
  'updated_at',
] as const;

export type CarersColumn = typeof CARERS_COLUMNS[number];
