// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CarePlanInterventionsRow {
  id: string;
  clinic_id: string;
  care_plan_goal_id: string;
  intervention_text: string;
  description?: string | null;
  frequency?: string | null;
  responsible_staff_id?: string | null;
  status: string;
  start_date?: string | null;
  end_date?: string | null;
  sort_order: number;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const CARE_PLAN_INTERVENTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'care_plan_goal_id',
  'intervention_text',
  'description',
  'frequency',
  'responsible_staff_id',
  'status',
  'start_date',
  'end_date',
  'sort_order',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type CarePlanInterventionsColumn = typeof CARE_PLAN_INTERVENTIONS_COLUMNS[number];
