// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ChecklistTemplatesRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  trigger_point: string;
  enforcement: string;
  items: unknown;
  is_active: boolean;
  sort_order: number;
  created_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const CHECKLIST_TEMPLATES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'trigger_point',
  'enforcement',
  'items',
  'is_active',
  'sort_order',
  'created_by_staff_id',
  'created_at',
  'updated_at',
] as const;

export type ChecklistTemplatesColumn = typeof CHECKLIST_TEMPLATES_COLUMNS[number];
