// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ChecklistInstancesRow {
  id: string;
  clinic_id: string;
  template_id: string;
  patient_id: string;
  episode_id?: string | null;
  completed_by_staff_id?: string | null;
  status: string;
  checked_items: unknown;
  total_items: number;
  completed_items: number;
  notes?: string | null;
  completed_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const CHECKLIST_INSTANCES_COLUMNS = [
  'id',
  'clinic_id',
  'template_id',
  'patient_id',
  'episode_id',
  'completed_by_staff_id',
  'status',
  'checked_items',
  'total_items',
  'completed_items',
  'notes',
  'completed_at',
  'created_at',
  'updated_at',
] as const;

export type ChecklistInstancesColumn = typeof CHECKLIST_INSTANCES_COLUMNS[number];
