// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ChemoCyclesRow {
  id: string;
  clinic_id: string;
  plan_id: string;
  cycle_number: number;
  planned_date: string;
  actual_date?: string | null;
  status: string;
  dose_modifications: unknown;
  toxicity_ctcae: unknown;
  notes?: string | null;
  administered_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const CHEMO_CYCLES_COLUMNS = [
  'id',
  'clinic_id',
  'plan_id',
  'cycle_number',
  'planned_date',
  'actual_date',
  'status',
  'dose_modifications',
  'toxicity_ctcae',
  'notes',
  'administered_by_staff_id',
  'created_at',
  'updated_at',
] as const;

export type ChemoCyclesColumn = typeof CHEMO_CYCLES_COLUMNS[number];
