// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalNotesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  author_id?: string | null;
  appointment_id?: string | null;
  title?: string | null;
  note_type: string;
  note_category?: string | null;
  source_type?: string | null;
  note_date_time?: string | null;
  note_date?: string | null;
  content?: string | null;
  content_html?: string | null;
  structured_fields?: unknown | null;
  status: string;
  is_draft?: boolean | null;
  is_signed?: boolean | null;
  template_id?: string | null;
  is_reportable_contact: boolean;
  contact_meta?: unknown | null;
  foi_content?: string | null;
  foi_exempt: boolean;
  did_not_attend: boolean;
  is_ai_draft: boolean;
  soap_subjective?: string | null;
  soap_objective?: string | null;
  soap_assessment?: string | null;
  soap_plan?: string | null;
  amended_from_id?: string | null;
  signed_at?: string | null;
  signed_by?: string | null;
  signed_by_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
  search_tsv?: unknown | null;
  reviewed_and_adopted_by_id?: string | null;
  reviewed_and_adopted_at?: string | null;
  consent_id?: string | null;
  signed_content_hash?: string | null;
  signed_content_hash_alg?: string | null;
}

export const CLINICAL_NOTES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'author_id',
  'appointment_id',
  'title',
  'note_type',
  'note_category',
  'source_type',
  'note_date_time',
  'note_date',
  'content',
  'content_html',
  'structured_fields',
  'status',
  'is_draft',
  'is_signed',
  'template_id',
  'is_reportable_contact',
  'contact_meta',
  'foi_content',
  'foi_exempt',
  'did_not_attend',
  'is_ai_draft',
  'soap_subjective',
  'soap_objective',
  'soap_assessment',
  'soap_plan',
  'amended_from_id',
  'signed_at',
  'signed_by',
  'signed_by_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
  'search_tsv',
  'reviewed_and_adopted_by_id',
  'reviewed_and_adopted_at',
  'consent_id',
  'signed_content_hash',
  'signed_content_hash_alg',
] as const;

export type ClinicalNotesColumn = typeof CLINICAL_NOTES_COLUMNS[number];
