// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicianFeeOverridesRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  item_number: string;
  provider_fee_cents: number;
  gap_cents: number;
  bulk_bill_eligible: boolean;
  notes?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const CLINICIAN_FEE_OVERRIDES_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'item_number',
  'provider_fee_cents',
  'gap_cents',
  'bulk_bill_eligible',
  'notes',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type ClinicianFeeOverridesColumn = typeof CLINICIAN_FEE_OVERRIDES_COLUMNS[number];
