// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalNoteEvidenceRow {
  id: string;
  note_id: string;
  chunk_id: string;
  clinic_id: string;
  quoted_excerpt?: string | null;
  section?: string | null;
  status: string;
  source: string;
  accepted_by_staff_id?: string | null;
  accepted_at?: string | null;
  created_at: string;
  lock_version: number;
}

export const CLINICAL_NOTE_EVIDENCE_COLUMNS = [
  'id',
  'note_id',
  'chunk_id',
  'clinic_id',
  'quoted_excerpt',
  'section',
  'status',
  'source',
  'accepted_by_staff_id',
  'accepted_at',
  'created_at',
  'lock_version',
] as const;

export type ClinicalNoteEvidenceColumn = typeof CLINICAL_NOTE_EVIDENCE_COLUMNS[number];
