// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicStepCareRulesRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  pathway_type: string;
  intervention_template_key: string;
  auto_assign_enabled: boolean;
  auto_escalate_enabled: boolean;
  escalation_priority: string;
  assignment_scope: string;
  is_active: boolean;
  expected_outcome_text?: string | null;
  conditions: unknown;
  created_by_staff_id?: string | null;
  lock_version: number;
  created_at: string;
  updated_at: string;
}

export const CLINIC_STEP_CARE_RULES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'pathway_type',
  'intervention_template_key',
  'auto_assign_enabled',
  'auto_escalate_enabled',
  'escalation_priority',
  'assignment_scope',
  'is_active',
  'expected_outcome_text',
  'conditions',
  'created_by_staff_id',
  'lock_version',
  'created_at',
  'updated_at',
] as const;

export type ClinicStepCareRulesColumn = typeof CLINIC_STEP_CARE_RULES_COLUMNS[number];
