// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicContactOptionsRow {
  id: string;
  clinic_id: string;
  locations?: unknown | null;
  programs?: unknown | null;
  service_recipient_types?: unknown | null;
  contact_media_types?: unknown | null;
  created_at: string;
  updated_at: string;
}

export const CLINIC_CONTACT_OPTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'locations',
  'programs',
  'service_recipient_types',
  'contact_media_types',
  'created_at',
  'updated_at',
] as const;

export type ClinicContactOptionsColumn = typeof CLINIC_CONTACT_OPTIONS_COLUMNS[number];
