// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicsRow {
  id: string;
  name: string;
  legal_name?: string | null;
  abn?: string | null;
  phone?: string | null;
  email?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  suburb?: string | null;
  state?: string | null;
  postcode?: string | null;
  country?: string | null;
  timezone?: string | null;
  time_zone?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  hpio?: string | null;
  npds_conformance_id?: string | null;
  erx_etp1_site_id?: string | null;
  session_idle_minutes?: number | null;
}

export const CLINICS_COLUMNS = [
  'id',
  'name',
  'legal_name',
  'abn',
  'phone',
  'email',
  'address_line1',
  'address_line2',
  'suburb',
  'state',
  'postcode',
  'country',
  'timezone',
  'time_zone',
  'is_active',
  'created_at',
  'updated_at',
  'deleted_at',
  'hpio',
  'npds_conformance_id',
  'erx_etp1_site_id',
  'session_idle_minutes',
] as const;

export type ClinicsColumn = typeof CLINICS_COLUMNS[number];
