// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalPoliciesRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  rule_type: string;
  parameters: unknown;
  llm_context?: string | null;
  is_active: boolean;
  generates_alert: boolean;
  available_to_llm: boolean;
  category?: string | null;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export const CLINICAL_POLICIES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'rule_type',
  'parameters',
  'llm_context',
  'is_active',
  'generates_alert',
  'available_to_llm',
  'category',
  'sort_order',
  'created_at',
  'updated_at',
] as const;

export type ClinicalPoliciesColumn = typeof CLINICAL_POLICIES_COLUMNS[number];
