// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicScribeVocabularyRow {
  id: string;
  clinic_id: string;
  category: string;
  term: string;
  pronunciation_hint?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const CLINIC_SCRIBE_VOCABULARY_COLUMNS = [
  'id',
  'clinic_id',
  'category',
  'term',
  'pronunciation_hint',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type ClinicScribeVocabularyColumn = typeof CLINIC_SCRIBE_VOCABULARY_COLUMNS[number];
