// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicSequencesRow {
  id: string;
  clinic_id: string;
  scope_key: string;
  next_value: number;
  created_at: string;
  updated_at: string;
}

export const CLINIC_SEQUENCES_COLUMNS = [
  'id',
  'clinic_id',
  'scope_key',
  'next_value',
  'created_at',
  'updated_at',
] as const;

export type ClinicSequencesColumn = typeof CLINIC_SEQUENCES_COLUMNS[number];
