// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalNoteCodesRow {
  id: string;
  note_id: string;
  clinic_id: string;
  system: string;
  code: string;
  display: string;
  confidence: string;
  status: string;
  source: string;
  source_excerpt?: string | null;
  accepted_by_staff_id?: string | null;
  accepted_at?: string | null;
  rejected_by_staff_id?: string | null;
  rejected_at?: string | null;
  reject_reason?: string | null;
  created_at: string;
  updated_at: string;
  lock_version: number;
}

export const CLINICAL_NOTE_CODES_COLUMNS = [
  'id',
  'note_id',
  'clinic_id',
  'system',
  'code',
  'display',
  'confidence',
  'status',
  'source',
  'source_excerpt',
  'accepted_by_staff_id',
  'accepted_at',
  'rejected_by_staff_id',
  'rejected_at',
  'reject_reason',
  'created_at',
  'updated_at',
  'lock_version',
] as const;

export type ClinicalNoteCodesColumn = typeof CLINICAL_NOTE_CODES_COLUMNS[number];
