// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicEnabledSpecialtiesRow {
  id: string;
  clinic_id: string;
  specialty_code: string;
  enabled_at: string;
  enabled_by?: string | null;
}

export const CLINIC_ENABLED_SPECIALTIES_COLUMNS = [
  'id',
  'clinic_id',
  'specialty_code',
  'enabled_at',
  'enabled_by',
] as const;

export type ClinicEnabledSpecialtiesColumn = typeof CLINIC_ENABLED_SPECIALTIES_COLUMNS[number];
