// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicSettingsRow {
  clinic_id: string;
  scribe_consent_mode: string;
  created_at: string;
  updated_at: string;
  ai_chat_classifier_mode: string;
  scribe_audio_retention: string;
  sharepoint_site_id?: string | null;
  letterhead_html?: string | null;
  letterhead_logo_url?: string | null;
  default_letter_language: string;
  default_guidelines?: unknown | null;
  training_opt_in: boolean;
  training_opt_in_changed_by?: string | null;
  training_opt_in_changed_at?: string | null;
  email_sender_mode: string;
  clinic_sender_email?: string | null;
  clinic_sender_name?: string | null;
  scribe_audio_retention_adr?: string | null;
  scribe_audio_retention_clinical_review?: string | null;
  scribe_audio_retention_approved_by_staff_id?: string | null;
  scribe_audio_retention_approved_at?: string | null;
  ai_llm_backend: string;
  scribe_runtime_mode: string;
  local_style_adapter_model_name?: string | null;
}

export const CLINIC_SETTINGS_COLUMNS = [
  'clinic_id',
  'scribe_consent_mode',
  'created_at',
  'updated_at',
  'ai_chat_classifier_mode',
  'scribe_audio_retention',
  'sharepoint_site_id',
  'letterhead_html',
  'letterhead_logo_url',
  'default_letter_language',
  'default_guidelines',
  'training_opt_in',
  'training_opt_in_changed_by',
  'training_opt_in_changed_at',
  'email_sender_mode',
  'clinic_sender_email',
  'clinic_sender_name',
  'scribe_audio_retention_adr',
  'scribe_audio_retention_clinical_review',
  'scribe_audio_retention_approved_by_staff_id',
  'scribe_audio_retention_approved_at',
  'ai_llm_backend',
  'scribe_runtime_mode',
  'local_style_adapter_model_name',
] as const;

export type ClinicSettingsColumn = typeof CLINIC_SETTINGS_COLUMNS[number];
