// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalFormulationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  author_id?: string | null;
  formulation_type: string;
  presenting_problem?: string | null;
  predisposing_factors?: string | null;
  precipitating_factors?: string | null;
  perpetuating_factors?: string | null;
  protective_factors?: string | null;
  summary?: string | null;
  diagnostic_formulation?: string | null;
  treatment_implications?: string | null;
  shared_with_patient: boolean;
  status: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  shared_with_clinicians: boolean;
  confidentiality_level: string;
}

export const CLINICAL_FORMULATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'author_id',
  'formulation_type',
  'presenting_problem',
  'predisposing_factors',
  'precipitating_factors',
  'perpetuating_factors',
  'protective_factors',
  'summary',
  'diagnostic_formulation',
  'treatment_implications',
  'shared_with_patient',
  'status',
  'created_at',
  'updated_at',
  'deleted_at',
  'shared_with_clinicians',
  'confidentiality_level',
] as const;

export type ClinicalFormulationsColumn = typeof CLINICAL_FORMULATIONS_COLUMNS[number];
