// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalReviewsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  reviewed_by_id?: string | null;
  review_type?: string | null;
  review_date?: string | null;
  summary?: string | null;
  recommendations?: string | null;
  status?: string | null;
  created_at: string;
  updated_at: string;
}

export const CLINICAL_REVIEWS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'reviewed_by_id',
  'review_type',
  'review_date',
  'summary',
  'recommendations',
  'status',
  'created_at',
  'updated_at',
] as const;

export type ClinicalReviewsColumn = typeof CLINICAL_REVIEWS_COLUMNS[number];
