// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicChoiceArchitectureDefaultsRow {
  id: string;
  clinic_id: string;
  next_review_due_days_default: number;
  safety_plan_refresh_days_default: number;
  medication_reminder_window_minutes: number;
  created_at: string;
  updated_at: string;
}

export const CLINIC_CHOICE_ARCHITECTURE_DEFAULTS_COLUMNS = [
  'id',
  'clinic_id',
  'next_review_due_days_default',
  'safety_plan_refresh_days_default',
  'medication_reminder_window_minutes',
  'created_at',
  'updated_at',
] as const;

export type ClinicChoiceArchitectureDefaultsColumn = typeof CLINIC_CHOICE_ARCHITECTURE_DEFAULTS_COLUMNS[number];
