// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalNoteVersionsRow {
  id: string;
  note_id: string;
  clinic_id: string;
  version_number: number;
  snapshot: unknown;
  edited_by_staff_id: string;
  edited_at: string;
  edit_reason?: string | null;
  status_at_snapshot?: string | null;
}

export const CLINICAL_NOTE_VERSIONS_COLUMNS = [
  'id',
  'note_id',
  'clinic_id',
  'version_number',
  'snapshot',
  'edited_by_staff_id',
  'edited_at',
  'edit_reason',
  'status_at_snapshot',
] as const;

export type ClinicalNoteVersionsColumn = typeof CLINICAL_NOTE_VERSIONS_COLUMNS[number];
