// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicThresholdsRow {
  id: string;
  clinic_id?: string | null;
  threshold_key?: string | null;
  threshold_value?: string | null;
  unit?: string | null;
  created_at: string;
  updated_at: string;
}

export const CLINIC_THRESHOLDS_COLUMNS = [
  'id',
  'clinic_id',
  'threshold_key',
  'threshold_value',
  'unit',
  'created_at',
  'updated_at',
] as const;

export type ClinicThresholdsColumn = typeof CLINIC_THRESHOLDS_COLUMNS[number];
