// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicMicroLearningRulesRow {
  id: string;
  clinic_id: string;
  name: string;
  tracking_type: string;
  delta_threshold: string;
  window_days: number;
  card_id: string;
  cooldown_days: number;
  is_active: boolean;
  lock_version: number;
  created_at: string;
  updated_at: string;
}

export const CLINIC_MICRO_LEARNING_RULES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'tracking_type',
  'delta_threshold',
  'window_days',
  'card_id',
  'cooldown_days',
  'is_active',
  'lock_version',
  'created_at',
  'updated_at',
] as const;

export type ClinicMicroLearningRulesColumn = typeof CLINIC_MICRO_LEARNING_RULES_COLUMNS[number];
