// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicianAvailabilityBlocksRow {
  id: string;
  clinic_id: string;
  clinician_id: string;
  colour: string;
  recurrence: string;
  day_of_week?: unknown | null;
  specific_date?: string | null;
  start_time: unknown;
  end_time: unknown;
  effective_from: string;
  effective_until?: string | null;
  label?: string | null;
  notes?: string | null;
  created_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const CLINICIAN_AVAILABILITY_BLOCKS_COLUMNS = [
  'id',
  'clinic_id',
  'clinician_id',
  'colour',
  'recurrence',
  'day_of_week',
  'specific_date',
  'start_time',
  'end_time',
  'effective_from',
  'effective_until',
  'label',
  'notes',
  'created_by_staff_id',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ClinicianAvailabilityBlocksColumn = typeof CLINICIAN_AVAILABILITY_BLOCKS_COLUMNS[number];
