// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicalTemplatesRow {
  id: string;
  clinic_id: string;
  category_id?: string | null;
  name: string;
  type: string;
  description?: string | null;
  content: unknown;
  is_active: boolean;
  is_system: boolean;
  sort_order: number;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const CLINICAL_TEMPLATES_COLUMNS = [
  'id',
  'clinic_id',
  'category_id',
  'name',
  'type',
  'description',
  'content',
  'is_active',
  'is_system',
  'sort_order',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type ClinicalTemplatesColumn = typeof CLINICAL_TEMPLATES_COLUMNS[number];
