// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClinicModulesRow {
  id?: string | null;
  clinic_id: string;
  module_key: string;
  is_enabled: boolean;
  updated_at: string;
}

export const CLINIC_MODULES_COLUMNS = [
  'id',
  'clinic_id',
  'module_key',
  'is_enabled',
  'updated_at',
] as const;

export type ClinicModulesColumn = typeof CLINIC_MODULES_COLUMNS[number];
