// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClozapineMonitoringChecksRow {
  id: string;
  clinic_id: string;
  registration_id: string;
  investigation: string;
  check_point: string;
  check_date?: string | null;
  result_status?: string | null;
  result_value?: string | null;
  notes?: string | null;
  recorded_by_staff_id?: string | null;
  created_at: string;
}

export const CLOZAPINE_MONITORING_CHECKS_COLUMNS = [
  'id',
  'clinic_id',
  'registration_id',
  'investigation',
  'check_point',
  'check_date',
  'result_status',
  'result_value',
  'notes',
  'recorded_by_staff_id',
  'created_at',
] as const;

export type ClozapineMonitoringChecksColumn = typeof CLOZAPINE_MONITORING_CHECKS_COLUMNS[number];
