// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClozapineTitrationDaysRow {
  id: string;
  clinic_id: string;
  registration_id: string;
  day_number: number;
  titration_date: string;
  morning_dose_mg?: string | null;
  evening_dose_mg?: string | null;
  prescriber_initials?: string | null;
  prescribed_by_staff_id?: string | null;
  comments?: string | null;
  created_at: string;
  updated_at: string;
}

export const CLOZAPINE_TITRATION_DAYS_COLUMNS = [
  'id',
  'clinic_id',
  'registration_id',
  'day_number',
  'titration_date',
  'morning_dose_mg',
  'evening_dose_mg',
  'prescriber_initials',
  'prescribed_by_staff_id',
  'comments',
  'created_at',
  'updated_at',
] as const;

export type ClozapineTitrationDaysColumn = typeof CLOZAPINE_TITRATION_DAYS_COLUMNS[number];
