// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClozapineAdministrationsRow {
  id: string;
  clinic_id: string;
  registration_id: string;
  titration_day_id?: string | null;
  administration_date: string;
  time_slot: string;
  actual_time?: string | null;
  dose_mg: string;
  administered: boolean;
  non_admin_code?: string | null;
  administered_by_staff_id?: string | null;
  administrator_initials?: string | null;
  notes?: string | null;
  created_at: string;
}

export const CLOZAPINE_ADMINISTRATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'registration_id',
  'titration_day_id',
  'administration_date',
  'time_slot',
  'actual_time',
  'dose_mg',
  'administered',
  'non_admin_code',
  'administered_by_staff_id',
  'administrator_initials',
  'notes',
  'created_at',
] as const;

export type ClozapineAdministrationsColumn = typeof CLOZAPINE_ADMINISTRATIONS_COLUMNS[number];
