// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClozapineRegistrationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  drug_product_id?: string | null;
  prescriber_staff_id?: string | null;
  registration_date: string;
  dispenser_pharmacy?: string | null;
  current_dose_mg?: string | null;
  titration_phase: string;
  monitoring_week?: number | null;
  monitoring_frequency: string;
  last_anc_date?: string | null;
  last_anc_value?: string | null;
  anc_status: string;
  last_wbc_date?: string | null;
  last_wbc_value?: string | null;
  next_blood_due_date?: string | null;
  physical_health_check_due?: string | null;
  ceased_date?: string | null;
  ceased_reason?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const CLOZAPINE_REGISTRATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'drug_product_id',
  'prescriber_staff_id',
  'registration_date',
  'dispenser_pharmacy',
  'current_dose_mg',
  'titration_phase',
  'monitoring_week',
  'monitoring_frequency',
  'last_anc_date',
  'last_anc_value',
  'anc_status',
  'last_wbc_date',
  'last_wbc_value',
  'next_blood_due_date',
  'physical_health_check_due',
  'ceased_date',
  'ceased_reason',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ClozapineRegistrationsColumn = typeof CLOZAPINE_REGISTRATIONS_COLUMNS[number];
