// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ClozapineObservationsRow {
  id: string;
  clinic_id: string;
  registration_id: string;
  observation_date: string;
  observation_time?: string | null;
  temperature?: string | null;
  pulse?: number | null;
  bp_systolic_lying?: number | null;
  bp_diastolic_lying?: number | null;
  bp_systolic_standing?: number | null;
  bp_diastolic_standing?: number | null;
  respiration_rate?: number | null;
  smoking_status?: string | null;
  cigarettes_per_day?: number | null;
  outside_normal: boolean;
  notes?: string | null;
  recorded_by_staff_id?: string | null;
  created_at: string;
}

export const CLOZAPINE_OBSERVATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'registration_id',
  'observation_date',
  'observation_time',
  'temperature',
  'pulse',
  'bp_systolic_lying',
  'bp_diastolic_lying',
  'bp_systolic_standing',
  'bp_diastolic_standing',
  'respiration_rate',
  'smoking_status',
  'cigarettes_per_day',
  'outside_normal',
  'notes',
  'recorded_by_staff_id',
  'created_at',
] as const;

export type ClozapineObservationsColumn = typeof CLOZAPINE_OBSERVATIONS_COLUMNS[number];
