// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CommunityResourcesRow {
  id: string;
  clinic_id: string;
  name: string;
  category: string;
  description?: string | null;
  services?: string | null;
  phone?: string | null;
  email?: string | null;
  website?: string | null;
  address?: string | null;
  operating_hours?: string | null;
  referral_process?: string | null;
  eligibility?: string | null;
  contact_person?: string | null;
  notes?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const COMMUNITY_RESOURCES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'category',
  'description',
  'services',
  'phone',
  'email',
  'website',
  'address',
  'operating_hours',
  'referral_process',
  'eligibility',
  'contact_person',
  'notes',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type CommunityResourcesColumn = typeof COMMUNITY_RESOURCES_COLUMNS[number];
