// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ConsentRecordsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  consent_type: string;
  status: string;
  granted_at?: string | null;
  withdrawn_at?: string | null;
  expires_at?: string | null;
  witness_name?: string | null;
  witness_role?: string | null;
  notes?: string | null;
  recorded_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const CONSENT_RECORDS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'consent_type',
  'status',
  'granted_at',
  'withdrawn_at',
  'expires_at',
  'witness_name',
  'witness_role',
  'notes',
  'recorded_by_id',
  'created_at',
  'updated_at',
] as const;

export type ConsentRecordsColumn = typeof CONSENT_RECORDS_COLUMNS[number];
