// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ConsultationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  clinician_id: string;
  encounter_date: string;
  encounter_type: string;
  duration_minutes?: number | null;
  presenting_complaints?: string | null;
  mse?: unknown | null;
  plan_text?: string | null;
  note_id?: string | null;
  status: string;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const CONSULTATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'clinician_id',
  'encounter_date',
  'encounter_type',
  'duration_minutes',
  'presenting_complaints',
  'mse',
  'plan_text',
  'note_id',
  'status',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ConsultationsColumn = typeof CONSULTATIONS_COLUMNS[number];
