// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ContactRecordsRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  episode_id?: string | null;
  staff_id?: string | null;
  contact_type: string;
  contact_date: string;
  contact_time?: unknown | null;
  duration_min?: number | null;
  location?: string | null;
  contact_medium?: string | null;
  program?: string | null;
  service_recipients?: string | null;
  is_reportable: boolean;
  team?: string | null;
  num_providing?: number | null;
  num_receiving?: number | null;
  content?: string | null;
  template_id?: string | null;
  status: string;
  created_at: string;
  updated_at?: string | null;
}

export const CONTACT_RECORDS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'episode_id',
  'staff_id',
  'contact_type',
  'contact_date',
  'contact_time',
  'duration_min',
  'location',
  'contact_medium',
  'program',
  'service_recipients',
  'is_reportable',
  'team',
  'num_providing',
  'num_receiving',
  'content',
  'template_id',
  'status',
  'created_at',
  'updated_at',
] as const;

export type ContactRecordsColumn = typeof CONTACT_RECORDS_COLUMNS[number];
