// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface CorrespondenceLettersRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  episode_id?: string | null;
  author_id?: string | null;
  recipient_name?: string | null;
  recipient_address?: string | null;
  recipient_email?: string | null;
  recipient_fax?: string | null;
  recipient_provider_id?: string | null;
  letter_type: string;
  subject?: string | null;
  content?: string | null;
  body?: string | null;
  status: string;
  clinical_note_id?: string | null;
  template_id?: string | null;
  generated_by_id?: string | null;
  notes?: string | null;
  sent_via?: string | null;
  created_at: string;
  sent_at?: string | null;
  deleted_at?: string | null;
  signature_data?: string | null;
  signed_by_id?: string | null;
  signed_at?: string | null;
  search_tsv?: unknown | null;
}

export const CORRESPONDENCE_LETTERS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'episode_id',
  'author_id',
  'recipient_name',
  'recipient_address',
  'recipient_email',
  'recipient_fax',
  'recipient_provider_id',
  'letter_type',
  'subject',
  'content',
  'body',
  'status',
  'clinical_note_id',
  'template_id',
  'generated_by_id',
  'notes',
  'sent_via',
  'created_at',
  'sent_at',
  'deleted_at',
  'signature_data',
  'signed_by_id',
  'signed_at',
  'search_tsv',
] as const;

export type CorrespondenceLettersColumn = typeof CORRESPONDENCE_LETTERS_COLUMNS[number];
