// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface DataRetentionPoliciesRow {
  id: string;
  clinic_id: string;
  data_category: string;
  retention_years: number;
  legal_basis?: string | null;
  disposal_method?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const DATA_RETENTION_POLICIES_COLUMNS = [
  'id',
  'clinic_id',
  'data_category',
  'retention_years',
  'legal_basis',
  'disposal_method',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type DataRetentionPoliciesColumn = typeof DATA_RETENTION_POLICIES_COLUMNS[number];
