// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface DataSharingAgreementsRow {
  id: string;
  clinic_id: string;
  partner_name: string;
  partner_type?: string | null;
  purpose?: string | null;
  data_categories?: unknown | null;
  start_date?: string | null;
  end_date?: string | null;
  conditions?: string | null;
  status: string;
  approved_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const DATA_SHARING_AGREEMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'partner_name',
  'partner_type',
  'purpose',
  'data_categories',
  'start_date',
  'end_date',
  'conditions',
  'status',
  'approved_by_id',
  'created_at',
  'updated_at',
] as const;

export type DataSharingAgreementsColumn = typeof DATA_SHARING_AGREEMENTS_COLUMNS[number];
