// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface DataBreachLogRow {
  id: string;
  clinic_id: string;
  breach_type?: string | null;
  severity: string;
  description: string;
  affected_records: number;
  affected_patients: number;
  containment_actions?: string | null;
  reported_by_id?: string | null;
  detected_at: string;
  reported_at?: string | null;
  status: string;
  resolution_notes?: string | null;
  is_notifiable?: boolean | null;
  notification_deadline?: string | null;
  oaic_form_data?: unknown | null;
  created_at: string;
  updated_at: string;
}

export const DATA_BREACH_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'breach_type',
  'severity',
  'description',
  'affected_records',
  'affected_patients',
  'containment_actions',
  'reported_by_id',
  'detected_at',
  'reported_at',
  'status',
  'resolution_notes',
  'is_notifiable',
  'notification_deadline',
  'oaic_form_data',
  'created_at',
  'updated_at',
] as const;

export type DataBreachLogColumn = typeof DATA_BREACH_LOG_COLUMNS[number];
