// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface DevelopmentalMilestonesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  domain: string;
  milestone: string;
  expected_age_months?: unknown | null;
  achieved_at_months?: unknown | null;
  status: string;
  note?: string | null;
  assessed_at: string;
  assessed_by?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const DEVELOPMENTAL_MILESTONES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'domain',
  'milestone',
  'expected_age_months',
  'achieved_at_months',
  'status',
  'note',
  'assessed_at',
  'assessed_by',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type DevelopmentalMilestonesColumn = typeof DEVELOPMENTAL_MILESTONES_COLUMNS[number];
