// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface DiagnosesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  created_by_id: string;
  icd_code: string;
  description: string;
  diagnosed_date: string;
  status: string;
  is_primary: boolean;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const DIAGNOSES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'created_by_id',
  'icd_code',
  'description',
  'diagnosed_date',
  'status',
  'is_primary',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type DiagnosesColumn = typeof DIAGNOSES_COLUMNS[number];
