// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface DrugProductsRow {
  id: string;
  clinic_id: string;
  generic_name: string;
  brand_name?: string | null;
  form?: string | null;
  strength?: string | null;
  unit?: string | null;
  route: string;
  schedule?: string | null;
  pbs_code?: string | null;
  pbs_listed: boolean;
  is_authority_required: boolean;
  is_controlled: boolean;
  atc_code?: string | null;
  drug_class?: string | null;
  is_lai: boolean;
  is_clozapine: boolean;
  contraindications?: string | null;
  common_interactions: unknown;
  monitoring_requirements?: string | null;
  dose_range?: string | null;
  data_source: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const DRUG_PRODUCTS_COLUMNS = [
  'id',
  'clinic_id',
  'generic_name',
  'brand_name',
  'form',
  'strength',
  'unit',
  'route',
  'schedule',
  'pbs_code',
  'pbs_listed',
  'is_authority_required',
  'is_controlled',
  'atc_code',
  'drug_class',
  'is_lai',
  'is_clozapine',
  'contraindications',
  'common_interactions',
  'monitoring_requirements',
  'dose_range',
  'data_source',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type DrugProductsColumn = typeof DRUG_PRODUCTS_COLUMNS[number];
