// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EcogPerformanceStatusRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  score: unknown;
  assessed_at: string;
  assessed_by_staff_id?: string | null;
  notes?: string | null;
  created_at: string;
}

export const ECOG_PERFORMANCE_STATUS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'score',
  'assessed_at',
  'assessed_by_staff_id',
  'notes',
  'created_at',
] as const;

export type EcogPerformanceStatusColumn = typeof ECOG_PERFORMANCE_STATUS_COLUMNS[number];
