// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EctCoursesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  treating_psychiatrist_id: string;
  anaesthetist_id?: string | null;
  consent_obtained: boolean;
  consent_date?: string | null;
  consent_recorded_by?: string | null;
  total_planned_sessions: number;
  indication: string;
  status: string;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const ECT_COURSES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'treating_psychiatrist_id',
  'anaesthetist_id',
  'consent_obtained',
  'consent_date',
  'consent_recorded_by',
  'total_planned_sessions',
  'indication',
  'status',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type EctCoursesColumn = typeof ECT_COURSES_COLUMNS[number];
