// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EctSessionsRow {
  id: string;
  course_id: string;
  clinic_id: string;
  session_number: number;
  session_date: string;
  stimulus_dose_mc?: string | null;
  seizure_duration_sec?: number | null;
  electrode_placement: string;
  anaesthetic_agent?: string | null;
  muscle_relaxant?: string | null;
  pre_treatment_bp?: string | null;
  post_treatment_bp?: string | null;
  mmse_score?: number | null;
  adverse_events?: string | null;
  clinician_notes?: string | null;
  administered_by: string;
  created_at: string;
  updated_at: string;
}

export const ECT_SESSIONS_COLUMNS = [
  'id',
  'course_id',
  'clinic_id',
  'session_number',
  'session_date',
  'stimulus_dose_mc',
  'seizure_duration_sec',
  'electrode_placement',
  'anaesthetic_agent',
  'muscle_relaxant',
  'pre_treatment_bp',
  'post_treatment_bp',
  'mmse_score',
  'adverse_events',
  'clinician_notes',
  'administered_by',
  'created_at',
  'updated_at',
] as const;

export type EctSessionsColumn = typeof ECT_SESSIONS_COLUMNS[number];
