// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EngagementScoresRow {
  id: string;
  clinic_id: string;
  encounter_id: string;
  patient_id: string;
  rapport: number;
  engagement: number;
  compliance: number;
  insight: number;
  affect: number;
  notes?: string | null;
  recorded_at: string;
  created_at: string;
  updated_at: string;
}

export const ENGAGEMENT_SCORES_COLUMNS = [
  'id',
  'clinic_id',
  'encounter_id',
  'patient_id',
  'rapport',
  'engagement',
  'compliance',
  'insight',
  'affect',
  'notes',
  'recorded_at',
  'created_at',
  'updated_at',
] as const;

export type EngagementScoresColumn = typeof ENGAGEMENT_SCORES_COLUMNS[number];
