// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EpisodesRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  title?: string | null;
  episode_number?: string | null;
  episode_type?: string | null;
  status: string;
  presenting_problem?: string | null;
  primary_diagnosis?: string | null;
  start_date: string;
  end_date?: string | null;
  closure_reason?: string | null;
  closure_summary?: string | null;
  team_id?: string | null;
  primary_clinician_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  discharge_signature_data?: string | null;
  discharge_signed_by_id?: string | null;
  discharge_signed_at?: string | null;
  key_worker_id?: string | null;
  specialty_code: string;
  discharge_summary_content?: string | null;
  discharge_vetting_status?: string | null;
  discharge_vetted_by_id?: string | null;
  discharge_vetted_at?: string | null;
  discharge_signature?: string | null;
  closure_vetting_status?: string | null;
  closure_vetted_by_id?: string | null;
  closure_vetted_at?: string | null;
  closure_signature?: string | null;
  lock_version: number;
}

export const EPISODES_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'title',
  'episode_number',
  'episode_type',
  'status',
  'presenting_problem',
  'primary_diagnosis',
  'start_date',
  'end_date',
  'closure_reason',
  'closure_summary',
  'team_id',
  'primary_clinician_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'discharge_signature_data',
  'discharge_signed_by_id',
  'discharge_signed_at',
  'key_worker_id',
  'specialty_code',
  'discharge_summary_content',
  'discharge_vetting_status',
  'discharge_vetted_by_id',
  'discharge_vetted_at',
  'discharge_signature',
  'closure_vetting_status',
  'closure_vetted_by_id',
  'closure_vetted_at',
  'closure_signature',
  'lock_version',
] as const;

export type EpisodesColumn = typeof EPISODES_COLUMNS[number];
