// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EreferralsRow {
  id: string;
  patient_id?: string | null;
  clinic_id: string;
  referrer_name?: string | null;
  referrer_org?: string | null;
  referrer_phone?: string | null;
  referrer_email?: string | null;
  priority: string;
  status: string;
  content?: unknown | null;
  reason?: string | null;
  clinical_summary?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const EREFERRALS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'referrer_name',
  'referrer_org',
  'referrer_phone',
  'referrer_email',
  'priority',
  'status',
  'content',
  'reason',
  'clinical_summary',
  'created_at',
  'updated_at',
] as const;

export type EreferralsColumn = typeof EREFERRALS_COLUMNS[number];
