// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ErxTokensRow {
  id: string;
  clinic_id: string;
  prescription_id: string;
  token_value: string;
  dsp_id?: string | null;
  npds_reference?: string | null;
  status: string;
  issued_at: string;
  expires_at?: string | null;
  dispensed_at?: string | null;
  dispensing_pharmacy?: string | null;
  raw_response?: unknown | null;
  created_at: string;
  updated_at: string;
}

export const ERX_TOKENS_COLUMNS = [
  'id',
  'clinic_id',
  'prescription_id',
  'token_value',
  'dsp_id',
  'npds_reference',
  'status',
  'issued_at',
  'expires_at',
  'dispensed_at',
  'dispensing_pharmacy',
  'raw_response',
  'created_at',
  'updated_at',
] as const;

export type ErxTokensColumn = typeof ERX_TOKENS_COLUMNS[number];
