// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EscalationsRow {
  id: string;
  clinic_id: string;
  patient_id?: string | null;
  episode_id?: string | null;
  raised_by_id?: string | null;
  assigned_to_id?: string | null;
  acknowledged_by_id?: string | null;
  resolved_by_id?: string | null;
  type?: string | null;
  severity?: string | null;
  title?: string | null;
  description?: string | null;
  status?: string | null;
  resolution?: string | null;
  acknowledged_at?: string | null;
  resolved_at?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
}

export const ESCALATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'raised_by_id',
  'assigned_to_id',
  'acknowledged_by_id',
  'resolved_by_id',
  'type',
  'severity',
  'title',
  'description',
  'status',
  'resolution',
  'acknowledged_at',
  'resolved_at',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
] as const;

export type EscalationsColumn = typeof ESCALATIONS_COLUMNS[number];
