// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EscalationEventsRow {
  id: string;
  escalation_id?: string | null;
  actor_id?: string | null;
  event_type?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const ESCALATION_EVENTS_COLUMNS = [
  'id',
  'escalation_id',
  'actor_id',
  'event_type',
  'notes',
  'created_at',
  'updated_at',
] as const;

export type EscalationEventsColumn = typeof ESCALATION_EVENTS_COLUMNS[number];
