// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface EvidenceDocumentsRow {
  id: string;
  source_id: string;
  title: string;
  publisher?: string | null;
  jurisdiction?: string | null;
  published_on?: string | null;
  url?: string | null;
  document_type: string;
  license?: string | null;
  ingested_at: string;
}

export const EVIDENCE_DOCUMENTS_COLUMNS = [
  'id',
  'source_id',
  'title',
  'publisher',
  'jurisdiction',
  'published_on',
  'url',
  'document_type',
  'license',
  'ingested_at',
] as const;

export type EvidenceDocumentsColumn = typeof EVIDENCE_DOCUMENTS_COLUMNS[number];
