// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ExternalCalendarSubscriptionsRow {
  id: string;
  clinic_id: string;
  owner_staff_id: string;
  provider: string;
  external_subscription_id: string;
  resource: string;
  notification_url: string;
  lifecycle_notification_url?: string | null;
  client_state: string;
  expiration_utc: string;
  status: string;
  last_notification_at?: string | null;
  last_renewed_at?: string | null;
  last_error?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const EXTERNAL_CALENDAR_SUBSCRIPTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'owner_staff_id',
  'provider',
  'external_subscription_id',
  'resource',
  'notification_url',
  'lifecycle_notification_url',
  'client_state',
  'expiration_utc',
  'status',
  'last_notification_at',
  'last_renewed_at',
  'last_error',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ExternalCalendarSubscriptionsColumn = typeof EXTERNAL_CALENDAR_SUBSCRIPTIONS_COLUMNS[number];
