// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface FeatureFlagDisableRequestsRow {
  id: string;
  clinic_id?: string | null;
  flag_name: string;
  action: string;
  requested_by_id: string;
  requested_at: string;
  approved_by_id?: string | null;
  approved_at?: string | null;
  status: string;
  reason?: string | null;
  rejection_reason?: string | null;
  created_at: string;
}

export const FEATURE_FLAG_DISABLE_REQUESTS_COLUMNS = [
  'id',
  'clinic_id',
  'flag_name',
  'action',
  'requested_by_id',
  'requested_at',
  'approved_by_id',
  'approved_at',
  'status',
  'reason',
  'rejection_reason',
  'created_at',
] as const;

export type FeatureFlagDisableRequestsColumn = typeof FEATURE_FLAG_DISABLE_REQUESTS_COLUMNS[number];
