// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface FeatureFlagsRow {
  id: string;
  clinic_id?: string | null;
  name: string;
  description?: string | null;
  enabled: boolean;
  rollout_percentage: number;
  created_at: string;
  updated_at: string;
}

export const FEATURE_FLAGS_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'enabled',
  'rollout_percentage',
  'created_at',
  'updated_at',
] as const;

export type FeatureFlagsColumn = typeof FEATURE_FLAGS_COLUMNS[number];
