// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface FeeSchedulesRow {
  id: string;
  clinic_id: string;
  item_number: string;
  description: string;
  schedule_fee_cents: number;
  category: string;
  modality?: string | null;
  min_duration_mins?: number | null;
  max_duration_mins?: number | null;
  is_initial: boolean;
  is_active: boolean;
  source: string;
  effective_from?: string | null;
  effective_to?: string | null;
  sort_order?: number | null;
  created_at: string;
  updated_at: string;
}

export const FEE_SCHEDULES_COLUMNS = [
  'id',
  'clinic_id',
  'item_number',
  'description',
  'schedule_fee_cents',
  'category',
  'modality',
  'min_duration_mins',
  'max_duration_mins',
  'is_initial',
  'is_active',
  'source',
  'effective_from',
  'effective_to',
  'sort_order',
  'created_at',
  'updated_at',
] as const;

export type FeeSchedulesColumn = typeof FEE_SCHEDULES_COLUMNS[number];
