// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface FhirBulkExportJobsRow {
  id: string;
  clinic_id: string;
  requested_by_staff_id: string;
  types: unknown;
  since?: string | null;
  request_url: string;
  group_id?: string | null;
  status: string;
  error_text?: string | null;
  output_files: unknown;
  total_resources?: number | null;
  exported_resources: number;
  started_at?: string | null;
  finished_at?: string | null;
  created_at: string;
}

export const FHIR_BULK_EXPORT_JOBS_COLUMNS = [
  'id',
  'clinic_id',
  'requested_by_staff_id',
  'types',
  'since',
  'request_url',
  'group_id',
  'status',
  'error_text',
  'output_files',
  'total_resources',
  'exported_resources',
  'started_at',
  'finished_at',
  'created_at',
] as const;

export type FhirBulkExportJobsColumn = typeof FHIR_BULK_EXPORT_JOBS_COLUMNS[number];
