// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface FhirSubscriptionsRow {
  id: string;
  clinic_id: string;
  status?: string | null;
  criteria: string;
  channel_type: string;
  channel_endpoint: string;
  channel_header?: unknown | null;
  channel_payload?: string | null;
  reason?: string | null;
  end_time?: string | null;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const FHIR_SUBSCRIPTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'status',
  'criteria',
  'channel_type',
  'channel_endpoint',
  'channel_header',
  'channel_payload',
  'reason',
  'end_time',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type FhirSubscriptionsColumn = typeof FHIR_SUBSCRIPTIONS_COLUMNS[number];
