// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ForensicRiskFormulationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  assessor_id: string;
  letter_id?: string | null;
  instrument: string;
  scores: unknown;
  historical_summary: string;
  clinical_summary: string;
  risk_management_summary: string;
  overall_risk: string;
  overall_reasoning: string;
  assessed_at: string;
  created_at: string;
  updated_at: string;
}

export const FORENSIC_RISK_FORMULATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'assessor_id',
  'letter_id',
  'instrument',
  'scores',
  'historical_summary',
  'clinical_summary',
  'risk_management_summary',
  'overall_risk',
  'overall_reasoning',
  'assessed_at',
  'created_at',
  'updated_at',
] as const;

export type ForensicRiskFormulationsColumn = typeof FORENSIC_RISK_FORMULATIONS_COLUMNS[number];
