// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface GlucoseReadingsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  value: string;
  unit: string;
  source: string;
  meal_context?: string | null;
  measured_at: string;
  recorded_by?: string | null;
  note?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const GLUCOSE_READINGS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'value',
  'unit',
  'source',
  'meal_context',
  'measured_at',
  'recorded_by',
  'note',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type GlucoseReadingsColumn = typeof GLUCOSE_READINGS_COLUMNS[number];
