// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface GroupSessionsRow {
  id: string;
  clinic_id: string;
  facilitator_id?: string | null;
  name: string;
  group_type?: string | null;
  program?: string | null;
  session_date: string;
  start_time?: unknown | null;
  end_time?: unknown | null;
  duration_min?: number | null;
  location?: string | null;
  notes?: string | null;
  status: string;
  created_at: string;
  updated_at: string;
}

export const GROUP_SESSIONS_COLUMNS = [
  'id',
  'clinic_id',
  'facilitator_id',
  'name',
  'group_type',
  'program',
  'session_date',
  'start_time',
  'end_time',
  'duration_min',
  'location',
  'notes',
  'status',
  'created_at',
  'updated_at',
] as const;

export type GroupSessionsColumn = typeof GROUP_SESSIONS_COLUMNS[number];
