// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface GroupSessionAttendeesRow {
  id: string;
  group_session_id: string;
  patient_id: string;
  attendance_status: string;
  notes?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const GROUP_SESSION_ATTENDEES_COLUMNS = [
  'id',
  'group_session_id',
  'patient_id',
  'attendance_status',
  'notes',
  'created_at',
  'updated_at',
] as const;

export type GroupSessionAttendeesColumn = typeof GROUP_SESSION_ATTENDEES_COLUMNS[number];
