// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface GrowthMeasurementsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  measurement_type: string;
  value: string;
  unit: string;
  age_at_measurement_days: number;
  percentile?: string | null;
  z_score?: string | null;
  reference_source?: string | null;
  measured_at: string;
  recorded_by?: string | null;
  note?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const GROWTH_MEASUREMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'measurement_type',
  'value',
  'unit',
  'age_at_measurement_days',
  'percentile',
  'z_score',
  'reference_source',
  'measured_at',
  'recorded_by',
  'note',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type GrowthMeasurementsColumn = typeof GROWTH_MEASUREMENTS_COLUMNS[number];
