// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface HiErrorLogRow {
  id: string;
  clinic_id?: string | null;
  patient_id?: string | null;
  operation: string;
  status_code?: number | null;
  error_code?: string | null;
  error_message: string;
  request_ref?: string | null;
  context?: unknown | null;
  created_by_staff_id?: string | null;
  created_at: string;
}

export const HI_ERROR_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'operation',
  'status_code',
  'error_code',
  'error_message',
  'request_ref',
  'context',
  'created_by_staff_id',
  'created_at',
] as const;

export type HiErrorLogColumn = typeof HI_ERROR_LOG_COLUMNS[number];
