// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface HotspotsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  hotspot_type?: string | null;
  reason?: string | null;
  severity?: string | null;
  is_active?: boolean | null;
  created_at: string;
  updated_at?: string | null;
}

export const HOTSPOTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'hotspot_type',
  'reason',
  'severity',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type HotspotsColumn = typeof HOTSPOTS_COLUMNS[number];
