// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ImmunizationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  cvx_code: string;
  vaccine_name: string;
  manufacturer?: string | null;
  series_name?: string | null;
  dose_number?: unknown | null;
  series_doses?: unknown | null;
  administered_date: string;
  lot_number?: string | null;
  expiration_date?: string | null;
  site?: string | null;
  route?: string | null;
  dose_quantity_ml?: string | null;
  status: string;
  not_done_reason?: string | null;
  note?: string | null;
  administered_by?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const IMMUNIZATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'cvx_code',
  'vaccine_name',
  'manufacturer',
  'series_name',
  'dose_number',
  'series_doses',
  'administered_date',
  'lot_number',
  'expiration_date',
  'site',
  'route',
  'dose_quantity_ml',
  'status',
  'not_done_reason',
  'note',
  'administered_by',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ImmunizationsColumn = typeof IMMUNIZATIONS_COLUMNS[number];
