// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ImportJobsRow {
  id: string;
  clinic_id: string;
  uploaded_by_id: string;
  kind: string;
  status: string;
  filename?: string | null;
  row_count: number;
  error_count: number;
  committed_count: number;
  report: unknown;
  uploaded_at: string;
  committed_at?: string | null;
  deleted_at?: string | null;
}

export const IMPORT_JOBS_COLUMNS = [
  'id',
  'clinic_id',
  'uploaded_by_id',
  'kind',
  'status',
  'filename',
  'row_count',
  'error_count',
  'committed_count',
  'report',
  'uploaded_at',
  'committed_at',
  'deleted_at',
] as const;

export type ImportJobsColumn = typeof IMPORT_JOBS_COLUMNS[number];
