// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface InsulinRegimensRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  basal_drug?: string | null;
  basal_dose_units?: string | null;
  basal_frequency?: string | null;
  bolus_drug?: string | null;
  bolus_doses?: unknown | null;
  correction_factor?: string | null;
  carb_ratio?: string | null;
  target_low?: string | null;
  target_high?: string | null;
  valid_from: string;
  valid_to?: string | null;
  note?: string | null;
  prescribed_by?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const INSULIN_REGIMENS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'basal_drug',
  'basal_dose_units',
  'basal_frequency',
  'bolus_drug',
  'bolus_doses',
  'correction_factor',
  'carb_ratio',
  'target_low',
  'target_high',
  'valid_from',
  'valid_to',
  'note',
  'prescribed_by',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type InsulinRegimensColumn = typeof INSULIN_REGIMENS_COLUMNS[number];
