// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface InvoicesRow {
  id: string;
  clinic_id: string;
  patient_id?: string | null;
  clinician_id?: string | null;
  invoice_number?: string | null;
  service_date?: string | null;
  mbs_item_code?: string | null;
  mbs_item_description?: string | null;
  fee_cents?: number | null;
  status?: string | null;
  payment_method?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  appointment_id?: string | null;
  billing_type?: string | null;
  subtotal_cents?: number | null;
  gst_cents?: number | null;
  total_cents?: number | null;
  paid_cents?: number | null;
  gap_cents?: number | null;
  schedule_fee_cents?: number | null;
  rebate_cents?: number | null;
  provider_fee_cents?: number | null;
  due_date?: string | null;
  approved_at?: string | null;
  approved_by_staff_id?: string | null;
  sent_at?: string | null;
  auto_generated: boolean;
  override_notes?: string | null;
  referral_valid?: boolean | null;
}

export const INVOICES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'clinician_id',
  'invoice_number',
  'service_date',
  'mbs_item_code',
  'mbs_item_description',
  'fee_cents',
  'status',
  'payment_method',
  'notes',
  'created_at',
  'updated_at',
  'appointment_id',
  'billing_type',
  'subtotal_cents',
  'gst_cents',
  'total_cents',
  'paid_cents',
  'gap_cents',
  'schedule_fee_cents',
  'rebate_cents',
  'provider_fee_cents',
  'due_date',
  'approved_at',
  'approved_by_staff_id',
  'sent_at',
  'auto_generated',
  'override_notes',
  'referral_valid',
] as const;

export type InvoicesColumn = typeof INVOICES_COLUMNS[number];
