// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface InvoiceLineItemsRow {
  id: string;
  invoice_id?: string | null;
  mbs_item_code?: string | null;
  description?: string | null;
  fee_cents?: number | null;
  quantity?: number | null;
  created_at: string;
  unit_price_cents?: number | null;
  discount_cents?: number | null;
  line_total_cents?: number | null;
  schedule_fee_cents?: number | null;
  updated_at?: string | null;
}

export const INVOICE_LINE_ITEMS_COLUMNS = [
  'id',
  'invoice_id',
  'mbs_item_code',
  'description',
  'fee_cents',
  'quantity',
  'created_at',
  'unit_price_cents',
  'discount_cents',
  'line_total_cents',
  'schedule_fee_cents',
  'updated_at',
] as const;

export type InvoiceLineItemsColumn = typeof INVOICE_LINE_ITEMS_COLUMNS[number];
