// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface KeyIssuesRow {
  id: string;
  clinic_id: string;
  encounter_id: string;
  patient_id: string;
  issue_text: string;
  category: string;
  priority: string;
  resolution?: string | null;
  resolved_at?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const KEY_ISSUES_COLUMNS = [
  'id',
  'clinic_id',
  'encounter_id',
  'patient_id',
  'issue_text',
  'category',
  'priority',
  'resolution',
  'resolved_at',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type KeyIssuesColumn = typeof KEY_ISSUES_COLUMNS[number];
