// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LaiValidationsRow {
  id: string;
  clinic_id: string;
  lai_schedule_id: string;
  patient_id: string;
  validated_by_staff_id: string;
  validation_date: string;
  valid_until: string;
  validation_type: string;
  outcome: string;
  clinical_rationale?: string | null;
  side_effects_reviewed?: string | null;
  consent_confirmed: boolean;
  blood_tests_reviewed: boolean;
  aims_reviewed: boolean;
  notes?: string | null;
  created_at: string;
}

export const LAI_VALIDATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'lai_schedule_id',
  'patient_id',
  'validated_by_staff_id',
  'validation_date',
  'valid_until',
  'validation_type',
  'outcome',
  'clinical_rationale',
  'side_effects_reviewed',
  'consent_confirmed',
  'blood_tests_reviewed',
  'aims_reviewed',
  'notes',
  'created_at',
] as const;

export type LaiValidationsColumn = typeof LAI_VALIDATIONS_COLUMNS[number];
