// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LaiGivenRow {
  id: string;
  clinic_id: string;
  lai_schedule_id: string;
  patient_id: string;
  administered_by_staff_id: string;
  schedule_id?: string | null;
  administered_by_id?: string | null;
  outcome: string;
  given_date: string;
  dose_given_mg?: string | null;
  dose_given?: string | null;
  injection_site?: string | null;
  batch_number?: string | null;
  expires_at?: string | null;
  refusal_reason?: string | null;
  deferred_to_date?: string | null;
  next_due_date?: string | null;
  aims_due?: boolean | null;
  aims_completed?: boolean | null;
  aims_response_id?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
}

export const LAI_GIVEN_COLUMNS = [
  'id',
  'clinic_id',
  'lai_schedule_id',
  'patient_id',
  'administered_by_staff_id',
  'schedule_id',
  'administered_by_id',
  'outcome',
  'given_date',
  'dose_given_mg',
  'dose_given',
  'injection_site',
  'batch_number',
  'expires_at',
  'refusal_reason',
  'deferred_to_date',
  'next_due_date',
  'aims_due',
  'aims_completed',
  'aims_response_id',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
] as const;

export type LaiGivenColumn = typeof LAI_GIVEN_COLUMNS[number];
