// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LaiSchedulesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  drug_product_id?: string | null;
  prescriber_staff_id: string;
  drug_name: string;
  dose_mg: string;
  frequency_days: number;
  injection_site: string;
  injection_technique: string;
  needle_gauge?: string | null;
  indication?: string | null;
  loading_dose_required: boolean;
  loading_doses_required: number;
  loading_doses_given: number;
  oral_overlap_required: boolean;
  oral_overlap_end_date?: string | null;
  start_date: string;
  first_due_date: string;
  next_due_date?: string | null;
  last_given_date?: string | null;
  end_date?: string | null;
  baseline_aims_score?: number | null;
  last_aims_date?: string | null;
  next_aims_due_date?: string | null;
  status: string;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const LAI_SCHEDULES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'drug_product_id',
  'prescriber_staff_id',
  'drug_name',
  'dose_mg',
  'frequency_days',
  'injection_site',
  'injection_technique',
  'needle_gauge',
  'indication',
  'loading_dose_required',
  'loading_doses_required',
  'loading_doses_given',
  'oral_overlap_required',
  'oral_overlap_end_date',
  'start_date',
  'first_due_date',
  'next_due_date',
  'last_given_date',
  'end_date',
  'baseline_aims_score',
  'last_aims_date',
  'next_aims_due_date',
  'status',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type LaiSchedulesColumn = typeof LAI_SCHEDULES_COLUMNS[number];
