// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LegalOrdersRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  order_type_id: string;
  order_number?: string | null;
  start_date: string;
  expires_at?: string | null;
  review_date?: string | null;
  status: string;
  issuing_authority?: string | null;
  conditions?: string | null;
  notes?: string | null;
  auto_flagged: boolean;
  created_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
}

export const LEGAL_ORDERS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'order_type_id',
  'order_number',
  'start_date',
  'expires_at',
  'review_date',
  'status',
  'issuing_authority',
  'conditions',
  'notes',
  'auto_flagged',
  'created_by_staff_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
] as const;

export type LegalOrdersColumn = typeof LEGAL_ORDERS_COLUMNS[number];
