// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LegalOrderTypesRow {
  id: string;
  code: string;
  name: string;
  jurisdiction: string;
  max_duration_days?: number | null;
  requires_tribunal: boolean;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const LEGAL_ORDER_TYPES_COLUMNS = [
  'id',
  'code',
  'name',
  'jurisdiction',
  'max_duration_days',
  'requires_tribunal',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type LegalOrderTypesColumn = typeof LEGAL_ORDER_TYPES_COLUMNS[number];
