// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterDeliveriesRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  channel: string;
  recipient_name: string;
  recipient_address?: string | null;
  recipient_email?: string | null;
  recipient_fax?: string | null;
  recipient_mhr_ihi?: string | null;
  status: string;
  receipt_id?: string | null;
  sent_by: string;
  attempted_at?: string | null;
  delivered_at?: string | null;
  error?: string | null;
  attempt_count: number;
  created_at: string;
  updated_at: string;
}

export const LETTER_DELIVERIES_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'channel',
  'recipient_name',
  'recipient_address',
  'recipient_email',
  'recipient_fax',
  'recipient_mhr_ihi',
  'status',
  'receipt_id',
  'sent_by',
  'attempted_at',
  'delivered_at',
  'error',
  'attempt_count',
  'created_at',
  'updated_at',
] as const;

export type LetterDeliveriesColumn = typeof LETTER_DELIVERIES_COLUMNS[number];
