// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterTranslationsRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  language_code: string;
  translated_text: string;
  translator_model: string;
  translated_by: string;
  translated_at: string;
  created_at: string;
}

export const LETTER_TRANSLATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'language_code',
  'translated_text',
  'translator_model',
  'translated_by',
  'translated_at',
  'created_at',
] as const;

export type LetterTranslationsColumn = typeof LETTER_TRANSLATIONS_COLUMNS[number];
