// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterExportsRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  format: string;
  content_ref: string;
  content_size_bytes?: number | null;
  generated_by: string;
  generated_at: string;
}

export const LETTER_EXPORTS_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'format',
  'content_ref',
  'content_size_bytes',
  'generated_by',
  'generated_at',
] as const;

export type LetterExportsColumn = typeof LETTER_EXPORTS_COLUMNS[number];
