// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterRevisionsRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  revision_number: number;
  previous_rendered_text?: string | null;
  reason_category: string;
  reason_detail: string;
  requested_by: string;
  created_at: string;
}

export const LETTER_REVISIONS_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'revision_number',
  'previous_rendered_text',
  'reason_category',
  'reason_detail',
  'requested_by',
  'created_at',
] as const;

export type LetterRevisionsColumn = typeof LETTER_REVISIONS_COLUMNS[number];
