// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterTemplatesRow {
  id: string;
  clinic_id?: string | null;
  code: string;
  name: string;
  category: string;
  description?: string | null;
  sections: unknown;
  system_prompt: string;
  default_recipients?: unknown | null;
  is_active: boolean;
  requires_second_review: boolean;
  created_at: string;
  updated_at: string;
}

export const LETTER_TEMPLATES_COLUMNS = [
  'id',
  'clinic_id',
  'code',
  'name',
  'category',
  'description',
  'sections',
  'system_prompt',
  'default_recipients',
  'is_active',
  'requires_second_review',
  'created_at',
  'updated_at',
] as const;

export type LetterTemplatesColumn = typeof LETTER_TEMPLATES_COLUMNS[number];
