// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterSectionsRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  section_key: string;
  section_order: number;
  label: string;
  content: string;
  regen_count: number;
  last_regen_at?: string | null;
  last_regen_by?: string | null;
  created_at: string;
  updated_at: string;
}

export const LETTER_SECTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'section_key',
  'section_order',
  'label',
  'content',
  'regen_count',
  'last_regen_at',
  'last_regen_by',
  'created_at',
  'updated_at',
] as const;

export type LetterSectionsColumn = typeof LETTER_SECTIONS_COLUMNS[number];
