// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LettersRow {
  id: string;
  clinic_id: string;
  template_id: string;
  patient_id: string;
  episode_id?: string | null;
  author_id: string;
  session_id?: string | null;
  status: string;
  subject: string;
  recipients: unknown;
  rendered_text?: string | null;
  approved_by?: string | null;
  approved_at?: string | null;
  sent_by?: string | null;
  sent_at?: string | null;
  revision: number;
  created_at: string;
  updated_at: string;
}

export const LETTERS_COLUMNS = [
  'id',
  'clinic_id',
  'template_id',
  'patient_id',
  'episode_id',
  'author_id',
  'session_id',
  'status',
  'subject',
  'recipients',
  'rendered_text',
  'approved_by',
  'approved_at',
  'sent_by',
  'sent_at',
  'revision',
  'created_at',
  'updated_at',
] as const;

export type LettersColumn = typeof LETTERS_COLUMNS[number];
