// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterTonePresetsRow {
  id: string;
  clinic_id?: string | null;
  tone_key: string;
  name: string;
  description: string;
  system_prompt_addendum: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const LETTER_TONE_PRESETS_COLUMNS = [
  'id',
  'clinic_id',
  'tone_key',
  'name',
  'description',
  'system_prompt_addendum',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type LetterTonePresetsColumn = typeof LETTER_TONE_PRESETS_COLUMNS[number];
