// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterAuditLogRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  event: string;
  actor_id: string;
  actor_role: string;
  section_key?: string | null;
  diff_summary?: unknown | null;
  ip_address?: string | null;
  created_at: string;
}

export const LETTER_AUDIT_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'event',
  'actor_id',
  'actor_role',
  'section_key',
  'diff_summary',
  'ip_address',
  'created_at',
] as const;

export type LetterAuditLogColumn = typeof LETTER_AUDIT_LOG_COLUMNS[number];
