// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LetterCitationsRow {
  id: string;
  clinic_id: string;
  letter_id: string;
  section_id?: string | null;
  source_kind: string;
  source_ref: string;
  source_offset?: number | null;
  snippet?: string | null;
  claim: string;
  confidence?: string | null;
  created_at: string;
}

export const LETTER_CITATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'letter_id',
  'section_id',
  'source_kind',
  'source_ref',
  'source_offset',
  'snippet',
  'claim',
  'confidence',
  'created_at',
] as const;

export type LetterCitationsColumn = typeof LETTER_CITATIONS_COLUMNS[number];
