// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LlmPromptsOutputsRow {
  id: string;
  llm_interaction_id: string;
  prompt_encrypted?: string | null;
  output_encrypted?: string | null;
  encryption_status: string;
  consent_id?: string | null;
  created_at: string;
}

export const LLM_PROMPTS_OUTPUTS_COLUMNS = [
  'id',
  'llm_interaction_id',
  'prompt_encrypted',
  'output_encrypted',
  'encryption_status',
  'consent_id',
  'created_at',
] as const;

export type LlmPromptsOutputsColumn = typeof LLM_PROMPTS_OUTPUTS_COLUMNS[number];
