// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface LlmInteractionsRow {
  id: string;
  clinic_id: string;
  user_id?: string | null;
  patient_id?: string | null;
  episode_id?: string | null;
  feature: string;
  model_name: string;
  model_provider?: string | null;
  prompt_tokens?: number | null;
  completion_tokens?: number | null;
  total_tokens?: number | null;
  latency_ms?: number | null;
  success: boolean;
  error_code?: string | null;
  input_ref?: string | null;
  output_ref?: string | null;
  metadata?: unknown | null;
  created_at: string;
  updated_at?: string | null;
  embedding?: unknown | null;
}

export const LLM_INTERACTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'user_id',
  'patient_id',
  'episode_id',
  'feature',
  'model_name',
  'model_provider',
  'prompt_tokens',
  'completion_tokens',
  'total_tokens',
  'latency_ms',
  'success',
  'error_code',
  'input_ref',
  'output_ref',
  'metadata',
  'created_at',
  'updated_at',
  'embedding',
] as const;

export type LlmInteractionsColumn = typeof LLM_INTERACTIONS_COLUMNS[number];
