// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MedicationReconciliationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  context: string;
  performed_at: string;
  performed_by?: string | null;
  snapshot: unknown;
  continued_count: number;
  ceased_count: number;
  modified_count: number;
  new_count: number;
  on_hold_count: number;
  summary_notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const MEDICATION_RECONCILIATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'context',
  'performed_at',
  'performed_by',
  'snapshot',
  'continued_count',
  'ceased_count',
  'modified_count',
  'new_count',
  'on_hold_count',
  'summary_notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type MedicationReconciliationsColumn = typeof MEDICATION_RECONCILIATIONS_COLUMNS[number];
