// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MedicationAdministrationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  patient_medication_id?: string | null;
  scheduled_time?: string | null;
  status: string;
  administered_time?: string | null;
  administered_by_staff_id?: string | null;
  dose_given?: string | null;
  route?: string | null;
  site?: string | null;
  notes?: string | null;
  reason_not_given?: string | null;
  witnessed_by_staff_id?: string | null;
  batch_number?: string | null;
  created_at: string;
  administration_context?: string | null;
  prn_reason?: string | null;
  lock_version: number;
}

export const MEDICATION_ADMINISTRATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'patient_medication_id',
  'scheduled_time',
  'status',
  'administered_time',
  'administered_by_staff_id',
  'dose_given',
  'route',
  'site',
  'notes',
  'reason_not_given',
  'witnessed_by_staff_id',
  'batch_number',
  'created_at',
  'administration_context',
  'prn_reason',
  'lock_version',
] as const;

export type MedicationAdministrationsColumn = typeof MEDICATION_ADMINISTRATIONS_COLUMNS[number];
