// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MessageThreadParticipantsRow {
  id: string;
  thread_id: string;
  user_id: string;
  last_read_at?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const MESSAGE_THREAD_PARTICIPANTS_COLUMNS = [
  'id',
  'thread_id',
  'user_id',
  'last_read_at',
  'created_at',
  'updated_at',
] as const;

export type MessageThreadParticipantsColumn = typeof MESSAGE_THREAD_PARTICIPANTS_COLUMNS[number];
