// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MessagesRow {
  id: string;
  thread_id?: string | null;
  sender_id?: string | null;
  clinic_id: string;
  content?: string | null;
  is_read?: boolean | null;
  created_at: string;
  updated_at: string;
}

export const MESSAGES_COLUMNS = [
  'id',
  'thread_id',
  'sender_id',
  'clinic_id',
  'content',
  'is_read',
  'created_at',
  'updated_at',
] as const;

export type MessagesColumn = typeof MESSAGES_COLUMNS[number];
