// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MessageThreadsRow {
  id: string;
  clinic_id: string;
  created_by_id: string;
  patient_id: string;
  subject: string;
  last_message_at?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const MESSAGE_THREADS_COLUMNS = [
  'id',
  'clinic_id',
  'created_by_id',
  'patient_id',
  'subject',
  'last_message_at',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type MessageThreadsColumn = typeof MESSAGE_THREADS_COLUMNS[number];
