// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MfaSecretsRow {
  id: string;
  staff_id: string;
  secret: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const MFA_SECRETS_COLUMNS = [
  'id',
  'staff_id',
  'secret',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type MfaSecretsColumn = typeof MFA_SECRETS_COLUMNS[number];
