// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MhaReviewsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  legal_order_id: string;
  order_id?: string | null;
  review_type: string;
  review_date: string;
  outcome?: string | null;
  notes?: string | null;
  clinical_notes?: string | null;
  next_review_date?: string | null;
  reviewed_by_staff_id?: string | null;
  reviewed_by_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
}

export const MHA_REVIEWS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'legal_order_id',
  'order_id',
  'review_type',
  'review_date',
  'outcome',
  'notes',
  'clinical_notes',
  'next_review_date',
  'reviewed_by_staff_id',
  'reviewed_by_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
] as const;

export type MhaReviewsColumn = typeof MHA_REVIEWS_COLUMNS[number];
