// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface MicroLearningCardsRow {
  id: string;
  card_key: string;
  title: string;
  body: string;
  estimated_minutes: number;
  tags: unknown;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const MICRO_LEARNING_CARDS_COLUMNS = [
  'id',
  'card_key',
  'title',
  'body',
  'estimated_minutes',
  'tags',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type MicroLearningCardsColumn = typeof MICRO_LEARNING_CARDS_COLUMNS[number];
