// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ModelDeploymentsRow {
  id: string;
  clinic_id: string;
  model_id: string;
  status: string;
  traffic_percentage: number;
  deployed_by: string;
  deployed_at: string;
  promoted_at?: string | null;
  rolled_back_at?: string | null;
  rollback_reason?: string | null;
  created_at: string;
  updated_at: string;
}

export const MODEL_DEPLOYMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'model_id',
  'status',
  'traffic_percentage',
  'deployed_by',
  'deployed_at',
  'promoted_at',
  'rolled_back_at',
  'rollback_reason',
  'created_at',
  'updated_at',
] as const;

export type ModelDeploymentsColumn = typeof MODEL_DEPLOYMENTS_COLUMNS[number];
