// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ModelRegistryRow {
  id: string;
  model_kind: string;
  name: string;
  version: string;
  provider: string;
  digest_sha256?: string | null;
  eval_scores?: unknown | null;
  red_team_pass: boolean;
  red_team_report_ref?: string | null;
  registered_by: string;
  registered_at: string;
  is_active: boolean;
}

export const MODEL_REGISTRY_COLUMNS = [
  'id',
  'model_kind',
  'name',
  'version',
  'provider',
  'digest_sha256',
  'eval_scores',
  'red_team_pass',
  'red_team_report_ref',
  'registered_by',
  'registered_at',
  'is_active',
] as const;

export type ModelRegistryColumn = typeof MODEL_REGISTRY_COLUMNS[number];
