// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ModelSurveillanceEventsRow {
  id: string;
  source_clinic_id: string;
  deployment_id?: string | null;
  model_id?: string | null;
  event_type: string;
  severity: string;
  payload?: unknown | null;
  created_at: string;
}

export const MODEL_SURVEILLANCE_EVENTS_COLUMNS = [
  'id',
  'source_clinic_id',
  'deployment_id',
  'model_id',
  'event_type',
  'severity',
  'payload',
  'created_at',
] as const;

export type ModelSurveillanceEventsColumn = typeof MODEL_SURVEILLANCE_EVENTS_COLUMNS[number];
