// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface NotificationsRow {
  id: string;
  clinic_id: string;
  recipient_staff_id?: string | null;
  type: string;
  title: string;
  body?: string | null;
  link?: string | null;
  priority?: string | null;
  is_read: boolean;
  read_at?: string | null;
  source_type?: string | null;
  source_id?: string | null;
  created_at: string;
  expires_at?: string | null;
  updated_at: string;
  severity?: string | null;
  category?: string | null;
  payload?: unknown | null;
  override_patient_sync: boolean;
}

export const NOTIFICATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'recipient_staff_id',
  'type',
  'title',
  'body',
  'link',
  'priority',
  'is_read',
  'read_at',
  'source_type',
  'source_id',
  'created_at',
  'expires_at',
  'updated_at',
  'severity',
  'category',
  'payload',
  'override_patient_sync',
] as const;

export type NotificationsColumn = typeof NOTIFICATIONS_COLUMNS[number];
