// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface NursingAssessmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  staff_id?: string | null;
  assessment_type: string;
  scores?: unknown | null;
  assessment_data?: unknown | null;
  total_score?: string | null;
  risk_level?: string | null;
  notes?: string | null;
  plan?: string | null;
  assessed_at: string;
  created_at: string;
  updated_at: string;
  next_review_at?: string | null;
}

export const NURSING_ASSESSMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'staff_id',
  'assessment_type',
  'scores',
  'assessment_data',
  'total_score',
  'risk_level',
  'notes',
  'plan',
  'assessed_at',
  'created_at',
  'updated_at',
  'next_review_at',
] as const;

export type NursingAssessmentsColumn = typeof NURSING_ASSESSMENTS_COLUMNS[number];
