// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OauthAuthorizationCodesRow {
  id: string;
  code_hash: string;
  client_id: string;
  clinic_id: string;
  user_id: string;
  patient_id?: string | null;
  redirect_uri: string;
  scopes: unknown;
  code_challenge?: string | null;
  code_challenge_method?: string | null;
  launch_token?: string | null;
  expires_at: string;
  created_at: string;
  redeemed_at?: string | null;
}

export const OAUTH_AUTHORIZATION_CODES_COLUMNS = [
  'id',
  'code_hash',
  'client_id',
  'clinic_id',
  'user_id',
  'patient_id',
  'redirect_uri',
  'scopes',
  'code_challenge',
  'code_challenge_method',
  'launch_token',
  'expires_at',
  'created_at',
  'redeemed_at',
] as const;

export type OauthAuthorizationCodesColumn = typeof OAUTH_AUTHORIZATION_CODES_COLUMNS[number];
