// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OauthRefreshTokensRow {
  id: string;
  token_hash: string;
  client_id: string;
  clinic_id: string;
  user_id: string;
  patient_id?: string | null;
  scopes: unknown;
  rotated_to_id?: string | null;
  expires_at: string;
  issued_at: string;
  revoked_at?: string | null;
}

export const OAUTH_REFRESH_TOKENS_COLUMNS = [
  'id',
  'token_hash',
  'client_id',
  'clinic_id',
  'user_id',
  'patient_id',
  'scopes',
  'rotated_to_id',
  'expires_at',
  'issued_at',
  'revoked_at',
] as const;

export type OauthRefreshTokensColumn = typeof OAUTH_REFRESH_TOKENS_COLUMNS[number];
