// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OauthAccessTokensRow {
  id: string;
  jti: string;
  client_id: string;
  clinic_id: string;
  user_id: string;
  patient_id?: string | null;
  scopes: unknown;
  expires_at: string;
  issued_at: string;
  revoked_at?: string | null;
  revoked_reason?: string | null;
}

export const OAUTH_ACCESS_TOKENS_COLUMNS = [
  'id',
  'jti',
  'client_id',
  'clinic_id',
  'user_id',
  'patient_id',
  'scopes',
  'expires_at',
  'issued_at',
  'revoked_at',
  'revoked_reason',
] as const;

export type OauthAccessTokensColumn = typeof OAUTH_ACCESS_TOKENS_COLUMNS[number];
