// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OpNotesRow {
  id: string;
  clinic_id: string;
  case_id: string;
  indication: string;
  findings: string;
  procedure_text: string;
  complications?: string | null;
  estimated_blood_loss_ml?: number | null;
  specimens: unknown;
  closed_by?: string | null;
  closed_at: string;
  created_at: string;
  deleted_at?: string | null;
}

export const OP_NOTES_COLUMNS = [
  'id',
  'clinic_id',
  'case_id',
  'indication',
  'findings',
  'procedure_text',
  'complications',
  'estimated_blood_loss_ml',
  'specimens',
  'closed_by',
  'closed_at',
  'created_at',
  'deleted_at',
] as const;

export type OpNotesColumn = typeof OP_NOTES_COLUMNS[number];
