// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OrgLevelLabelsRow {
  id: string;
  clinic_id: string;
  level: number;
  label: string;
  created_at: string;
  updated_at: string;
}

export const ORG_LEVEL_LABELS_COLUMNS = [
  'id',
  'clinic_id',
  'level',
  'label',
  'created_at',
  'updated_at',
] as const;

export type OrgLevelLabelsColumn = typeof ORG_LEVEL_LABELS_COLUMNS[number];
