// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OrgUnitsRow {
  id: string;
  clinic_id: string;
  name: string;
  level: string;
  parent_id?: string | null;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const ORG_UNITS_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'level',
  'parent_id',
  'sort_order',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type OrgUnitsColumn = typeof ORG_UNITS_COLUMNS[number];
