// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OrgUnitProgramsRow {
  id: string;
  clinic_id: string;
  org_unit_id: string;
  name: string;
  is_active: boolean;
  created_at: string;
  updated_at?: string | null;
}

export const ORG_UNIT_PROGRAMS_COLUMNS = [
  'id',
  'clinic_id',
  'org_unit_id',
  'name',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type OrgUnitProgramsColumn = typeof ORG_UNIT_PROGRAMS_COLUMNS[number];
