// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface OutcomeMeasuresRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  episode_id?: string | null;
  staff_id?: string | null;
  measure_type: string;
  collection_occasion?: string | null;
  total_score?: string | null;
  items?: unknown | null;
  notes?: string | null;
  created_at: string;
  updated_at?: string | null;
  status?: string | null;
  assigned_for_patient?: boolean | null;
  template_id?: string | null;
  template_name?: string | null;
  assigned_by?: string | null;
  completed_at?: string | null;
  lock_version: number;
}

export const OUTCOME_MEASURES_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'episode_id',
  'staff_id',
  'measure_type',
  'collection_occasion',
  'total_score',
  'items',
  'notes',
  'created_at',
  'updated_at',
  'status',
  'assigned_for_patient',
  'template_id',
  'template_name',
  'assigned_by',
  'completed_at',
  'lock_version',
] as const;

export type OutcomeMeasuresColumn = typeof OUTCOME_MEASURES_COLUMNS[number];
