// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PacuRecordsRow {
  id: string;
  clinic_id: string;
  case_id: string;
  vitals: unknown;
  aldrete_score: unknown;
  discharge_criteria_met: boolean;
  recovery_end_at?: string | null;
  note?: string | null;
  recorded_by?: string | null;
  created_at: string;
  deleted_at?: string | null;
}

export const PACU_RECORDS_COLUMNS = [
  'id',
  'clinic_id',
  'case_id',
  'vitals',
  'aldrete_score',
  'discharge_criteria_met',
  'recovery_end_at',
  'note',
  'recorded_by',
  'created_at',
  'deleted_at',
] as const;

export type PacuRecordsColumn = typeof PACU_RECORDS_COLUMNS[number];
