// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PasswordResetTokensRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  token_hash: string;
  expires_at: string;
  used_at?: string | null;
  requested_ip?: string | null;
  requested_user_agent?: string | null;
  created_at: string;
}

export const PASSWORD_RESET_TOKENS_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'token_hash',
  'expires_at',
  'used_at',
  'requested_ip',
  'requested_user_agent',
  'created_at',
] as const;

export type PasswordResetTokensColumn = typeof PASSWORD_RESET_TOKENS_COLUMNS[number];
