// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PathologyOrdersRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  appointment_id?: string | null;
  ordered_by_id: string;
  order_number: string;
  panel_name: string;
  tests: unknown;
  urgency: string;
  clinical_notes?: string | null;
  fasting?: boolean | null;
  copy_to_gp?: boolean | null;
  status: string;
  hl7_sent_at?: string | null;
  hl7_message?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PATHOLOGY_ORDERS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'appointment_id',
  'ordered_by_id',
  'order_number',
  'panel_name',
  'tests',
  'urgency',
  'clinical_notes',
  'fasting',
  'copy_to_gp',
  'status',
  'hl7_sent_at',
  'hl7_message',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PathologyOrdersColumn = typeof PATHOLOGY_ORDERS_COLUMNS[number];
