// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientMicroLearningAssignmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  card_id: string;
  rule_id?: string | null;
  status: string;
  assigned_at: string;
  opened_at?: string | null;
  completed_at?: string | null;
  source_reason?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_MICRO_LEARNING_ASSIGNMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'card_id',
  'rule_id',
  'status',
  'assigned_at',
  'opened_at',
  'completed_at',
  'source_reason',
  'created_at',
  'updated_at',
] as const;

export type PatientMicroLearningAssignmentsColumn = typeof PATIENT_MICRO_LEARNING_ASSIGNMENTS_COLUMNS[number];
