// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientDutyRelationshipsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  staff_id: string;
  created_by_id?: string | null;
  relationship_type: string;
  reason: string;
  expires_at: string;
  created_at: string;
  revoked_at?: string | null;
  revoked_by_id?: string | null;
  lock_version: number;
}

export const PATIENT_DUTY_RELATIONSHIPS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'staff_id',
  'created_by_id',
  'relationship_type',
  'reason',
  'expires_at',
  'created_at',
  'revoked_at',
  'revoked_by_id',
  'lock_version',
] as const;

export type PatientDutyRelationshipsColumn = typeof PATIENT_DUTY_RELATIONSHIPS_COLUMNS[number];
