// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientLegalOrdersRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  order_type_id: string;
  entered_by_id?: string | null;
  order_number?: string | null;
  start_date: string;
  end_date?: string | null;
  review_date?: string | null;
  next_application_date?: string | null;
  status: string;
  notes?: string | null;
  ai_summary?: string | null;
  created_at: string;
  updated_at: string;
  lock_version: number;
}

export const PATIENT_LEGAL_ORDERS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'order_type_id',
  'entered_by_id',
  'order_number',
  'start_date',
  'end_date',
  'review_date',
  'next_application_date',
  'status',
  'notes',
  'ai_summary',
  'created_at',
  'updated_at',
  'lock_version',
] as const;

export type PatientLegalOrdersColumn = typeof PATIENT_LEGAL_ORDERS_COLUMNS[number];
