// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientRoutineEventsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  routine_id?: string | null;
  event_type: string;
  value_numeric?: string | null;
  value_text?: string | null;
  occurred_at: string;
  created_at: string;
}

export const PATIENT_ROUTINE_EVENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'routine_id',
  'event_type',
  'value_numeric',
  'value_text',
  'occurred_at',
  'created_at',
] as const;

export type PatientRoutineEventsColumn = typeof PATIENT_ROUTINE_EVENTS_COLUMNS[number];
