// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientInvitesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  code: string;
  qr_token: string;
  expires_at: string;
  used_at?: string | null;
  created_by?: string | null;
  created_at: string;
}

export const PATIENT_INVITES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'code',
  'qr_token',
  'expires_at',
  'used_at',
  'created_by',
  'created_at',
] as const;

export type PatientInvitesColumn = typeof PATIENT_INVITES_COLUMNS[number];
