// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientDeviceSourcesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  provider: string;
  device_label: string;
  external_device_id?: string | null;
  is_active: boolean;
  metadata: unknown;
  last_ingested_at?: string | null;
  lock_version: number;
  created_at: string;
  updated_at: string;
}

export const PATIENT_DEVICE_SOURCES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'provider',
  'device_label',
  'external_device_id',
  'is_active',
  'metadata',
  'last_ingested_at',
  'lock_version',
  'created_at',
  'updated_at',
] as const;

export type PatientDeviceSourcesColumn = typeof PATIENT_DEVICE_SOURCES_COLUMNS[number];
