// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientBehaviorContractsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  pathway_id?: string | null;
  trigger_text: string;
  commitment_behavior: string;
  fallback_plan: string;
  review_date: string;
  accountability_partner?: string | null;
  adherence_status: string;
  adherence_note?: string | null;
  last_adherence_check_at?: string | null;
  is_active: boolean;
  lock_version: number;
  created_by_staff_id?: string | null;
  updated_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_BEHAVIOR_CONTRACTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'pathway_id',
  'trigger_text',
  'commitment_behavior',
  'fallback_plan',
  'review_date',
  'accountability_partner',
  'adherence_status',
  'adherence_note',
  'last_adherence_check_at',
  'is_active',
  'lock_version',
  'created_by_staff_id',
  'updated_by_staff_id',
  'created_at',
  'updated_at',
] as const;

export type PatientBehaviorContractsColumn = typeof PATIENT_BEHAVIOR_CONTRACTS_COLUMNS[number];
