// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientTrackingRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  tracking_type: string;
  value: string;
  note?: string | null;
  recorded_at: string;
  source: string;
  created_at: string;
}

export const PATIENT_TRACKING_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'tracking_type',
  'value',
  'note',
  'recorded_at',
  'source',
  'created_at',
] as const;

export type PatientTrackingColumn = typeof PATIENT_TRACKING_COLUMNS[number];
