// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientAlertsRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  alert_type_id: string;
  entered_by_id?: string | null;
  title: string;
  notes?: string | null;
  management_plan?: string | null;
  severity: string;
  is_active: boolean;
  show_flag: boolean;
  created_at: string;
  updated_at: string;
  resolved_at?: string | null;
}

export const PATIENT_ALERTS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'alert_type_id',
  'entered_by_id',
  'title',
  'notes',
  'management_plan',
  'severity',
  'is_active',
  'show_flag',
  'created_at',
  'updated_at',
  'resolved_at',
] as const;

export type PatientAlertsColumn = typeof PATIENT_ALERTS_COLUMNS[number];
