// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientFcmTokensRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  patient_app_account_id?: string | null;
  device_token: string;
  platform: string;
  last_seen_at: string;
  created_at: string;
  deleted_at?: string | null;
}

export const PATIENT_FCM_TOKENS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'patient_app_account_id',
  'device_token',
  'platform',
  'last_seen_at',
  'created_at',
  'deleted_at',
] as const;

export type PatientFcmTokensColumn = typeof PATIENT_FCM_TOKENS_COLUMNS[number];
