// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientSyncPreferencesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  module_key: string;
  enabled: boolean;
  updated_by_patient: boolean;
  updated_by_staff_id?: string | null;
  updated_at: string;
  created_at: string;
}

export const PATIENT_SYNC_PREFERENCES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'module_key',
  'enabled',
  'updated_by_patient',
  'updated_by_staff_id',
  'updated_at',
  'created_at',
] as const;

export type PatientSyncPreferencesColumn = typeof PATIENT_SYNC_PREFERENCES_COLUMNS[number];
