// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientOutreachLogRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  kind: string;
  channel: string;
  skip_reason?: string | null;
  provider_message_id?: string | null;
  title?: string | null;
  body?: string | null;
  deep_link?: string | null;
  override_channel?: string | null;
  override_reason?: string | null;
  override_by_staff_id?: string | null;
  attempted_at: string;
  delivered_at?: string | null;
  failed_at?: string | null;
  error_message?: string | null;
}

export const PATIENT_OUTREACH_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'kind',
  'channel',
  'skip_reason',
  'provider_message_id',
  'title',
  'body',
  'deep_link',
  'override_channel',
  'override_reason',
  'override_by_staff_id',
  'attempted_at',
  'delivered_at',
  'failed_at',
  'error_message',
] as const;

export type PatientOutreachLogColumn = typeof PATIENT_OUTREACH_LOG_COLUMNS[number];
