// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientTeamAssignmentsRow {
  id: string;
  patient_id: string;
  org_unit_id: string;
  primary_clinician_id?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at?: string | null;
  referral_status: string;
  reviewed_by_id?: string | null;
  reviewed_at?: string | null;
  referred_by_id?: string | null;
  escalation_id?: string | null;
  rejection_reason?: string | null;
}

export const PATIENT_TEAM_ASSIGNMENTS_COLUMNS = [
  'id',
  'patient_id',
  'org_unit_id',
  'primary_clinician_id',
  'is_active',
  'created_at',
  'updated_at',
  'referral_status',
  'reviewed_by_id',
  'reviewed_at',
  'referred_by_id',
  'escalation_id',
  'rejection_reason',
] as const;

export type PatientTeamAssignmentsColumn = typeof PATIENT_TEAM_ASSIGNMENTS_COLUMNS[number];
