// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientTeamReallocationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  to_org_unit_id: string;
  to_primary_clinician_id?: string | null;
  from_org_unit_id?: string | null;
  status: string;
  referred_by_id: string;
  reviewed_by_id?: string | null;
  reviewed_at?: string | null;
  reason?: string | null;
  rejection_reason?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_TEAM_REALLOCATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'to_org_unit_id',
  'to_primary_clinician_id',
  'from_org_unit_id',
  'status',
  'referred_by_id',
  'reviewed_by_id',
  'reviewed_at',
  'reason',
  'rejection_reason',
  'created_at',
  'updated_at',
] as const;

export type PatientTeamReallocationsColumn = typeof PATIENT_TEAM_REALLOCATIONS_COLUMNS[number];
