// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientMedicationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  drug_product_id?: string | null;
  drug_code?: string | null;
  drug_label: string;
  generic_name?: string | null;
  brand_name?: string | null;
  dose: string;
  dose_unit?: string | null;
  route: string;
  frequency: string;
  instructions?: string | null;
  indication?: string | null;
  start_date?: string | null;
  end_date?: string | null;
  status: string;
  reason_for_cessation?: string | null;
  is_regular: boolean;
  is_prn: boolean;
  is_lai: boolean;
  taper_schedule?: unknown | null;
  source: string;
  prescribed_by_staff_id?: string | null;
  recorded_by_staff_id?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  prescribed_by_specialty_code?: string | null;
  category?: string | null;
  lock_version: number;
}

export const PATIENT_MEDICATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'drug_product_id',
  'drug_code',
  'drug_label',
  'generic_name',
  'brand_name',
  'dose',
  'dose_unit',
  'route',
  'frequency',
  'instructions',
  'indication',
  'start_date',
  'end_date',
  'status',
  'reason_for_cessation',
  'is_regular',
  'is_prn',
  'is_lai',
  'taper_schedule',
  'source',
  'prescribed_by_staff_id',
  'recorded_by_staff_id',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
  'prescribed_by_specialty_code',
  'category',
  'lock_version',
] as const;

export type PatientMedicationsColumn = typeof PATIENT_MEDICATIONS_COLUMNS[number];
