// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientMedRemindersRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  medication_id?: string | null;
  drug_name: string;
  dose?: string | null;
  instructions: string;
  days_of_week: unknown;
  reminder_time: string;
  is_active: boolean;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_MED_REMINDERS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'medication_id',
  'drug_name',
  'dose',
  'instructions',
  'days_of_week',
  'reminder_time',
  'is_active',
  'created_by',
  'created_at',
  'updated_at',
] as const;

export type PatientMedRemindersColumn = typeof PATIENT_MED_REMINDERS_COLUMNS[number];
