// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientsRow {
  id: string;
  clinic_id: string;
  emr_number?: string | null;
  given_name: string;
  family_name: string;
  preferred_name?: string | null;
  date_of_birth: string;
  gender?: string | null;
  pronouns?: string | null;
  email?: string | null;
  email_primary?: string | null;
  phone_mobile?: string | null;
  phone_home?: string | null;
  address_line1?: string | null;
  address_line2?: string | null;
  suburb?: string | null;
  state?: string | null;
  postcode?: string | null;
  country?: string | null;
  status: string;
  medicare_number?: string | null;
  medicare_reference?: string | null;
  medicare_expiry?: string | null;
  ihi_number?: string | null;
  dva_number?: string | null;
  dva_card_type?: string | null;
  indigenous_status?: string | null;
  atsi_status?: string | null;
  interpreter_required: boolean;
  interpreter_language?: string | null;
  emergency_contact_name?: string | null;
  emergency_contact_phone?: string | null;
  emergency_contact_relationship?: string | null;
  gp_name?: string | null;
  gp_practice?: string | null;
  gp_phone?: string | null;
  gp_fax?: string | null;
  gp_email?: string | null;
  gp_provider_number?: string | null;
  gp_address_street?: string | null;
  gp_address_suburb?: string | null;
  gp_address_state?: string | null;
  gp_address_postcode?: string | null;
  nok_name?: string | null;
  nok_relationship?: string | null;
  nok_phone?: string | null;
  consent_to_treatment?: boolean | null;
  consent_for_research?: boolean | null;
  consent_to_share_with_gp?: boolean | null;
  consent_to_share_with_carer?: boolean | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  viva_triage_number?: string | null;
  health_fund_name?: string | null;
  health_fund_number?: string | null;
  medicare_number_lookup?: string | null;
  ihi_number_lookup?: string | null;
  dva_number_lookup?: string | null;
  sms_consent: boolean;
  sms_consent_updated_at?: string | null;
  sms_consent_updated_by?: string | null;
  photo_url?: string | null;
  deceased_date?: string | null;
  purged_at?: string | null;
  last_contact_at?: string | null;
  ihi_record_status?: string | null;
  ihi_number_status?: string | null;
  ihi_verified_at?: string | null;
  search_tsv?: unknown | null;
}

export const PATIENTS_COLUMNS = [
  'id',
  'clinic_id',
  'emr_number',
  'given_name',
  'family_name',
  'preferred_name',
  'date_of_birth',
  'gender',
  'pronouns',
  'email',
  'email_primary',
  'phone_mobile',
  'phone_home',
  'address_line1',
  'address_line2',
  'suburb',
  'state',
  'postcode',
  'country',
  'status',
  'medicare_number',
  'medicare_reference',
  'medicare_expiry',
  'ihi_number',
  'dva_number',
  'dva_card_type',
  'indigenous_status',
  'atsi_status',
  'interpreter_required',
  'interpreter_language',
  'emergency_contact_name',
  'emergency_contact_phone',
  'emergency_contact_relationship',
  'gp_name',
  'gp_practice',
  'gp_phone',
  'gp_fax',
  'gp_email',
  'gp_provider_number',
  'gp_address_street',
  'gp_address_suburb',
  'gp_address_state',
  'gp_address_postcode',
  'nok_name',
  'nok_relationship',
  'nok_phone',
  'consent_to_treatment',
  'consent_for_research',
  'consent_to_share_with_gp',
  'consent_to_share_with_carer',
  'created_at',
  'updated_at',
  'deleted_at',
  'viva_triage_number',
  'health_fund_name',
  'health_fund_number',
  'medicare_number_lookup',
  'ihi_number_lookup',
  'dva_number_lookup',
  'sms_consent',
  'sms_consent_updated_at',
  'sms_consent_updated_by',
  'photo_url',
  'deceased_date',
  'purged_at',
  'last_contact_at',
  'ihi_record_status',
  'ihi_number_status',
  'ihi_verified_at',
  'search_tsv',
] as const;

export type PatientsColumn = typeof PATIENTS_COLUMNS[number];
