// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientAllergiesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  allergen: string;
  allergen_type: string;
  reaction?: string | null;
  severity: string;
  status: string;
  recorded_by_staff_id?: string | null;
  recorded_at: string;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PATIENT_ALLERGIES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'allergen',
  'allergen_type',
  'reaction',
  'severity',
  'status',
  'recorded_by_staff_id',
  'recorded_at',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PatientAllergiesColumn = typeof PATIENT_ALLERGIES_COLUMNS[number];
