// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientDigitalPhenotypesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  computation_day: string;
  lookback_days: number;
  sleep_hours_avg_7d?: string | null;
  steps_avg_7d?: string | null;
  resting_hr_avg_7d?: string | null;
  hrv_avg_7d?: string | null;
  mood_avg_7d?: string | null;
  anxiety_avg_7d?: string | null;
  adherence_score: string;
  risk_index: string;
  risk_band: string;
  contributing_signals: unknown;
  lock_version: number;
  created_at: string;
  updated_at: string;
}

export const PATIENT_DIGITAL_PHENOTYPES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'computation_day',
  'lookback_days',
  'sleep_hours_avg_7d',
  'steps_avg_7d',
  'resting_hr_avg_7d',
  'hrv_avg_7d',
  'mood_avg_7d',
  'anxiety_avg_7d',
  'adherence_score',
  'risk_index',
  'risk_band',
  'contributing_signals',
  'lock_version',
  'created_at',
  'updated_at',
] as const;

export type PatientDigitalPhenotypesColumn = typeof PATIENT_DIGITAL_PHENOTYPES_COLUMNS[number];
