// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientFlagsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  category: string;
  severity: string;
  title: string;
  description?: string | null;
  status: string;
  raised_by_staff_id?: string | null;
  resolved_by_staff_id?: string | null;
  raised_at: string;
  resolved_at?: string | null;
  related_record_type?: string | null;
  related_record_id?: string | null;
  is_header_flag: boolean;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PATIENT_FLAGS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'category',
  'severity',
  'title',
  'description',
  'status',
  'raised_by_staff_id',
  'resolved_by_staff_id',
  'raised_at',
  'resolved_at',
  'related_record_type',
  'related_record_id',
  'is_header_flag',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PatientFlagsColumn = typeof PATIENT_FLAGS_COLUMNS[number];
