// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientRoutinePlansRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  pathway_id?: string | null;
  name: string;
  condition_kind: string;
  condition_threshold?: string | null;
  condition_window_minutes: number;
  then_action_kind: string;
  then_action_text: string;
  fallback_after_minutes?: number | null;
  fallback_action_text?: string | null;
  review_date: string;
  is_active: boolean;
  lock_version: number;
  created_by_staff_id?: string | null;
  updated_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_ROUTINE_PLANS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'pathway_id',
  'name',
  'condition_kind',
  'condition_threshold',
  'condition_window_minutes',
  'then_action_kind',
  'then_action_text',
  'fallback_after_minutes',
  'fallback_action_text',
  'review_date',
  'is_active',
  'lock_version',
  'created_by_staff_id',
  'updated_by_staff_id',
  'created_at',
  'updated_at',
] as const;

export type PatientRoutinePlansColumn = typeof PATIENT_ROUTINE_PLANS_COLUMNS[number];
