// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientMergesRow {
  id: string;
  clinic_id: string;
  source_patient_id: string;
  destination_patient_id: string;
  merged_by: string;
  reason: string;
  source_snapshot: unknown;
  created_at: string;
}

export const PATIENT_MERGES_COLUMNS = [
  'id',
  'clinic_id',
  'source_patient_id',
  'destination_patient_id',
  'merged_by',
  'reason',
  'source_snapshot',
  'created_at',
] as const;

export type PatientMergesColumn = typeof PATIENT_MERGES_COLUMNS[number];
