// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientSharedDocumentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  title: string;
  doc_type: string;
  file_path?: string | null;
  url?: string | null;
  shared_by?: string | null;
  created_at: string;
}

export const PATIENT_SHARED_DOCUMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'title',
  'doc_type',
  'file_path',
  'url',
  'shared_by',
  'created_at',
] as const;

export type PatientSharedDocumentsColumn = typeof PATIENT_SHARED_DOCUMENTS_COLUMNS[number];
