// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientAttachmentsRow {
  id: string;
  patient_id: string;
  uploaded_by?: string | null;
  filename: string;
  label?: string | null;
  mime_type?: string | null;
  file_size?: number | null;
  file_path: string;
  is_active: boolean;
  created_at: string;
  storage_backend: string;
  storage_key?: string | null;
  storage_bucket?: string | null;
  storage_etag?: string | null;
  clinic_id: string;
  episode_id?: string | null;
  specialty_code?: string | null;
  updated_at?: string | null;
}

export const PATIENT_ATTACHMENTS_COLUMNS = [
  'id',
  'patient_id',
  'uploaded_by',
  'filename',
  'label',
  'mime_type',
  'file_size',
  'file_path',
  'is_active',
  'created_at',
  'storage_backend',
  'storage_key',
  'storage_bucket',
  'storage_etag',
  'clinic_id',
  'episode_id',
  'specialty_code',
  'updated_at',
] as const;

export type PatientAttachmentsColumn = typeof PATIENT_ATTACHMENTS_COLUMNS[number];
