// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientAppAccountsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  phone?: string | null;
  email?: string | null;
  password_hash: string;
  is_active: boolean;
  mfa_enabled: boolean;
  mfa_secret?: string | null;
  last_login_at?: string | null;
  failed_login_attempts: number;
  locked_until?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_APP_ACCOUNTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'phone',
  'email',
  'password_hash',
  'is_active',
  'mfa_enabled',
  'mfa_secret',
  'last_login_at',
  'failed_login_attempts',
  'locked_until',
  'created_at',
  'updated_at',
] as const;

export type PatientAppAccountsColumn = typeof PATIENT_APP_ACCOUNTS_COLUMNS[number];
