// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientSummarySignoffsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  signed_off_by_id: string;
  signed_off_at: string;
  review_due_date: string;
  review_interval_months: number;
  reminder_task_id?: string | null;
  lock_version: number;
  created_at: string;
  updated_at: string;
}

export const PATIENT_SUMMARY_SIGNOFFS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'signed_off_by_id',
  'signed_off_at',
  'review_due_date',
  'review_interval_months',
  'reminder_task_id',
  'lock_version',
  'created_at',
  'updated_at',
] as const;

export type PatientSummarySignoffsColumn = typeof PATIENT_SUMMARY_SIGNOFFS_COLUMNS[number];
