// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientBehavioralSegmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  segment_code: string;
  confidence_score: string;
  rationale: unknown;
  computed_at: string;
  override_by_staff_id?: string | null;
  override_reason?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_BEHAVIORAL_SEGMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'segment_code',
  'confidence_score',
  'rationale',
  'computed_at',
  'override_by_staff_id',
  'override_reason',
  'created_at',
  'updated_at',
] as const;

export type PatientBehavioralSegmentsColumn = typeof PATIENT_BEHAVIORAL_SEGMENTS_COLUMNS[number];
