// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientTasksRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  title: string;
  description?: string | null;
  due_date?: string | null;
  reminder_time?: unknown | null;
  status: string;
  completed_at?: string | null;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export const PATIENT_TASKS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'title',
  'description',
  'due_date',
  'reminder_time',
  'status',
  'completed_at',
  'created_by',
  'created_at',
  'updated_at',
] as const;

export type PatientTasksColumn = typeof PATIENT_TASKS_COLUMNS[number];
