// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientContactsRow {
  id: string;
  patient_id: string;
  given_name: string;
  family_name?: string | null;
  relationship?: string | null;
  phone_mobile?: string | null;
  phone_home?: string | null;
  email?: string | null;
  is_emergency_contact: boolean;
  is_carer: boolean;
  has_consent: boolean;
  created_at: string;
  updated_at?: string | null;
  contact_type?: string | null;
  consent_level?: string | null;
  consent_notes?: string | null;
  deleted_at?: string | null;
  clinic_id: string;
}

export const PATIENT_CONTACTS_COLUMNS = [
  'id',
  'patient_id',
  'given_name',
  'family_name',
  'relationship',
  'phone_mobile',
  'phone_home',
  'email',
  'is_emergency_contact',
  'is_carer',
  'has_consent',
  'created_at',
  'updated_at',
  'contact_type',
  'consent_level',
  'consent_notes',
  'deleted_at',
  'clinic_id',
] as const;

export type PatientContactsColumn = typeof PATIENT_CONTACTS_COLUMNS[number];
