// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientAppRegistrationRequestsRow {
  id: string;
  clinic_id: string;
  dedupe_key: string;
  given_name: string;
  family_name: string;
  preferred_name?: string | null;
  date_of_birth: string;
  gender?: string | null;
  phone_mobile: string;
  email?: string | null;
  address: unknown;
  next_of_kin: unknown;
  gp: unknown;
  support_person: unknown;
  reason?: string | null;
  source: string;
  status: string;
  reviewed_by_staff_id?: string | null;
  reviewed_at?: string | null;
  duplicate_patient_id?: string | null;
  client_request_id?: string | null;
  metadata: unknown;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
}

export const PATIENT_APP_REGISTRATION_REQUESTS_COLUMNS = [
  'id',
  'clinic_id',
  'dedupe_key',
  'given_name',
  'family_name',
  'preferred_name',
  'date_of_birth',
  'gender',
  'phone_mobile',
  'email',
  'address',
  'next_of_kin',
  'gp',
  'support_person',
  'reason',
  'source',
  'status',
  'reviewed_by_staff_id',
  'reviewed_at',
  'duplicate_patient_id',
  'client_request_id',
  'metadata',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
] as const;

export type PatientAppRegistrationRequestsColumn = typeof PATIENT_APP_REGISTRATION_REQUESTS_COLUMNS[number];
