// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientLegalAttachmentsRow {
  id: string;
  patient_id: string;
  legal_order_id?: string | null;
  category: string;
  filename: string;
  mime_type?: string | null;
  file_size?: number | null;
  file_path: string;
  created_at: string;
  storage_backend: string;
  storage_key?: string | null;
  storage_bucket?: string | null;
  storage_etag?: string | null;
  clinic_id: string;
  updated_at?: string | null;
}

export const PATIENT_LEGAL_ATTACHMENTS_COLUMNS = [
  'id',
  'patient_id',
  'legal_order_id',
  'category',
  'filename',
  'mime_type',
  'file_size',
  'file_path',
  'created_at',
  'storage_backend',
  'storage_key',
  'storage_bucket',
  'storage_etag',
  'clinic_id',
  'updated_at',
] as const;

export type PatientLegalAttachmentsColumn = typeof PATIENT_LEGAL_ATTACHMENTS_COLUMNS[number];
