// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientIhisRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  ihi_value: string;
  ihi_lookup: string;
  record_status: string;
  number_status: string;
  source: string;
  hi_verified_at: string;
  hi_display_name_original?: string | null;
  hi_display_name_40?: string | null;
  hi_name_was_truncated: boolean;
  created_by_staff_id?: string | null;
  created_at: string;
}

export const PATIENT_IHIS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'ihi_value',
  'ihi_lookup',
  'record_status',
  'number_status',
  'source',
  'hi_verified_at',
  'hi_display_name_original',
  'hi_display_name_40',
  'hi_name_was_truncated',
  'created_by_staff_id',
  'created_at',
] as const;

export type PatientIhisColumn = typeof PATIENT_IHIS_COLUMNS[number];
