// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PatientProvidersRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  provider_type?: string | null;
  provider_name?: string | null;
  provider_practice?: string | null;
  provider_phone?: string | null;
  provider_fax?: string | null;
  provider_email?: string | null;
  provider_number?: string | null;
  provider_address?: string | null;
  is_primary?: boolean | null;
  created_at: string;
  updated_at?: string | null;
}

export const PATIENT_PROVIDERS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'provider_type',
  'provider_name',
  'provider_practice',
  'provider_phone',
  'provider_fax',
  'provider_email',
  'provider_number',
  'provider_address',
  'is_primary',
  'created_at',
  'updated_at',
] as const;

export type PatientProvidersColumn = typeof PATIENT_PROVIDERS_COLUMNS[number];
