// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PaymentsRow {
  id: string;
  invoice_id?: string | null;
  clinic_id: string;
  amount_cents?: number | null;
  payment_method?: string | null;
  reference?: string | null;
  status?: string | null;
  paid_at?: string | null;
  created_at: string;
  received_by_id?: string | null;
  payment_date?: string | null;
  claim_status?: string | null;
  claim_reference?: string | null;
  notes?: string | null;
  updated_at?: string | null;
}

export const PAYMENTS_COLUMNS = [
  'id',
  'invoice_id',
  'clinic_id',
  'amount_cents',
  'payment_method',
  'reference',
  'status',
  'paid_at',
  'created_at',
  'received_by_id',
  'payment_date',
  'claim_status',
  'claim_reference',
  'notes',
  'updated_at',
] as const;

export type PaymentsColumn = typeof PAYMENTS_COLUMNS[number];
