// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PermissionsRow {
  id: string;
  name: string;
  description?: string | null;
  created_at: string;
  updated_at: string;
}

export const PERMISSIONS_COLUMNS = [
  'id',
  'name',
  'description',
  'created_at',
  'updated_at',
] as const;

export type PermissionsColumn = typeof PERMISSIONS_COLUMNS[number];
