// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PhiScrubberRulesRow {
  id: string;
  clinic_id?: string | null;
  category: string;
  name: string;
  pattern: string;
  replacement: string;
  precedence: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const PHI_SCRUBBER_RULES_COLUMNS = [
  'id',
  'clinic_id',
  'category',
  'name',
  'pattern',
  'replacement',
  'precedence',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type PhiScrubberRulesColumn = typeof PHI_SCRUBBER_RULES_COLUMNS[number];
