// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PhoneTriageRow {
  id: string;
  clinic_id: string;
  patient_id?: string | null;
  caller_name: string;
  caller_relationship?: string | null;
  caller_phone?: string | null;
  reason_for_call: string;
  urgency: string;
  triage_notes?: string | null;
  action_taken?: string | null;
  assigned_to_id?: string | null;
  received_by_id?: string | null;
  triaged_by_staff_id?: string | null;
  status: string;
  created_at: string;
  updated_at: string;
  receptionist_summary?: string | null;
  clinical_risk_flags?: unknown | null;
  lock_version: number;
}

export const PHONE_TRIAGE_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'caller_name',
  'caller_relationship',
  'caller_phone',
  'reason_for_call',
  'urgency',
  'triage_notes',
  'action_taken',
  'assigned_to_id',
  'received_by_id',
  'triaged_by_staff_id',
  'status',
  'created_at',
  'updated_at',
  'receptionist_summary',
  'clinical_risk_flags',
  'lock_version',
] as const;

export type PhoneTriageColumn = typeof PHONE_TRIAGE_COLUMNS[number];
