// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PlannedTransitionsRow {
  id: string;
  clinic_id: string;
  from_staff_id: string;
  reason: string;
  effective_date: string;
  status: string;
  created_by_id: string;
  approved_by_id?: string | null;
  approved_at?: string | null;
  executed_at?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PLANNED_TRANSITIONS_COLUMNS = [
  'id',
  'clinic_id',
  'from_staff_id',
  'reason',
  'effective_date',
  'status',
  'created_by_id',
  'approved_by_id',
  'approved_at',
  'executed_at',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PlannedTransitionsColumn = typeof PLANNED_TRANSITIONS_COLUMNS[number];
