// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PlannedTransitionAssignmentsRow {
  id: string;
  transition_id: string;
  patient_id: string;
  episode_id?: string | null;
  to_staff_id: string;
  to_team?: string | null;
  status: string;
  handover_notes?: string | null;
  executed_at?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const PLANNED_TRANSITION_ASSIGNMENTS_COLUMNS = [
  'id',
  'transition_id',
  'patient_id',
  'episode_id',
  'to_staff_id',
  'to_team',
  'status',
  'handover_notes',
  'executed_at',
  'created_at',
  'updated_at',
] as const;

export type PlannedTransitionAssignmentsColumn = typeof PLANNED_TRANSITION_ASSIGNMENTS_COLUMNS[number];
