// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PregnanciesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  lmp_date: string;
  edd_date: string;
  gtpal: unknown;
  status: string;
  note?: string | null;
  recorded_by?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PREGNANCIES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'lmp_date',
  'edd_date',
  'gtpal',
  'status',
  'note',
  'recorded_by',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PregnanciesColumn = typeof PREGNANCIES_COLUMNS[number];
