// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PrescriptionsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  drug_product_id?: string | null;
  prescribed_by_staff_id: string;
  patient_medication_id?: string | null;
  generic_name: string;
  brand_name?: string | null;
  dose: string;
  route: string;
  frequency: string;
  directions?: string | null;
  quantity: number;
  repeats: number;
  pbs_item_code?: string | null;
  is_authority: boolean;
  authority_code?: string | null;
  is_s8: boolean;
  prescription_type: string;
  status: string;
  safescript_checked: boolean;
  safescript_checked_at?: string | null;
  safescript_result?: unknown | null;
  erx_token?: string | null;
  erx_dsp_id?: string | null;
  erx_submitted_at?: string | null;
  is_electronic: boolean;
  prescribed_date: string;
  expires_at?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  prescription_category: string;
  lock_version: number;
  cancellation_reason?: string | null;
  cancelled_at?: string | null;
  cancelled_by_staff_id?: string | null;
}

export const PRESCRIPTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'drug_product_id',
  'prescribed_by_staff_id',
  'patient_medication_id',
  'generic_name',
  'brand_name',
  'dose',
  'route',
  'frequency',
  'directions',
  'quantity',
  'repeats',
  'pbs_item_code',
  'is_authority',
  'authority_code',
  'is_s8',
  'prescription_type',
  'status',
  'safescript_checked',
  'safescript_checked_at',
  'safescript_result',
  'erx_token',
  'erx_dsp_id',
  'erx_submitted_at',
  'is_electronic',
  'prescribed_date',
  'expires_at',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
  'prescription_category',
  'lock_version',
  'cancellation_reason',
  'cancelled_at',
  'cancelled_by_staff_id',
] as const;

export type PrescriptionsColumn = typeof PRESCRIPTIONS_COLUMNS[number];
