// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PrimaryCancerConditionsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  icd10?: string | null;
  snomed?: string | null;
  histology?: string | null;
  laterality?: string | null;
  diagnosis_date: string;
  stage_system?: string | null;
  notes?: string | null;
  created_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PRIMARY_CANCER_CONDITIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'icd10',
  'snomed',
  'histology',
  'laterality',
  'diagnosis_date',
  'stage_system',
  'notes',
  'created_by_staff_id',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PrimaryCancerConditionsColumn = typeof PRIMARY_CANCER_CONDITIONS_COLUMNS[number];
