// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ProblemListRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  code_system: string;
  code: string;
  display: string;
  category: string;
  clinical_status: string;
  verification_status: string;
  severity?: string | null;
  is_chronic: boolean;
  onset_date?: string | null;
  onset_age_years?: unknown | null;
  abatement_date?: string | null;
  note?: string | null;
  recorded_date: string;
  recorded_by?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PROBLEM_LIST_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'code_system',
  'code',
  'display',
  'category',
  'clinical_status',
  'verification_status',
  'severity',
  'is_chronic',
  'onset_date',
  'onset_age_years',
  'abatement_date',
  'note',
  'recorded_date',
  'recorded_by',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ProblemListColumn = typeof PROBLEM_LIST_COLUMNS[number];
