// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ProgramsRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const PROGRAMS_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type ProgramsColumn = typeof PROGRAMS_COLUMNS[number];
