// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface PsychologySessionNotesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  staff_id: string;
  session_date: string;
  duration_min?: number | null;
  session_type?: string | null;
  content?: string | null;
  outcome_scores?: unknown | null;
  shared_with_clinicians: boolean;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const PSYCHOLOGY_SESSION_NOTES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'staff_id',
  'session_date',
  'duration_min',
  'session_type',
  'content',
  'outcome_scores',
  'shared_with_clinicians',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type PsychologySessionNotesColumn = typeof PSYCHOLOGY_SESSION_NOTES_COLUMNS[number];
