// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralWorkflowEventsRow {
  clinic_id: string;
  referral_id: string;
  event_type: string;
  performed_by_staff_id?: string | null;
  notes?: string | null;
  outcome?: string | null;
  event_at: string;
  created_at: string;
  updated_at?: string | null;
}

export const REFERRAL_WORKFLOW_EVENTS_COLUMNS = [
  'clinic_id',
  'referral_id',
  'event_type',
  'performed_by_staff_id',
  'notes',
  'outcome',
  'event_at',
  'created_at',
  'updated_at',
] as const;

export type ReferralWorkflowEventsColumn = typeof REFERRAL_WORKFLOW_EVENTS_COLUMNS[number];
