// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  referral_number: string;
  referral_date: string;
  source: string;
  from_service: string;
  from_provider_name?: string | null;
  from_provider_phone?: string | null;
  from_provider_email?: string | null;
  from_provider_prescriber_no?: string | null;
  referring_org?: string | null;
  reason: string;
  clinical_summary?: string | null;
  current_medications?: string | null;
  diagnosis_info?: string | null;
  urgency: string;
  status: string;
  status_changed_at?: string | null;
  received_at: string;
  assigned_to_staff_id?: string | null;
  linked_episode_id?: string | null;
  has_attachment: boolean;
  ocr_extracted?: unknown | null;
  rejection_reason?: string | null;
  redirect_to?: string | null;
  sla_due_date?: string | null;
  sla_breached: boolean;
  internal_notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  referral_mode: string;
  target_clinician_id?: string | null;
  distribution_mode?: string | null;
  distribution_speciality?: string | null;
  accepted_by_staff_id?: string | null;
  broadcast_at?: string | null;
  reminder_sent_at?: string | null;
  final_reminder_sent_at?: string | null;
  auto_close_at?: string | null;
  feedback_sent_at?: string | null;
  clarification_notes?: string | null;
  created_by_staff_id?: string | null;
  target_specialty_code: string;
  service_request_status: string;
  task_status: string;
  coordinator_id?: string | null;
  triaged_at?: string | null;
  triaged_by?: string | null;
}

export const REFERRALS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'referral_number',
  'referral_date',
  'source',
  'from_service',
  'from_provider_name',
  'from_provider_phone',
  'from_provider_email',
  'from_provider_prescriber_no',
  'referring_org',
  'reason',
  'clinical_summary',
  'current_medications',
  'diagnosis_info',
  'urgency',
  'status',
  'status_changed_at',
  'received_at',
  'assigned_to_staff_id',
  'linked_episode_id',
  'has_attachment',
  'ocr_extracted',
  'rejection_reason',
  'redirect_to',
  'sla_due_date',
  'sla_breached',
  'internal_notes',
  'created_at',
  'updated_at',
  'deleted_at',
  'referral_mode',
  'target_clinician_id',
  'distribution_mode',
  'distribution_speciality',
  'accepted_by_staff_id',
  'broadcast_at',
  'reminder_sent_at',
  'final_reminder_sent_at',
  'auto_close_at',
  'feedback_sent_at',
  'clarification_notes',
  'created_by_staff_id',
  'target_specialty_code',
  'service_request_status',
  'task_status',
  'coordinator_id',
  'triaged_at',
  'triaged_by',
] as const;

export type ReferralsColumn = typeof REFERRALS_COLUMNS[number];
