// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralClinicianOffersRow {
  id: string;
  clinic_id: string;
  referral_id: string;
  staff_id: string;
  offered_at: string;
  response: string;
  responded_at?: string | null;
  decline_reason?: string | null;
  created_at: string;
  updated_at: string;
}

export const REFERRAL_CLINICIAN_OFFERS_COLUMNS = [
  'id',
  'clinic_id',
  'referral_id',
  'staff_id',
  'offered_at',
  'response',
  'responded_at',
  'decline_reason',
  'created_at',
  'updated_at',
] as const;

export type ReferralClinicianOffersColumn = typeof REFERRAL_CLINICIAN_OFFERS_COLUMNS[number];
