// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralValidityRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  referring_provider_name: string;
  referring_provider_number?: string | null;
  referral_type: string;
  referral_date: string;
  expires_at: string;
  is_active: boolean;
  notes?: string | null;
  created_at: string;
  updated_at: string;
}

export const REFERRAL_VALIDITY_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'referring_provider_name',
  'referring_provider_number',
  'referral_type',
  'referral_date',
  'expires_at',
  'is_active',
  'notes',
  'created_at',
  'updated_at',
] as const;

export type ReferralValidityColumn = typeof REFERRAL_VALIDITY_COLUMNS[number];
