// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralAttachmentsRow {
  id: string;
  clinic_id: string;
  referral_id: string;
  original_filename: string;
  stored_filename: string;
  mime_type: string;
  file_size_bytes: number;
  storage_key: string;
  category: string;
  ocr_status: string;
  ocr_result?: unknown | null;
  ocr_error_message?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const REFERRAL_ATTACHMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'referral_id',
  'original_filename',
  'stored_filename',
  'mime_type',
  'file_size_bytes',
  'storage_key',
  'category',
  'ocr_status',
  'ocr_result',
  'ocr_error_message',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ReferralAttachmentsColumn = typeof REFERRAL_ATTACHMENTS_COLUMNS[number];
