// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralFeedbackLogRow {
  id: string;
  clinic_id: string;
  referral_id: string;
  feedback_type: string;
  recipient_email: string;
  sent_at: string;
  message_body?: string | null;
  sent_by_staff_id?: string | null;
  delivery_status: string;
  created_at: string;
}

export const REFERRAL_FEEDBACK_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'referral_id',
  'feedback_type',
  'recipient_email',
  'sent_at',
  'message_body',
  'sent_by_staff_id',
  'delivery_status',
  'created_at',
] as const;

export type ReferralFeedbackLogColumn = typeof REFERRAL_FEEDBACK_LOG_COLUMNS[number];
