// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralSourcesRow {
  id: string;
  clinic_id: string;
  category: string;
  name: string;
  is_active: boolean;
  sort_order: number;
  created_at: string;
  updated_at: string;
}

export const REFERRAL_SOURCES_COLUMNS = [
  'id',
  'clinic_id',
  'category',
  'name',
  'is_active',
  'sort_order',
  'created_at',
  'updated_at',
] as const;

export type ReferralSourcesColumn = typeof REFERRAL_SOURCES_COLUMNS[number];
