// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReferralStateTransitionsRow {
  id: string;
  clinic_id: string;
  referral_id: string;
  from_task_status?: string | null;
  to_task_status: string;
  actor_id?: string | null;
  reason?: string | null;
  created_at: string;
}

export const REFERRAL_STATE_TRANSITIONS_COLUMNS = [
  'id',
  'clinic_id',
  'referral_id',
  'from_task_status',
  'to_task_status',
  'actor_id',
  'reason',
  'created_at',
] as const;

export type ReferralStateTransitionsColumn = typeof REFERRAL_STATE_TRANSITIONS_COLUMNS[number];
