// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReportSchedulesRow {
  id: string;
  clinic_id: string;
  report_type: string;
  name: string;
  frequency: string;
  schedule_cron?: string | null;
  recipients: unknown;
  filters: unknown;
  format: string;
  is_active: boolean;
  created_by_staff_id?: string | null;
  last_run_at?: string | null;
  next_run_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const REPORT_SCHEDULES_COLUMNS = [
  'id',
  'clinic_id',
  'report_type',
  'name',
  'frequency',
  'schedule_cron',
  'recipients',
  'filters',
  'format',
  'is_active',
  'created_by_staff_id',
  'last_run_at',
  'next_run_at',
  'created_at',
  'updated_at',
] as const;

export type ReportSchedulesColumn = typeof REPORT_SCHEDULES_COLUMNS[number];
