// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReportRunsRow {
  id: string;
  clinic_id: string;
  requested_by_id: string;
  report_type: string;
  filters: unknown;
  format: string;
  status: string;
  total_rows: number;
  result_data?: unknown | null;
  error_message?: string | null;
  generated_at: string;
  created_at: string;
  updated_at: string;
}

export const REPORT_RUNS_COLUMNS = [
  'id',
  'clinic_id',
  'requested_by_id',
  'report_type',
  'filters',
  'format',
  'status',
  'total_rows',
  'result_data',
  'error_message',
  'generated_at',
  'created_at',
  'updated_at',
] as const;

export type ReportRunsColumn = typeof REPORT_RUNS_COLUMNS[number];
