// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface RestrictiveInterventionsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  intervention_type?: string | null;
  start_time?: string | null;
  end_time?: string | null;
  duration_minutes?: number | null;
  reason?: string | null;
  authorised_by_id?: string | null;
  recorded_by_id?: string | null;
  outcome?: string | null;
  created_at: string;
  updated_at?: string | null;
  alternatives_tried?: string | null;
  debrief_completed: boolean;
  debrief_notes?: string | null;
  notified_persons?: unknown | null;
  lock_version: number;
}

export const RESTRICTIVE_INTERVENTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'intervention_type',
  'start_time',
  'end_time',
  'duration_minutes',
  'reason',
  'authorised_by_id',
  'recorded_by_id',
  'outcome',
  'created_at',
  'updated_at',
  'alternatives_tried',
  'debrief_completed',
  'debrief_notes',
  'notified_persons',
  'lock_version',
] as const;

export type RestrictiveInterventionsColumn = typeof RESTRICTIVE_INTERVENTIONS_COLUMNS[number];
