// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ReviewPlansRow {
  id: string;
  clinic_id: string;
  encounter_id: string;
  patient_id: string;
  episode_id?: string | null;
  plan_text: string;
  follow_up_date?: string | null;
  follow_up_type?: string | null;
  tasks_to_create?: unknown | null;
  generate_letter: boolean;
  letter_type?: string | null;
  letter_recipient?: string | null;
  letter_job_id?: string | null;
  tasks_created: number;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const REVIEW_PLANS_COLUMNS = [
  'id',
  'clinic_id',
  'encounter_id',
  'patient_id',
  'episode_id',
  'plan_text',
  'follow_up_date',
  'follow_up_type',
  'tasks_to_create',
  'generate_letter',
  'letter_type',
  'letter_recipient',
  'letter_job_id',
  'tasks_created',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type ReviewPlansColumn = typeof REVIEW_PLANS_COLUMNS[number];
