// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface RiskAssessmentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  template_submission_id?: string | null;
  assessment_type: string;
  total_score?: string | null;
  score_band?: string | null;
  interpretation_detail?: unknown | null;
  overall_risk_level: string;
  suicide_risk: boolean;
  self_harm_risk: boolean;
  harm_to_others_risk: boolean;
  absconding_risk: boolean;
  vulnerability_risk: boolean;
  protective_factors?: string | null;
  risk_narrative?: string | null;
  risk_management_plan?: string | null;
  safety_plan_in_place: boolean;
  safety_plan_summary?: string | null;
  assessed_by_id: string;
  assessment_date: string;
  review_date?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  lock_version: number;
}

export const RISK_ASSESSMENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'template_submission_id',
  'assessment_type',
  'total_score',
  'score_band',
  'interpretation_detail',
  'overall_risk_level',
  'suicide_risk',
  'self_harm_risk',
  'harm_to_others_risk',
  'absconding_risk',
  'vulnerability_risk',
  'protective_factors',
  'risk_narrative',
  'risk_management_plan',
  'safety_plan_in_place',
  'safety_plan_summary',
  'assessed_by_id',
  'assessment_date',
  'review_date',
  'created_at',
  'updated_at',
  'deleted_at',
  'lock_version',
] as const;

export type RiskAssessmentsColumn = typeof RISK_ASSESSMENTS_COLUMNS[number];
