// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SafetyPlansRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  content?: unknown | null;
  status: string;
  created_at: string;
  updated_at: string;
}

export const SAFETY_PLANS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'content',
  'status',
  'created_at',
  'updated_at',
] as const;

export type SafetyPlansColumn = typeof SAFETY_PLANS_COLUMNS[number];
