// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SafetyChecklistsRow {
  id: string;
  clinic_id: string;
  case_id: string;
  phase: string;
  items: unknown;
  completed_by?: string | null;
  completed_at: string;
  created_at: string;
  deleted_at?: string | null;
}

export const SAFETY_CHECKLISTS_COLUMNS = [
  'id',
  'clinic_id',
  'case_id',
  'phase',
  'items',
  'completed_by',
  'completed_at',
  'created_at',
  'deleted_at',
] as const;

export type SafetyChecklistsColumn = typeof SAFETY_CHECKLISTS_COLUMNS[number];
