// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ScribeSensitiveFlagsRow {
  id: string;
  clinic_id: string;
  session_id: string;
  patient_id: string;
  category: string;
  severity: string;
  transcript_offset?: number | null;
  snippet?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  review_disposition?: string | null;
  created_at: string;
}

export const SCRIBE_SENSITIVE_FLAGS_COLUMNS = [
  'id',
  'clinic_id',
  'session_id',
  'patient_id',
  'category',
  'severity',
  'transcript_offset',
  'snippet',
  'reviewed_by',
  'reviewed_at',
  'review_disposition',
  'created_at',
] as const;

export type ScribeSensitiveFlagsColumn = typeof SCRIBE_SENSITIVE_FLAGS_COLUMNS[number];
