// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ScribeNoteTemplatesRow {
  id: string;
  clinic_id?: string | null;
  variant: string;
  name: string;
  system_prompt: string;
  user_prompt_template: string;
  sections: unknown;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const SCRIBE_NOTE_TEMPLATES_COLUMNS = [
  'id',
  'clinic_id',
  'variant',
  'name',
  'system_prompt',
  'user_prompt_template',
  'sections',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type ScribeNoteTemplatesColumn = typeof SCRIBE_NOTE_TEMPLATES_COLUMNS[number];
