// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ScribeConsentsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  session_id?: string | null;
  mode: string;
  patient_signature_png?: string | null;
  clinician_attested_by_id?: string | null;
  clinician_attestation_text?: string | null;
  attested_at?: string | null;
  created_at: string;
  revoked_at?: string | null;
  revoked_by?: string | null;
  revoke_reason?: string | null;
}

export const SCRIBE_CONSENTS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'session_id',
  'mode',
  'patient_signature_png',
  'clinician_attested_by_id',
  'clinician_attestation_text',
  'attested_at',
  'created_at',
  'revoked_at',
  'revoked_by',
  'revoke_reason',
] as const;

export type ScribeConsentsColumn = typeof SCRIBE_CONSENTS_COLUMNS[number];
