// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ScribeTalkTimeMetricsRow {
  id: string;
  clinic_id: string;
  session_id: string;
  clinician_seconds: number;
  patient_seconds: number;
  silence_seconds: number;
  total_seconds: number;
  created_at: string;
}

export const SCRIBE_TALK_TIME_METRICS_COLUMNS = [
  'id',
  'clinic_id',
  'session_id',
  'clinician_seconds',
  'patient_seconds',
  'silence_seconds',
  'total_seconds',
  'created_at',
] as const;

export type ScribeTalkTimeMetricsColumn = typeof SCRIBE_TALK_TIME_METRICS_COLUMNS[number];
