// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ScribeSessionsRow {
  id: string;
  clinic_id: string;
  clinician_id: string;
  patient_id: string;
  consent_id?: string | null;
  status: string;
  whisper_mode: boolean;
  started_at: string;
  paused_at?: string | null;
  resumed_at?: string | null;
  ended_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const SCRIBE_SESSIONS_COLUMNS = [
  'id',
  'clinic_id',
  'clinician_id',
  'patient_id',
  'consent_id',
  'status',
  'whisper_mode',
  'started_at',
  'paused_at',
  'resumed_at',
  'ended_at',
  'created_at',
  'updated_at',
] as const;

export type ScribeSessionsColumn = typeof SCRIBE_SESSIONS_COLUMNS[number];
