// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ScribeActionItemsRow {
  id: string;
  clinic_id: string;
  session_id: string;
  patient_id: string;
  item_type: string;
  description: string;
  assignee_role?: string | null;
  due_date?: string | null;
  status: string;
  downstream_table?: string | null;
  downstream_id?: string | null;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  created_at: string;
  updated_at: string;
  lineage_key: string;
}

export const SCRIBE_ACTION_ITEMS_COLUMNS = [
  'id',
  'clinic_id',
  'session_id',
  'patient_id',
  'item_type',
  'description',
  'assignee_role',
  'due_date',
  'status',
  'downstream_table',
  'downstream_id',
  'reviewed_by',
  'reviewed_at',
  'created_at',
  'updated_at',
  'lineage_key',
] as const;

export type ScribeActionItemsColumn = typeof SCRIBE_ACTION_ITEMS_COLUMNS[number];
