// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface ShiftHandoversRow {
  id: string;
  clinic_id: string;
  ward?: string | null;
  shift_type: string;
  summary_manual?: string | null;
  key_issues?: unknown | null;
  patient_updates?: unknown | null;
  outgoing_staff_id?: string | null;
  incoming_staff_id?: string | null;
  pending_actions?: unknown | null;
  shift_date?: string | null;
  status: string;
  created_by_id?: string | null;
  acknowledged_at?: string | null;
  created_at: string;
  updated_at: string;
  lock_version: number;
}

export const SHIFT_HANDOVERS_COLUMNS = [
  'id',
  'clinic_id',
  'ward',
  'shift_type',
  'summary_manual',
  'key_issues',
  'patient_updates',
  'outgoing_staff_id',
  'incoming_staff_id',
  'pending_actions',
  'shift_date',
  'status',
  'created_by_id',
  'acknowledged_at',
  'created_at',
  'updated_at',
  'lock_version',
] as const;

export type ShiftHandoversColumn = typeof SHIFT_HANDOVERS_COLUMNS[number];
