// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SideEffectSchedulesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  patient_medication_id?: string | null;
  schedule_type: string;
  frequency_weeks: number;
  next_due_date?: string | null;
  last_completed_date?: string | null;
  parameters: unknown;
  notes?: string | null;
  status: string;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const SIDE_EFFECT_SCHEDULES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'patient_medication_id',
  'schedule_type',
  'frequency_weeks',
  'next_due_date',
  'last_completed_date',
  'parameters',
  'notes',
  'status',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type SideEffectSchedulesColumn = typeof SIDE_EFFECT_SCHEDULES_COLUMNS[number];
