// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SmartLaunchContextsRow {
  id: string;
  launch_token: string;
  client_id: string;
  clinic_id: string;
  user_id: string;
  patient_id?: string | null;
  encounter_id?: string | null;
  scopes: unknown;
  expires_at: string;
  created_at: string;
  consumed_at?: string | null;
}

export const SMART_LAUNCH_CONTEXTS_COLUMNS = [
  'id',
  'launch_token',
  'client_id',
  'clinic_id',
  'user_id',
  'patient_id',
  'encounter_id',
  'scopes',
  'expires_at',
  'created_at',
  'consumed_at',
] as const;

export type SmartLaunchContextsColumn = typeof SMART_LAUNCH_CONTEXTS_COLUMNS[number];
