// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SmartAppsRow {
  id: string;
  clinic_id: string;
  client_id: string;
  client_secret_hash?: string | null;
  name: string;
  description?: string | null;
  vendor?: string | null;
  vendor_url?: string | null;
  logo_url?: string | null;
  app_type: string;
  redirect_uris: unknown;
  scopes: unknown;
  launch_modes: unknown;
  is_active: boolean;
  is_approved: boolean;
  approved_by_id?: string | null;
  approved_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const SMART_APPS_COLUMNS = [
  'id',
  'clinic_id',
  'client_id',
  'client_secret_hash',
  'name',
  'description',
  'vendor',
  'vendor_url',
  'logo_url',
  'app_type',
  'redirect_uris',
  'scopes',
  'launch_modes',
  'is_active',
  'is_approved',
  'approved_by_id',
  'approved_at',
  'created_at',
  'updated_at',
] as const;

export type SmartAppsColumn = typeof SMART_APPS_COLUMNS[number];
