// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SpecialtiesRow {
  code: string;
  display: string;
  system: string;
  snomed_code?: string | null;
  sort_order: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const SPECIALTIES_COLUMNS = [
  'code',
  'display',
  'system',
  'snomed_code',
  'sort_order',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type SpecialtiesColumn = typeof SPECIALTIES_COLUMNS[number];
