// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffSpecialtiesRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  specialty_code: string;
  is_primary: boolean;
  credential_ref?: string | null;
  created_at: string;
  created_by?: string | null;
  updated_at: string;
  deleted_at?: string | null;
}

export const STAFF_SPECIALTIES_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'specialty_code',
  'is_primary',
  'credential_ref',
  'created_at',
  'created_by',
  'updated_at',
  'deleted_at',
] as const;

export type StaffSpecialtiesColumn = typeof STAFF_SPECIALTIES_COLUMNS[number];
