// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffTeamAssignmentsRow {
  id: string;
  staff_id: string;
  org_unit_id: string;
  start_date: string;
  end_date?: string | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
  clinic_id: string;
}

export const STAFF_TEAM_ASSIGNMENTS_COLUMNS = [
  'id',
  'staff_id',
  'org_unit_id',
  'start_date',
  'end_date',
  'is_active',
  'created_at',
  'updated_at',
  'clinic_id',
] as const;

export type StaffTeamAssignmentsColumn = typeof STAFF_TEAM_ASSIGNMENTS_COLUMNS[number];
