// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffLeaveRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  leave_type: string;
  start_date: string;
  end_date: string;
  reason?: string | null;
  cover_staff_id?: string | null;
  status: string;
  requested_by?: string | null;
  approved_by_staff_id?: string | null;
  approved_at?: string | null;
  created_at: string;
  updated_at: string;
}

export const STAFF_LEAVE_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'leave_type',
  'start_date',
  'end_date',
  'reason',
  'cover_staff_id',
  'status',
  'requested_by',
  'approved_by_staff_id',
  'approved_at',
  'created_at',
  'updated_at',
] as const;

export type StaffLeaveColumn = typeof STAFF_LEAVE_COLUMNS[number];
