// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffFcmTokensRow {
  id: string;
  clinic_id: string;
  staff_id: string;
  device_token: string;
  platform: string;
  last_seen_at: string;
  created_at: string;
  deleted_at?: string | null;
}

export const STAFF_FCM_TOKENS_COLUMNS = [
  'id',
  'clinic_id',
  'staff_id',
  'device_token',
  'platform',
  'last_seen_at',
  'created_at',
  'deleted_at',
] as const;

export type StaffFcmTokensColumn = typeof STAFF_FCM_TOKENS_COLUMNS[number];
