// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffPermissionsRow {
  id: string;
  staff_id: string;
  permission_id: string;
  granted_at: string;
  granted_by?: string | null;
  created_at: string;
  updated_at?: string | null;
}

export const STAFF_PERMISSIONS_COLUMNS = [
  'id',
  'staff_id',
  'permission_id',
  'granted_at',
  'granted_by',
  'created_at',
  'updated_at',
] as const;

export type StaffPermissionsColumn = typeof STAFF_PERMISSIONS_COLUMNS[number];
