// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffRow {
  id: string;
  clinic_id: string;
  given_name: string;
  family_name: string;
  preferred_name?: string | null;
  email: string;
  password_hash: string;
  role: string;
  discipline?: string | null;
  discipline_id?: string | null;
  phone_mobile?: string | null;
  phone_work?: string | null;
  ahpra_number?: string | null;
  prescriber_number?: string | null;
  provider_number?: string | null;
  hpii?: string | null;
  qualifications?: string | null;
  specialisation?: string | null;
  employment_type?: string | null;
  worker_type?: string | null;
  is_active: boolean;
  require_mfa: boolean;
  has_mfa_configured: boolean;
  mfa_enabled?: boolean | null;
  mfa_secret?: string | null;
  recovery_codes?: unknown | null;
  must_change_password?: boolean | null;
  failed_login_attempts: number;
  locked_until?: string | null;
  last_login_at?: string | null;
  outlook_email?: string | null;
  outlook_refresh_token?: string | null;
  outlook_token_expires_at?: number | null;
  outlook_calendar_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
  digital_signature?: string | null;
  max_concurrent_sessions: number;
}

export const STAFF_COLUMNS = [
  'id',
  'clinic_id',
  'given_name',
  'family_name',
  'preferred_name',
  'email',
  'password_hash',
  'role',
  'discipline',
  'discipline_id',
  'phone_mobile',
  'phone_work',
  'ahpra_number',
  'prescriber_number',
  'provider_number',
  'hpii',
  'qualifications',
  'specialisation',
  'employment_type',
  'worker_type',
  'is_active',
  'require_mfa',
  'has_mfa_configured',
  'mfa_enabled',
  'mfa_secret',
  'recovery_codes',
  'must_change_password',
  'failed_login_attempts',
  'locked_until',
  'last_login_at',
  'outlook_email',
  'outlook_refresh_token',
  'outlook_token_expires_at',
  'outlook_calendar_id',
  'created_at',
  'updated_at',
  'deleted_at',
  'digital_signature',
  'max_concurrent_sessions',
] as const;

export type StaffColumn = typeof STAFF_COLUMNS[number];
