// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffSettingsRow {
  id: string;
  staff_id: string;
  setting_key: string;
  setting_value?: unknown | null;
  created_at: string;
  updated_at: string;
}

export const STAFF_SETTINGS_COLUMNS = [
  'id',
  'staff_id',
  'setting_key',
  'setting_value',
  'created_at',
  'updated_at',
] as const;

export type StaffSettingsColumn = typeof STAFF_SETTINGS_COLUMNS[number];
