// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffModuleAccessRow {
  id: string;
  staff_id: string;
  clinic_id: string;
  module: string;
  access_level: string;
  granted_by_id?: string | null;
  can_delegate_this: boolean;
  created_at: string;
  updated_at: string;
}

export const STAFF_MODULE_ACCESS_COLUMNS = [
  'id',
  'staff_id',
  'clinic_id',
  'module',
  'access_level',
  'granted_by_id',
  'can_delegate_this',
  'created_at',
  'updated_at',
] as const;

export type StaffModuleAccessColumn = typeof STAFF_MODULE_ACCESS_COLUMNS[number];
