// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StaffSessionsRow {
  id: string;
  staff_id: string;
  clinic_id: string;
  refresh_token: string;
  user_agent?: string | null;
  ip_address?: string | null;
  expires_at: string;
  created_at: string;
  updated_at: string;
  revoked_at?: string | null;
  family_id: string;
  lock_version: number;
}

export const STAFF_SESSIONS_COLUMNS = [
  'id',
  'staff_id',
  'clinic_id',
  'refresh_token',
  'user_agent',
  'ip_address',
  'expires_at',
  'created_at',
  'updated_at',
  'revoked_at',
  'family_id',
  'lock_version',
] as const;

export type StaffSessionsColumn = typeof STAFF_SESSIONS_COLUMNS[number];
