// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StateMhaFormsRow {
  id: string;
  state_code: string;
  form_code: string;
  name: string;
  act_reference: string;
  section_reference?: string | null;
  field_schema: unknown;
  requires_authorised_psychiatrist: boolean;
  max_duration_days?: number | null;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const STATE_MHA_FORMS_COLUMNS = [
  'id',
  'state_code',
  'form_code',
  'name',
  'act_reference',
  'section_reference',
  'field_schema',
  'requires_authorised_psychiatrist',
  'max_duration_days',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type StateMhaFormsColumn = typeof STATE_MHA_FORMS_COLUMNS[number];
