// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StepCareRuleEventsRow {
  id: string;
  clinic_id: string;
  rule_id: string;
  patient_id: string;
  pathway_id?: string | null;
  event_type: string;
  fingerprint: string;
  details: unknown;
  created_at: string;
}

export const STEP_CARE_RULE_EVENTS_COLUMNS = [
  'id',
  'clinic_id',
  'rule_id',
  'patient_id',
  'pathway_id',
  'event_type',
  'fingerprint',
  'details',
  'created_at',
] as const;

export type StepCareRuleEventsColumn = typeof STEP_CARE_RULE_EVENTS_COLUMNS[number];
