// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface StructuredObservationsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  staff_id?: string | null;
  observation_type: string;
  location?: string | null;
  mood?: string | null;
  behaviour?: string | null;
  risk_concerns?: string | null;
  sleep_quality?: string | null;
  values?: unknown | null;
  notes?: string | null;
  observed_at: string;
  created_at: string;
  escalation_required: boolean;
  escalation_notes?: string | null;
}

export const STRUCTURED_OBSERVATIONS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'staff_id',
  'observation_type',
  'location',
  'mood',
  'behaviour',
  'risk_concerns',
  'sleep_quality',
  'values',
  'notes',
  'observed_at',
  'created_at',
  'escalation_required',
  'escalation_notes',
] as const;

export type StructuredObservationsColumn = typeof STRUCTURED_OBSERVATIONS_COLUMNS[number];
