// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SubscriberBrandingRow {
  id: string;
  clinic_id: string;
  logo_url?: string | null;
  primary_color?: string | null;
  sidebar_color?: string | null;
  sidebar_title?: string | null;
  sidebar_subtitle?: string | null;
  org_name?: string | null;
  created_at: string;
  updated_at: string;
}

export const SUBSCRIBER_BRANDING_COLUMNS = [
  'id',
  'clinic_id',
  'logo_url',
  'primary_color',
  'sidebar_color',
  'sidebar_title',
  'sidebar_subtitle',
  'org_name',
  'created_at',
  'updated_at',
] as const;

export type SubscriberBrandingColumn = typeof SUBSCRIBER_BRANDING_COLUMNS[number];
