// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SubscriptionsRow {
  id: string;
  clinic_id: string;
  plan_type: string;
  seats: number;
  price_per_month: string;
  price_per_year?: string | null;
  discount_percent?: string | null;
  discount_amount?: string | null;
  status: string;
  start_date: string;
  end_date?: string | null;
  renewal_date?: string | null;
  reminder_days: number;
  notes?: string | null;
  created_at: string;
  updated_at: string;
}

export const SUBSCRIPTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'plan_type',
  'seats',
  'price_per_month',
  'price_per_year',
  'discount_percent',
  'discount_amount',
  'status',
  'start_date',
  'end_date',
  'renewal_date',
  'reminder_days',
  'notes',
  'created_at',
  'updated_at',
] as const;

export type SubscriptionsColumn = typeof SUBSCRIPTIONS_COLUMNS[number];
