// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface SurgicalCasesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  procedure_code: string;
  procedure_display: string;
  primary_surgeon_id?: string | null;
  planned_date: string;
  urgency: string;
  asa_class: unknown;
  consent_status: string;
  status: string;
  note?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const SURGICAL_CASES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'procedure_code',
  'procedure_display',
  'primary_surgeon_id',
  'planned_date',
  'urgency',
  'asa_class',
  'consent_status',
  'status',
  'note',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type SurgicalCasesColumn = typeof SURGICAL_CASES_COLUMNS[number];
