// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TasksRow {
  id: string;
  clinic_id: string;
  patient_id?: string | null;
  episode_id?: string | null;
  assigned_to_id?: string | null;
  assigned_by_id?: string | null;
  title: string;
  description?: string | null;
  task_type?: string | null;
  priority?: string | null;
  status?: string | null;
  due_date?: string | null;
  completed_at?: string | null;
  completed_by_id?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  lock_version: number;
}

export const TASKS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'assigned_to_id',
  'assigned_by_id',
  'title',
  'description',
  'task_type',
  'priority',
  'status',
  'due_date',
  'completed_at',
  'completed_by_id',
  'notes',
  'created_at',
  'updated_at',
  'lock_version',
] as const;

export type TasksColumn = typeof TASKS_COLUMNS[number];
