// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TemplatesRow {
  id: string;
  clinic_id: string;
  name: string;
  type?: string | null;
  description?: string | null;
  category: string;
  content?: unknown | null;
  is_active: boolean;
  status: string;
  sort_order: number;
  created_by_id?: string | null;
  published_at?: string | null;
  retired_at?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const TEMPLATES_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'type',
  'description',
  'category',
  'content',
  'is_active',
  'status',
  'sort_order',
  'created_by_id',
  'published_at',
  'retired_at',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type TemplatesColumn = typeof TEMPLATES_COLUMNS[number];
