// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TemplateSectionsRow {
  id: string;
  template_id: string;
  section_type?: string | null;
  label?: string | null;
  options?: unknown | null;
  sort_order?: number | null;
  is_required?: boolean | null;
  created_at: string;
}

export const TEMPLATE_SECTIONS_COLUMNS = [
  'id',
  'template_id',
  'section_type',
  'label',
  'options',
  'sort_order',
  'is_required',
  'created_at',
] as const;

export type TemplateSectionsColumn = typeof TEMPLATE_SECTIONS_COLUMNS[number];
