// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TmsSessionsRow {
  id: string;
  course_id: string;
  clinic_id: string;
  session_number: number;
  session_date: string;
  pulses_delivered?: number | null;
  intensity_percent?: number | null;
  coil_position?: string | null;
  duration_minutes?: number | null;
  adverse_events?: string | null;
  patient_tolerance: string;
  administered_by: string;
  phq9_score?: number | null;
  clinician_notes?: string | null;
  created_at: string;
  updated_at: string;
}

export const TMS_SESSIONS_COLUMNS = [
  'id',
  'course_id',
  'clinic_id',
  'session_number',
  'session_date',
  'pulses_delivered',
  'intensity_percent',
  'coil_position',
  'duration_minutes',
  'adverse_events',
  'patient_tolerance',
  'administered_by',
  'phq9_score',
  'clinician_notes',
  'created_at',
  'updated_at',
] as const;

export type TmsSessionsColumn = typeof TMS_SESSIONS_COLUMNS[number];
