// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TnmStageGroupsRow {
  id: string;
  clinic_id: string;
  condition_id: string;
  t?: string | null;
  n?: string | null;
  m?: string | null;
  stage_group?: string | null;
  staged_at: string;
  staged_by_staff_id?: string | null;
  notes?: string | null;
  created_at: string;
}

export const TNM_STAGE_GROUPS_COLUMNS = [
  'id',
  'clinic_id',
  'condition_id',
  't',
  'n',
  'm',
  'stage_group',
  'staged_at',
  'staged_by_staff_id',
  'notes',
  'created_at',
] as const;

export type TnmStageGroupsColumn = typeof TNM_STAGE_GROUPS_COLUMNS[number];
