// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TrainingExportRequestsRow {
  id: string;
  clinic_id: string;
  requested_by_id: string;
  requested_at: string;
  approved_by_id?: string | null;
  approved_at?: string | null;
  status: string;
  format: string;
  reason?: string | null;
  rejection_reason?: string | null;
  download_token?: string | null;
  downloaded_at?: string | null;
  row_count?: number | null;
  expires_at: string;
  created_at: string;
}

export const TRAINING_EXPORT_REQUESTS_COLUMNS = [
  'id',
  'clinic_id',
  'requested_by_id',
  'requested_at',
  'approved_by_id',
  'approved_at',
  'status',
  'format',
  'reason',
  'rejection_reason',
  'download_token',
  'downloaded_at',
  'row_count',
  'expires_at',
  'created_at',
] as const;

export type TrainingExportRequestsColumn = typeof TRAINING_EXPORT_REQUESTS_COLUMNS[number];
