// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TrainingCorpusItemsRow {
  id: string;
  source_clinic_id: string;
  source_session_id?: string | null;
  scrubber_version: string;
  sanitised_transcript: string;
  redaction_summary: unknown;
  status: string;
  reviewed_by?: string | null;
  reviewed_at?: string | null;
  rejection_reason?: string | null;
  created_at: string;
}

export const TRAINING_CORPUS_ITEMS_COLUMNS = [
  'id',
  'source_clinic_id',
  'source_session_id',
  'scrubber_version',
  'sanitised_transcript',
  'redaction_summary',
  'status',
  'reviewed_by',
  'reviewed_at',
  'rejection_reason',
  'created_at',
] as const;

export type TrainingCorpusItemsColumn = typeof TRAINING_CORPUS_ITEMS_COLUMNS[number];
