// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TreatmentPathwaysRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  name: string;
  status: string;
  milestones?: unknown | null;
  created_at: string;
  updated_at?: string | null;
  lock_version: number;
  updated_by_staff_id?: string | null;
}

export const TREATMENT_PATHWAYS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'name',
  'status',
  'milestones',
  'created_at',
  'updated_at',
  'lock_version',
  'updated_by_staff_id',
] as const;

export type TreatmentPathwaysColumn = typeof TREATMENT_PATHWAYS_COLUMNS[number];
