// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TreatmentPlansRow {
  id: string;
  patient_id: string;
  clinic_id: string;
  episode_id?: string | null;
  staff_id?: string | null;
  title?: string | null;
  status?: string | null;
  goals?: unknown | null;
  interventions?: unknown | null;
  review_date?: string | null;
  created_at: string;
  updated_at: string;
}

export const TREATMENT_PLANS_COLUMNS = [
  'id',
  'patient_id',
  'clinic_id',
  'episode_id',
  'staff_id',
  'title',
  'status',
  'goals',
  'interventions',
  'review_date',
  'created_at',
  'updated_at',
] as const;

export type TreatmentPlansColumn = typeof TREATMENT_PLANS_COLUMNS[number];
