// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface TumourBoardDecisionsRow {
  id: string;
  clinic_id: string;
  condition_id: string;
  meeting_date: string;
  recommendation: string;
  rationale?: string | null;
  attendee_staff_ids?: unknown | null;
  chaired_by_staff_id?: string | null;
  created_at: string;
}

export const TUMOUR_BOARD_DECISIONS_COLUMNS = [
  'id',
  'clinic_id',
  'condition_id',
  'meeting_date',
  'recommendation',
  'rationale',
  'attendee_staff_ids',
  'chaired_by_staff_id',
  'created_at',
] as const;

export type TumourBoardDecisionsColumn = typeof TUMOUR_BOARD_DECISIONS_COLUMNS[number];
