// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface VivaAlertThresholdsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  tracking_type: string;
  direction: string;
  threshold: string;
  consecutive_days: number;
  is_active: boolean;
  created_by?: string | null;
  created_at: string;
  updated_at: string;
}

export const VIVA_ALERT_THRESHOLDS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'tracking_type',
  'direction',
  'threshold',
  'consecutive_days',
  'is_active',
  'created_by',
  'created_at',
  'updated_at',
] as const;

export type VivaAlertThresholdsColumn = typeof VIVA_ALERT_THRESHOLDS_COLUMNS[number];
