// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface VoicePatientPreferencesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  opted_out: boolean;
  opted_out_at?: string | null;
  opt_out_channel?: string | null;
  preferred_call_start?: string | null;
  preferred_call_end?: string | null;
  preferred_call_time?: string | null;
  preferred_days?: unknown | null;
  preferred_call_days?: unknown | null;
  created_at: string;
  updated_at: string;
}

export const VOICE_PATIENT_PREFERENCES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'opted_out',
  'opted_out_at',
  'opt_out_channel',
  'preferred_call_start',
  'preferred_call_end',
  'preferred_call_time',
  'preferred_days',
  'preferred_call_days',
  'created_at',
  'updated_at',
] as const;

export type VoicePatientPreferencesColumn = typeof VOICE_PATIENT_PREFERENCES_COLUMNS[number];
