// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface VoiceCallsRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  episode_id?: string | null;
  script_id?: string | null;
  initiated_by_id?: string | null;
  direction: string;
  status: string;
  phone_number_masked?: string | null;
  duration_seconds?: number | null;
  started_at?: string | null;
  ended_at?: string | null;
  call_sid?: string | null;
  transcript_available: boolean;
  transcript_s3_key?: string | null;
  outcome?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const VOICE_CALLS_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'episode_id',
  'script_id',
  'initiated_by_id',
  'direction',
  'status',
  'phone_number_masked',
  'duration_seconds',
  'started_at',
  'ended_at',
  'call_sid',
  'transcript_available',
  'transcript_s3_key',
  'outcome',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type VoiceCallsColumn = typeof VOICE_CALLS_COLUMNS[number];
