// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface VoiceScriptsRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  script_type: string;
  version: number;
  content: string;
  is_active: boolean;
  created_by_id?: string | null;
  created_at: string;
  updated_at: string;
}

export const VOICE_SCRIPTS_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'script_type',
  'version',
  'content',
  'is_active',
  'created_by_id',
  'created_at',
  'updated_at',
] as const;

export type VoiceScriptsColumn = typeof VOICE_SCRIPTS_COLUMNS[number];
