// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface WaitlistEntriesRow {
  id: string;
  clinic_id: string;
  patient_id: string;
  referral_id?: string | null;
  preferred_clinician_id?: string | null;
  priority: string;
  preferred_time_of_day?: string | null;
  preferred_start_time?: unknown | null;
  preferred_end_time?: unknown | null;
  added_date: string;
  target_appointment_by?: string | null;
  status: string;
  converted_appointment_id?: string | null;
  notes?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const WAITLIST_ENTRIES_COLUMNS = [
  'id',
  'clinic_id',
  'patient_id',
  'referral_id',
  'preferred_clinician_id',
  'priority',
  'preferred_time_of_day',
  'preferred_start_time',
  'preferred_end_time',
  'added_date',
  'target_appointment_by',
  'status',
  'converted_appointment_id',
  'notes',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type WaitlistEntriesColumn = typeof WAITLIST_ENTRIES_COLUMNS[number];
