// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface WebauthnCredentialsRow {
  id: string;
  staff_id: string;
  clinic_id: string;
  credential_id: string;
  public_key: string;
  counter: number;
  transports?: unknown | null;
  device_name?: string | null;
  aaguid?: string | null;
  backup_eligible: boolean;
  backup_state: boolean;
  last_used_at?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const WEBAUTHN_CREDENTIALS_COLUMNS = [
  'id',
  'staff_id',
  'clinic_id',
  'credential_id',
  'public_key',
  'counter',
  'transports',
  'device_name',
  'aaguid',
  'backup_eligible',
  'backup_state',
  'last_used_at',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type WebauthnCredentialsColumn = typeof WEBAUTHN_CREDENTIALS_COLUMNS[number];
