// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface WebhookSecretsRow {
  id: string;
  clinic_id: string;
  source: string;
  hmac_secret: string;
  signature_header: string;
  timestamp_header?: string | null;
  replay_window_seconds: number;
  rate_limit_per_minute: number;
  ip_allowlist?: string | null;
  queue_name: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export const WEBHOOK_SECRETS_COLUMNS = [
  'id',
  'clinic_id',
  'source',
  'hmac_secret',
  'signature_header',
  'timestamp_header',
  'replay_window_seconds',
  'rate_limit_per_minute',
  'ip_allowlist',
  'queue_name',
  'is_active',
  'created_at',
  'updated_at',
] as const;

export type WebhookSecretsColumn = typeof WEBHOOK_SECRETS_COLUMNS[number];
