// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface WebhookAuditLogRow {
  id: string;
  clinic_id?: string | null;
  source: string;
  payload_hash: string;
  nonce?: string | null;
  outcome: string;
  error_text?: string | null;
  job_id?: string | null;
  body_size?: number | null;
  source_ip?: string | null;
  received_at: string;
}

export const WEBHOOK_AUDIT_LOG_COLUMNS = [
  'id',
  'clinic_id',
  'source',
  'payload_hash',
  'nonce',
  'outcome',
  'error_text',
  'job_id',
  'body_size',
  'source_ip',
  'received_at',
] as const;

export type WebhookAuditLogColumn = typeof WEBHOOK_AUDIT_LOG_COLUMNS[number];
