// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface WorkflowsRow {
  id: string;
  clinic_id: string;
  name: string;
  description?: string | null;
  trigger_event: string;
  steps: unknown;
  is_active: boolean;
  created_by_staff_id?: string | null;
  created_at: string;
  updated_at: string;
  deleted_at?: string | null;
}

export const WORKFLOWS_COLUMNS = [
  'id',
  'clinic_id',
  'name',
  'description',
  'trigger_event',
  'steps',
  'is_active',
  'created_by_staff_id',
  'created_at',
  'updated_at',
  'deleted_at',
] as const;

export type WorkflowsColumn = typeof WORKFLOWS_COLUMNS[number];
