// AUTO-GENERATED by scripts/generate-types-from-migrations.ts
// DO NOT EDIT MANUALLY. Run `npm run generate:types-from-migrations` to regenerate.
//
// Source: parsed from apps/api/migrations/*.ts (Knex builder calls only;
// raw SQL column DDL is rejected by check-no-column-ddl-in-raw-sql guard).

export interface WorkflowExecutionsRow {
  id: string;
  clinic_id: string;
  workflow_id: string;
  trigger_data?: unknown | null;
  status: string;
  steps_completed: number;
  total_steps: number;
  error_message?: string | null;
  step_results?: unknown | null;
  started_at: string;
  completed_at?: string | null;
}

export const WORKFLOW_EXECUTIONS_COLUMNS = [
  'id',
  'clinic_id',
  'workflow_id',
  'trigger_data',
  'status',
  'steps_completed',
  'total_steps',
  'error_message',
  'step_results',
  'started_at',
  'completed_at',
] as const;

export type WorkflowExecutionsColumn = typeof WORKFLOW_EXECUTIONS_COLUMNS[number];
