{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "signacare-sovereign-gpu-inference.fullname" . }}
  labels:
    {{- include "signacare-sovereign-gpu-inference.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "signacare-sovereign-gpu-inference.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            {{- toYaml .Values.networkPolicy.allowedIngress.namespaceSelector | nindent 12 }}
          podSelector:
            {{- toYaml .Values.networkPolicy.allowedIngress.podSelector | nindent 12 }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.port }}
{{- end }}
