apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "signacare-sovereign-gpu-inference.fullname" . }}
  labels:
    {{- include "signacare-sovereign-gpu-inference.labels" . | nindent 4 }}
automountServiceAccountToken: false
