apiVersion: v1
kind: Service
metadata:
  name: {{ include "signacare-sovereign-gpu-inference.fullname" . }}
  labels:
    {{- include "signacare-sovereign-gpu-inference.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "signacare-sovereign-gpu-inference.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
