import { Alert, Box, Typography } from '@mui/material';
import SmartToyOutlinedIcon from '@mui/icons-material/SmartToyOutlined';

interface Props {
  onDismiss?: () => void;
}

export const AIDraftBanner: React.FC<Props> = ({ onDismiss }) => (
  <Alert role="alert"
    severity="warning"
    icon={<SmartToyOutlinedIcon />}
    onClose={onDismiss}
    sx={{
      mb: 2,
      backgroundColor: '#FFF8E1',
      border: '1.5px solid #F0852C',
      color: '#3D484B',
      borderRadius: 2,
      '& .MuiAlert-icon': { color: '#F0852C' },
    }}
  >
    <Box>
      <Typography variant="subtitle2" fontWeight={700} sx={{ fontFamily: 'Albert Sans, sans-serif' }}>
        AI-Generated Draft
      </Typography>
      <Typography variant="body2" sx={{ fontFamily: 'Albert Sans, sans-serif' }}>
        This draft was generated by AI – please review before signing. Verify all clinical
        details, medications, and assessment findings for accuracy before countersigning.
      </Typography>
    </Box>
  </Alert>
);
